### ISSUE TITLE
After restart can't send messages in an old thread

### ISSUE THREAD

**Issue by QuinnTDIP** [Dragory/modmailbot#10]
I restarted the bot, and now previously open threads won't let me send messages, I can still talk, BUT it doesn't send to the user. Ideas?

**Comment by Dragory** [comment]
That's weird, it definitely works through restarts on my end. Do new threads work fine? What if the users in question send another message, does it go to the old thread (that you can't reply in) or create a new one?

**Comment by QuinnTDIP** [comment]
After a restart I tested & the bot creates a new channel IF I send it a new DM, ELSE it just won't let me send DMs through the old channel.

**Comment by QuinnTDIP** [comment]
EDIT: I redownloaded the updated version & it works fine between restarts, thanks!
