### ISSUE TITLE
Add option to disable bot mention notifications

### ISSUE THREAD

**Issue by chnaski** [Dragory/modmailbot#101]
I'd like to be able to turn off @mentions to the bot in the log channel.

**Comment by Dragory** [comment]
You change the role that is mentioned with the `mentionRole` setting, or set it to null to disable the mentions entirely.

This unfortunately applied to both new threads and the log channel, so if you *only* want to disable mentions in the log channel, that can't be done right now.

**Comment by JonasPardon** [comment]
Might be worth putting on the to-do list? I could see this being useful for some use cases.

**Comment by chnaski** [comment]
Dragory, i dont want to turn off all mentions. I want to turn off the fact that whenever someone mentions my bot in the main server, it goes to the log channel on the DM server.

**Comment by Dragory** [comment]
Yeah, I get that. Unfortunately there is no option for that at the moment. I'll leave this issue open and add it to the TODO though!

**Comment by chnaski** [comment]
Any ETA for this? One of my staff left my server due to this. Just wondering.

**Comment by Dragory** [comment]
Actually my bad, you can set the config option `pingOnBotMention` to `false` to disable the ping! For some reason I seem to have forgotten to document this option.
