### ISSUE TITLE
Crashing After About 15+ Channel Closes

### ISSUE THREAD

**Issue by Ragnarok345** [Dragory/modmailbot#104]
Exactly as the title says. I've had to use the bot for a massive re-verification that over 1,000 people on my server are still employed by the company the server is about. We recently started closing those channels, of which there about 200, and after every 10-15 or so, the bot crashes like it's under too heavy a workload, though just closing a few channels should be nothing. I'd post a picture from Terminal, but...the error changes almost every time. Any ideas what could be causing this?

**Comment by Dragory** [comment]
Hmm, could be the bot being rate limited by Discord, though I think Eris should handle that in the background(?). I'll need to run some tests. In the meanwhile, can you post one or two of the errors you got here, even if it changes almost every time?

**Comment by Ragnarok345** [comment]
Here’s one. 
![screen shot 2018-07-27 at 3 13 11 pm](https://user-images.githubusercontent.com/10534873/43348626-e0f06368-91af-11e8-9ce6-f0299ad31049.png)

**Comment by Dragory** [comment]
Hmm, it appears the bot's connection to the discord API is interrupted by something. It shouldn't be rate limits, since those would return a proper error code. Are you closing these threads with `!close` or by deleting the channels manually?

**Comment by Ragnarok345** [comment]
Here are a few more crashes. It looks like they're actually all the same now, unlike before. 
![image](https://user-images.githubusercontent.com/10534873/43672695-5462042e-9768-11e8-8657-2432a6543541.png)
![image](https://user-images.githubusercontent.com/10534873/43672696-57dfb39e-9768-11e8-8da8-aa937a01b74d.png)
![image](https://user-images.githubusercontent.com/10534873/43672699-5b23156e-9768-11e8-9b9a-7d3b60ad5178.png)
Also, I know I always close channels with the !close command, but I don't know for sure about the rest of my staff. I'm asking and will let you know. Also, the bot crashed again today, and the heavy workload it was under has ended. Just in case it helps.

**Comment by Ragnarok345** [comment]
Ok, I updated to the newest version of the bot, which I haven't done since March, because I didn't realize it was being updated still, and now it's crashing more than ever. It's gone down four times today alone. My staff are really pressuring me to get a new bot or something. What do I do here? Here's the information about what happened. 
![image](https://user-images.githubusercontent.com/10534873/43751053-1b68def0-99b0-11e8-83a3-8e51ece9e459.png)

**Comment by Dragory** [comment]
Are you using the closeMessage option? If so, does it crash without it?

**Comment by Ragnarok345** [comment]
Yeah, I'm using closeMessage. It did crash without it, but now you say that I notice it's become more frequent since I started. Also, I would love to try that, but I really don't know what that means. I looked in the config options on the main page, and I don't understand it. What do I do, exactly?

**Comment by Dragory** [comment]
Did it crash with `closeMessage` completely removed or set to e.g. `""`? If the latter, try removing it from the config entirely.

For the "url" thing, find out your IP (via e.g. http://ip4.me/) and then set the url option to:
`"http://ip:8890"` (replace `ip` with your IP, and 8890 with the port you're using if you've changed that). This way the bot won't have to try to figure out your IP at runtime.

**Comment by Ragnarok345** [comment]
I _think_ that may have done it, but I'm not sure yet. Also, is there any way to make relaySmallAttachmentsAsAttachments handle larger file sizes? Many pictures that are sent to us are too big. If not changing it, there any other way around it? I just find it kind of surprising that it's so small, with Discord's limit being 8 mb.

**Comment by Dragory** [comment]
At the moment there is no setting for the file size limit of `relaySmallAttachmentsAsAttachments`, but I could definitely add one. I'll add it on the TODO.

**Comment by Dragory** [comment]
I pushed a new update that might help with the ECONNRESET errors. Can you give it a try?
The update also includes a new `smallAttachmentLimit` option to control the file size limit of `relaySmallAttachmentsAsAttachments` (in bytes).

**Comment by Ragnarok345** [comment]
Cool, thanks! I will say that the url thing seems to have fixed it, so if it works after I update, it could be for either reason...

**Comment by Ragnarok345** [comment]
How exactly do I need to format the smallAttachmentLimit? I entered it as "smallAttachmentLimit": "8000", tried to send a 3.5 mb file, and it didn't work.

**Comment by Dragory** [comment]
You might have to forward the port in your router - make sure you've done that and see if it works.

**Comment by Ragnarok345** [comment]
I'm...not exactly sure how to do that either.

**Comment by Ragnarok345** [comment]
Just woke up to this. 
![screen shot 2018-08-08 at 9 39 55 am](https://user-images.githubusercontent.com/10534873/43851454-9cac2284-9aef-11e8-8cd8-bf7f6be80d4a.png)

**Comment by Ragnarok345** [comment]
Just got the weirdest one yet. Here's the entire Terminal....thing. Whatever you'd call it. From bringing it online to crashing. 
`Last login: Wed Aug  8 02:20:56 on ttys001
Clarks-Mac-mini:~ David$ cd /Users/David/Verifier && npm start
Loading modules...
Connecting to Discord...
Connected! Now listening to DMs.
Connected! Now listening to DMs.
[NOTE] Creating new thread channel noah-lauzier-4105
Closing thread 885a1d58-67d9-45f6-8373-ab177afa7365
Deleting channel 476851104357810176
[NOTE] Creating new thread channel ragnarok-1268
Closing thread 4851d3ce-ef80-4f8d-bd8d-5758abdb55b2
Deleting channel 476880038285934594
[NOTE] Creating new thread channel boombastic-6575
[NOTE] Creating new thread channel grim-rx-8853
Closing thread c5af74ad-8a8f-4673-8957-79a9cf06ad5c
Deleting channel 477128950494265345
[NOTE] Creating new thread channel saad823-5667
[NOTE] Creating new thread channel bdoge-1077
[NOTE] Creating new thread channel indianmagic-6088
[NOTE] Creating new thread channel evos-kjdogg-2381
[NOTE] Creating new thread channel bacon-0560
Closing thread f32ed6c2-483e-4919-a55f-8b1419232e35
Deleting channel 477175255492722708
Closing thread 5bf2ea2c-2bd4-4d63-aa09-010618d7532a
Deleting channel 477184563324518401
[NOTE] Creating new thread channel evos-kjdogg-2381
[NOTE] Creating new thread channel skins-5702
[NOTE] Creating new thread channel coolcasey-1048
Closing thread ec026395-aee2-49a9-b093-6973b7f7ea1b
Deleting channel 477184973271466016
Closing thread 828498e9-3038-41b9-be10-bf554341d90a
Deleting channel 477186666180902912
[NOTE] Creating new thread channel jav-1234
[NOTE] Creating new thread channel jav-1234
Error creating modmail channel for Jav#1234!
{ Error: Request timed out (>15000ms) on POST /guilds/424035999715426305/channels
    at ClientRequest.<anonymous> (/Users/David/Verifier/node_modules/eris/lib/rest/RequestHandler.js:309:32)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
  req: 
   ClientRequest {
     domain: null,
     _events: { aborted: [Object], error: [Object], response: [Array] },
     _eventsCount: 3,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 64,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 441,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: [Object],
        _httpMessage: [Circular],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 120230929,
        _destroyed: false,
        read: [Function],
        _consuming: true,
        _called: true,
        [Symbol(asyncId)]: 518343,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 518350,
        [Symbol(triggerAsyncId)]: 518346 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 441,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: [Object],
        _httpMessage: [Circular],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 120230929,
        _destroyed: false,
        read: [Function],
        _consuming: true,
        _called: true,
        [Symbol(asyncId)]: 518343,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 518350,
        [Symbol(triggerAsyncId)]: 518346 },
     _header: 'POST /api/v7/guilds/424035999715426305/channels HTTP/1.1\r\nUser-Agent: DiscordBot (https://github.com/abalabahaha/eris, 0.8.4)\r\nAccept-Encoding: gzip,deflate\r\nAuthorization: Bot NDI2MjIwNzgwNDI3MjgwMzg1.DZS03Q.EYnhsmpI8DHxHObVRjRdCcsA0sM\r\nX-Audit-Log-Reason: New%20ModMail%20thread\r\nContent-Type: application/json\r\nHost: discordapp.com\r\nConnection: close\r\nContent-Length: 64\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/api/v7/guilds/424035999715426305/channels',
     _ended: false,
     res: null,
     aborted: 1533866646941,
     timeoutCb: [Function: emitTimeout],
     upgradeOrConnect: false,
     parser: 
      HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
        _headers: [],
        _url: '',
        _consumed: false,
        socket: [Object],
        incoming: null,
        outgoing: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncomingClient] },
     maxHeadersCount: null,
     [Symbol(outHeadersKey)]: 
      { 'user-agent': [Array],
        'accept-encoding': [Array],
        authorization: [Array],
        'x-audit-log-reason': [Array],
        'content-type': [Array],
        host: [Array] } } }
Clarks-Mac-mini:Verifier David$ 
`

**Comment by Dragory** [comment]
Ah yeah, that's just a timeout, can happen if the API server is down or laggy. For some reason the error is really long-winded though.

Also, those screenshots there include your bot token - I recommend changing it ASAP!

**Comment by Ragnarok345** [comment]
Alright, I will, thanks! Also, did you see the last comment I left? _After_ the patch you released, I had it do the error con reset, or whatever it says. Only once since then, but it has happened.

**Comment by Dragory** [comment]
Yeah, and I actually noticed a few of those errors on my own setup as well. I think it's just random connection problems, so I'll probably add an error handler that more or less just ignores them (unless there's a bunch of them in a short amount of time).

**Comment by Ragnarok345** [comment]
Alright. I'll keep updated and see what happens.

**Comment by Ragnarok345** [comment]
![image](https://user-images.githubusercontent.com/10534873/44295775-c4facc00-a264-11e8-9d46-6f1bcc4003f9.png)
It ran fine for several days, but crashed twice in the last hour. See above.

**Comment by Dragory** [comment]
I will be pushing an update to help with the ECONNRESET errors sometime after next week. Until then, I recommend using an auto-restart utility of some sort, such as `pm2`.

**Comment by Ragnarok345** [comment]
I have no idea how to use pm2. I tried to look it up, but it's way over my head at this point. I'm learning more, but I'm not there yet. Unless you might be able to tell me simply how to use it with this....?

**Comment by Ragnarok345** [comment]
Any update on that...er, update? Bot is still crashing semi-frequently.

**Comment by Dragory** [comment]
I haven't pushed a fix for this yet. You don't need to use `pm2` specifically, any auto-restart program would work. Follow issue #88 for updates on the ECONNRESET fix.
