### ISSUE TITLE
Alternative log locations

### ISSUE THREAD

**Issue by TheBadGuyTeam** [Dragory/modmailbot#106]
Can I make my logs get written to txts and get posted to discord?

**Comment by Dragory** [comment]
This is currently not possible. Alternative log destinations are on my roadmap, but they're not a very high priority.

**Comment by mesub7** [comment]
Hi there!
As of V3, you can now save logs as an attachment (a text file).
See more about it [here](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#logstorage)

**Comment by DarkView** [comment]
Merged with #55)
