### ISSUE TITLE
Bot Crashes when someone blocks it and we try to close

### ISSUE THREAD

**Issue by mattsilver1** [Dragory/modmailbot#109]
![image](https://user-images.githubusercontent.com/40540813/43377686-0d686b2a-9390-11e8-851c-f53a294cfb1a.png)

So basically, the bot keeps trying to send a message to someone that blocked the bot or left the server. Anytime that we try to close a thread or reply to a thread w/ a user that leave the main guild or blocked the bot, it completely errors out and crashes.

**Comment by Dragory** [comment]
Is this with `closeMessage` set? I know there are some checks against blocks in the regular !reply command, but those might not apply to the close message.

**Comment by mattsilver1** [comment]
Thought I'd re-open this since it's kind of related. Basically, the bot isn't autoclosing a thread that is marked to be closed after a certain amount of minutes. It closes threads fine now with just ``!close`` but isn't properly closing threads that have a time set.

**Comment by mattsilver1** [comment]
Oh and we're still having the issue of a failed close when the bot is blocked by the user.

**Comment by Dragory** [comment]
Are you experiencing the failed close even with the change in `Thread.js` I mentioned above?

**Comment by Dragory** [comment]
Can you post another screenshot of the error it's giving now?

**Comment by mattsilver1** [comment]
It appears to be the same error.

**Comment by Dragory** [comment]
By same error, which one do you mean? The original picture had 2 errors in it. Are you still getting both of them?

**Comment by LookOutForMe** [comment]
Got the same issue.

**Comment by bulletproof08** [comment]
Same error
![screenshot_2](https://user-images.githubusercontent.com/39467878/43997865-3abda06a-9de8-11e8-8e2f-31378dceb8f5.png)

User left, trying to close & bot crashes

**Comment by mattsilver1** [comment]
@bulletproof08 Take a look at #114. It should help.
