### ISSUE TITLE
Cannot display logs. 

### ISSUE THREAD

**Issue by LookOutForMe** [Dragory/modmailbot#113]
I am hosting on glitch.com. The logs are not being displayed or "takes too long to respond". An alternative or a way to fix this will be appreciated. Thank you for the help.

**Comment by idcw0tdisism8** [comment]
If you PC host it's better, glitch.com would suck for it.

**Comment by LookOutForMe** [comment]
Since I am not able to host. On my pc that's why I chose glitch.com.
Although I saw a previous user with the same issue and was asked.to contact glitch.com for their environment port which is "3000" as their support section said.
Even after changing the port it doesn't seem to work for me.

**Comment by idcw0tdisism8** [comment]
I have no idea on that issue then, @Dragory should.

**Comment by Dragory** [comment]
Unfortunately I have no experience hosting on glitch.com. Contacting their support is your best bet.
