### ISSUE TITLE
Schedule close isn't working. 

### ISSUE THREAD

**Issue by LookOutForMe** [Dragory/modmailbot#114]
Using `!close time` doesn't seem to work. The channel isn't autoclosing after the specific amount of time. Although the `!close` command works fine.

**Comment by idcw0tdisism8** [comment]
Have you tried using these?

s = seconds
m = minutes
h = hours

**Comment by Dragory** [comment]
Are there any errors when this happens? Does the bot still post "Closing as scheduled...", but the channel stays? If so, can you still run commands such as `!reply` in that channel afterwards?

**Comment by mattsilver1** [comment]
It does say "Closing as scheduled..." and we can still reply, and close it with ``!close`` afterwards. But it still doesn't close properly and the channel remains even after the time.

**Comment by Dragory** [comment]
Is there any output in the bot's console when this happens?

**Comment by mattsilver1** [comment]
Mine's been spamming this error for like the past 5 days now: 
![image](https://user-images.githubusercontent.com/40540813/43760343-bdaa5858-99ef-11e8-833c-3b6dd89ac58b.png)

**Comment by Dragory** [comment]
That'd probably be why, hmm... Are you using the `closeMessage` option?

**Comment by mattsilver1** [comment]
Yes.

**Comment by Dragory** [comment]
I pushed a new update. Can you see if you're still experiencing crashes with it?

**Comment by mattsilver1** [comment]
How can we update the bot to the latest version again?

**Comment by Dragory** [comment]
See this issue comment for update instructions:
https://github.com/Dragory/modmailbot/issues/90#issuecomment-411845784

I'll be adding more in-depth instructions to the README later.

**Comment by Dragory** [comment]
@LookOutForMe Are you still experiencing this issue?
