### ISSUE TITLE
inboxServerPermission format of permissions?

### ISSUE THREAD

**Issue by bulletproof08** [Dragory/modmailbot#117]
What's the format of permission I need to set here? I tried all "common used". The one I want to use is "manage messages" I tried: "MANAGE_MESSAGES", "manage messages", "managemessages" and so on.. I saw in the code that you compare this setting with the direct user permission but still couldn't find the right format. Help would be appreciated and I suggest a documentation update :)

**Comment by Dragory** [comment]
Good point about the documentation 😛 You can see a list of permission names at https://abal.moe/Eris/docs/reference (down at `Eris.Constants.Permissions`). In this case it should be `manageMessages`.

**Comment by bulletproof08** [comment]
This worked, thanks!
