### ISSUE TITLE
Changing IP-based logging to hostname

### ISSUE THREAD

**Issue by Blizzard098** [Dragory/modmailbot#118]
Greetings!

So I was just curious as to how I'd change the address for logs from xxx.xxx.xxx.xxx:0000 to something like logs.mywebsite.com

I only want to do this as I am running the bot on the same virtual machine as my website, which I don't really want people to have the IP to haha.

Thanks!
~ Blizzard

**Comment by Dragory** [comment]
Hey! You can change the hostname using the `url` config option. You'll need to keep the port in the url though, or set up a reverse proxy to forward the logs to e.g. a subdomain on port 80.
