### ISSUE TITLE
Issue with logs and attachments with bot hosted on heroku

### ISSUE THREAD

**Issue by reboxer** [Dragory/modmailbot#119]
every time someone send a file or i close a thread it shows a link with my ip to the image/file but it wont load, is there any way to change this to a free host service? google drive or something like that?

**Comment by reboxer** [comment]
@Dragory thank you for the reply
so i followed the steps in this thread #74 and made heroku run the bot and assign a random port but it still shows port 8890 in logs and attachments links, so i took a look at the code and found this in [/src/utils.js](https://github.com/Dragory/modmailbot/blob/master/src/utils.js)
> async function getSelfUrl(path = '') {
  if (config.url) {
    return `${config.url}/${path}`;
  } else {
    const port = config.port || 8890;
    const ip = await publicIp.v4();
    return `http://${ip}:${port}/${path}`;
  }
}
>
and i was wondering if there is any way i can change this so instead of using 8890 as port, make it get the random port assigned by heroku like it does with the url.
(sorry if im wrong in all this, i dont know how to code and barely understand all this)

**Comment by reboxer** [comment]
Not really sure, but what this article says, it might be
https://devcenter.heroku.com/articles/procfile#procfile-format

**Comment by Dragory** [comment]
Try renaming your `config.json` to `config.js`, and then changing the format from:
```
{
  "key": "value"
}
```

To this:
```
module.exports = {
  "key": "value"
};
```

And then add this:
```
module.exports = {
  "port": process.env.PORT,
  // Other config values here
};
```

**Comment by reboxer** [comment]
I renamed the config file to config.js and changed the format, everything works fine, i have started it multiple times and links port are changing to the one assigned by heroku, but when i open them i keep getting a connection time out error.
and if it help, i used the console to see if there were any files inside logs folder and it was empty
![7ec020b12223f6953da06325c9094aa4](https://user-images.githubusercontent.com/7484116/43993035-f96255d2-9d5d-11e8-9f9b-546f116ebd8a.png)

**Comment by reboxer** [comment]
@Dragory sorry to mention you,but its been a few days and i really need this to work :(

**Comment by Dragory** [comment]
The error seems to indicate the attachment file that was requested wasn't found. There's nothing in the bot that deletes old attachments, so this sounds like an issue with either missing permissions when saving the file (that should show up in the logs, but to be sure, verify that the bot user has write permissions to the `attachments/` folder) or something in Heroku causing the `attachments/` folder to be emptied.

**Comment by reboxer** [comment]
I searched a bit and heroku seems to block all ports and you can only open them by request and having an account for a company, fortunately i managed to host the bot on an amazon vps so this problem is solved since i can open any port.
and can you check this thread instead #129?
thank you.
