### ISSUE TITLE
Stuck on the 5th and 7th step! (Beginner help)

### ISSUE THREAD

**Issue by MissAerith** [Dragory/modmailbot#12]
Hi, I'm not very familiar with using node.js & do I need the GitHub Desktop application ? I'm unsure of what exact steps I need to take for "installing dependencies" or where to start. It would be much appreciative to know if there are specific commands to type to install it or certain applications you need to open in order to do these! Otherwise, I know the rest on how to add the bot to the server and such and how to find server IDs and bot token stuff. I've already completed the values in config.json.

**Comment by mroWEloh** [comment]
Well you should just be able to go into a terminal and run `npm install` in the bot's file if you have node and npm installed.

**Comment by LegitEzra** [comment]
change directory to the modmail bot root and run npm install
