### ISSUE TITLE
Bot dmed discord member who just joined "null".

### ISSUE THREAD

**Issue by idcw0tdisism8** [Dragory/modmailbot#120]
![image](https://user-images.githubusercontent.com/35388464/43985588-0a5ac38c-9cce-11e8-8330-f229764276c7.png)
UMM @Dragory

**Comment by Dragory** [comment]
What is your `greetingMessage` config option set to?

**Comment by idcw0tdisism8** [comment]
![image](https://user-images.githubusercontent.com/35388464/44310126-b7456380-a396-11e8-9cbc-f4d60f054903.png)

**Comment by Dragory** [comment]
Change these options to `false` and `null` instead of `"false"` and `"null"` respectively.

**Comment by idcw0tdisism8** [comment]
Thanks.
