### ISSUE TITLE
Crash with Events.JS Error

### ISSUE THREAD

**Issue by wc3717** [Dragory/modmailbot#121]
I get this error a few hour after the bot starts https://going-g.host/bXy3KKJ65H.png

**Comment by maxrumsey** [comment]
Appears to be an error on your side. Do you self-host your bot or host it on a VPS / Heroku / AWS?

https://stackoverflow.com/questions/17245881/node-js-econnreset

> ECONNRESET (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the http and net modules.
- https://nodejs.org/api/errors.html

**Comment by Dragory** [comment]
This error can appear even when the bot is hosted on a VPS. It seems to be a mostly random (and harmless) network error, so I'm planning on adding an error handler that ignores the ECONNRESET errors unless there are a bunch of them in a short span of time. Please follow issue #104 for updates on this.
