### ISSUE TITLE
auto-close when can't dm

### ISSUE THREAD

**Issue by untuned** [Dragory/modmailbot#122]
When the bot can no longer DM someone due to them not being on the server, it should automatically close (with an option to toggle it maybe)

`Error while replying to user: DiscordRESTError [50007]: Cannot send messages to this user`

**Comment by Dragory** [comment]
For the most part, the bot already did this. However, there was a bug with the `closeMessage` option where the bot would crash if it couldn't DM the close message to the user. Are you still experiencing this with the latest version of the bot (v2.16.0 at the time of writing)?
