### ISSUE TITLE
Problem with logs

### ISSUE THREAD

**Issue by lukaa032** [Dragory/modmailbot#125]
I am interesting about logs i am new but when i start on 8890 port they won't load my page did i need to set up something i open port to 8890 in my router page. I set up to port 80 but that didn't work. Did i need to host same page and web hosting to pay to i have this feature or i can do about myself?

**Comment by Dragory** [comment]
You don't need to pay for web hosting to have the logs work. Opening the port should be enough, but that depends on your specific network setup - there could be another firewall further up the chain somewhere blocking the port.

**Comment by lukaa032** [comment]
So what happen if i set up on port 80 but still don't open?

**Comment by JGriffin34432** [comment]
@Dragory Can you make it to where like it would save to a website like Pastebin for example using an api key?
