### ISSUE TITLE
Newlines in greeting message

### ISSUE THREAD

**Issue by reboxer** [Dragory/modmailbot#129]
How can we make the greeting message have multiple lines of text (newlines or shift + enter) like in the /r/overwatch discord server?

**Comment by Dragory** [comment]
You can enter newlines in the greeting message config value (it's parsed as JSON5, which accepts them). Alternatively, you can put `\n`s as newlines there manually.

**Comment by reboxer** [comment]
Thank you, used `\n` and it worked.
