### ISSUE TITLE
index.js provides no output

### ISSUE THREAD

**Issue by mroWEloh** [Dragory/modmailbot#13]
I set up the bot on a remote linux server and typed `npm install`, but it gives me the error:

`npm WARN modmailbot@1.0.0 No repository field.`

Also when trying to run the bot I get no output in the terminal and it does not start up.

Any help @Dragory?

**Comment by Dragory** [comment]
That is just a warning, not an error. You can safely ignore it. Not sure about not getting any output - have you filled everything in config.json? Also, if possible, try with Node 8.

**Comment by mroWEloh** [comment]
I installed Node 8 and made sure everything in `config.json` was filled out. Still no success?
[![Screenshot from Gyazo](https://gyazo.com/83698c474bf08e050b98e10252c0c7aa/raw)](https://gyazo.com/83698c474bf08e050b98e10252c0c7aa)
[![Screenshot from Gyazo](https://gyazo.com/d1271b55331a89070bb757ed4300a29b/raw)](https://gyazo.com/d1271b55331a89070bb757ed4300a29b)

**Comment by Dragory** [comment]
The value for `token` doesn't seem right - tokens are longer and should contain both letters and numbers.

You can get your bot's token by clicking on the app with the bot user in https://discordapp.com/developers/applications/me and then clicking on ["click to reveal" next to "Token:"](http://i.imgur.com/PRnm3Yj.png).
