### ISSUE TITLE
Connecting issues & commands

### ISSUE THREAD

**Issue by HectorDiscord** [Dragory/modmailbot#135]
Hello, the modmail doesn't do any commands and he isn't connected in my server more than about 20 minutes. When he is connected, he can just receive messages, but we can't respond to it. But we can see the bot typing.

**Comment by Dragory** [comment]
Are there any errors in the console?

**Comment by HectorDiscord** [comment]
Not for the commands, I'm waiting the next time the bot will be down but I think there will be nothing

**Comment by HectorDiscord** [comment]
But this time the bot didn't disconnect since 45 minutes

**Comment by HectorDiscord** [comment]
It seems it wont be disconnected, but the commands don't work and we can't respond to the people who dm the bot

**Comment by HectorDiscord** [comment]
hum, the bot is disconnected. Seems that he is down when i disconnect.

**Comment by HectorDiscord** [comment]
ok, i fixed the offline issue, but the bot still doens't respond to any command and mods can't respond to members @Dragory

**Comment by HectorDiscord** [comment]
can anyone help ?
