### ISSUE TITLE
Bot spits out a very long message then crashes.

### ISSUE THREAD

**Issue by OmarWazzan** [Dragory/modmailbot#137]
```
       _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 588,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: [Object],
        _httpMessage: [Circular],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 145922,
        _destroyed: false,
        _called: true,
        [Symbol(asyncId)]: 1766,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 1772,
        [Symbol(triggerAsyncId)]: 1769 },
     _header: 'POST /api/v7/channels/484543822123237376/messages HTTP/1.1\r\nUser-Agent: DiscordBot (https://github.com/abalabahaha/eris, 0.8.4)\r\nAccept-Encoding: gzip,deflate\r\nAuthorization: Bot `[token]\r\nContent-Type:` application/json\r\nHost: discordapp.com\r\nConnection: close\r\nContent-Length: 252\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/api/v7/channels/484543822123237376/messages',
     _ended: false,
     res: null,
     aborted: 1535594665836,
     timeoutCb: [Function: emitTimeout],
     upgradeOrConnect: false,
     parser:
      HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
        _headers: [],
        _url: '',
        _consumed: false,
        socket: [Object],
        incoming: null,
        outgoing: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncomingClient] },
     maxHeadersCount: null,
     [Symbol(outHeadersKey)]:
      { 'user-agent': [Array],
        'accept-encoding': [Array],
        authorization: [Array],
        'content-type': [Array],
        host: [Array] } } }

```

This started happening today, whenever a message is sent or command used.

**Comment by Dragory** [comment]
Whenever *any* message is sent or command is used? This sort of connection errors are usually due to e.g. the connection closing unexpectedly, but if it happens all the time, something's definitely wrong. Are you hosting any other bots on the same machine, and if so, are those working fine?

**Comment by OmarWazzan** [comment]
When threads open, they don't open correctly. (https://gtaodiscord.com/o/90ea8f.png and https://gtaodiscord.com/o/48d3bd.png)

When we send messages through modmail, bot either crashes and spits that out, or gives out an error. Error while replying to user: Request timed out (>15000ms) on POST /channels/483409590994731030/messages

There are other bots running on the server, but they're unaffected. (and another one running on the same token is doing fine too)

**Comment by Dragory** [comment]
Timeouts would definitely point to a network issue of some sort. Does it work if you stop the other bot that's using the same token, and then restart modmail?

**Comment by OmarWazzan** [comment]
Still does the same issue.

sometimes I'm also getting: Error while replying to user: DiscordHTTPError: 500 INTERNAL SERVER ERROR on POST /api/v7/channels/485476401739202580/messages

**Comment by OmarWazzan** [comment]
There's also this one that just popped up: 0|npm      |
0|npm      | Error: closed before the connection is established
0|npm      |     at WebSocket.close (/root/modmail/node_modules/ws/lib/WebSocket.js:271:21)
0|npm      |     at Shard.disconnect (/root/modmail/node_modules/eris/lib/gateway/Shard.js:104:25)
0|npm      |     at Timeout.setTimeout [as _onTimeout] (/root/modmail/node_modules/eris/lib/gateway/Shard.js:1647:22)
0|npm      |     at ontimeout (timers.js:498:11)
0|npm      |     at tryOnTimeout (timers.js:323:5)
0|npm      |     at Timer.listOnTimeout (timers.js:290:5)
0|npm      | events.js:183
0|npm      |       throw er; // Unhandled 'error' event
0|npm      |       ^
0|npm      |
0|npm      | Error: read ECONNRESET
0|npm      |     at _errnoException (util.js:992:11)
0|npm      |     at TLSWrap.onread (net.js:618:25)

**Comment by Dragory** [comment]
ECONNRESET is a connection error that seems to pop up randomly. I'll be pushing a fix (or workaround, rather) for that sometime in the near future. See issue #88 for updates!
