### ISSUE TITLE
Commands don't work &  mods can't send messages

### ISSUE THREAD

**Issue by HectorDiscord** [Dragory/modmailbot#139]
Hello ! Here is my issues : 
- my modmail commands don't work at all. 
- The modmail can receive message and create threads but my moderators can't send any message to the people who is talking...

**Comment by Dragory** [comment]
If you're using `inboxServerPermission`, make sure it's set correctly ([you can find the values to use here](https://abal.moe/Eris/docs/reference), under `Eris.Constants.Permissions`) and that your moderators have those permissions.

**Comment by Dragory** [comment]
Instead of `"8192"`, try changing `inboxServerPermission` to `"manageMessages"`

**Comment by HectorDiscord** [comment]
doesn't work, but note that i can see the bot typing

**Comment by Dragory** [comment]
Make sure your mods have the "Manage Messages" permission too. Then it should work with `inboxServerPermission` set to `"manageMessages"`.

**Comment by HectorDiscord** [comment]
it works ! 🎉 
Thank you very much for your help !

**Comment by HectorDiscord** [comment]
oh... Now the bot send the message 2 times when the mod send a message, when he received a message and when he does any command @Dragory
