### ISSUE TITLE
Error No File

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Dragory/modmailbot#14]
![image](https://user-images.githubusercontent.com/18231531/28841687-e6dae52e-76f2-11e7-9976-e76755e2ed89.png)

I did all the steps

**Comment by Dragory** [comment]
The error implies that the folder doesn't have a `package.json` file. This is included in the bot's files, so you're currently missing some of its files. Try redownloading, and make sure you're running the command in the directory where the bot's files are located.
