### ISSUE TITLE
Bot using heavy resources

### ISSUE THREAD

**Issue by SpeedBird95** [Dragory/modmailbot#141]
Hi , 

I have the bot running with pm2 and went into src and used pm2 with index.js.
PM2 is showing the bot using 67MB of memory. This seems extensive.
Is there a problem or is this normal behavior ?

│[ 1] index           Mem:  68 MB    CPU:  0 %  online ││                                                                                                                                  │

**Comment by Dragory** [comment]
This is pretty normal from what I've seen. It also depends on the size of your main server (larger servers will have more members cached).

**Comment by SpeedBird95** [comment]
Ok , on another note , the server keeps crashing perodically with the following: 
Any idea how I can trouble shoot?

 index > Error: read ECONNRESET                                                                                                   │
│                                                      ││ index >     at _errnoException (util.js:992:11)                                                                                  │
│                                                      ││ index >     at TLSWrap.onread (net.js:618:25)

**Comment by Dragory** [comment]
Known issue. Follow issue #88 for updates on that!
