### ISSUE TITLE
Auto-reply to bot pings

### ISSUE THREAD

**Issue by JustxMeg** [Dragory/modmailbot#143]

**Comment by JustxMeg** [comment]
Hey,

Yes, but that does it in the contact logs and I want in the channel where the bot has been pinged with a custom text.

**Comment by Dragory** [comment]
Oh right, like an auto-response to the ping? I could look into adding something like that in the future.

**Comment by JustxMeg** [comment]
Yeah, we really need it in our server.

**Comment by Dragory** [comment]
Added in v2.17.0 as `botMentionResponse` option

**Comment by JustxMeg** [comment]
Updated the bot, but somehow it doesn't work?

**Comment by Dragory** [comment]
What did you set as `botMentionResponse`? Note that the same conditions apply as for `pingOnBotMention`, i.e. the bot won't respond to pings by staff members.

**Comment by JustxMeg** [comment]
```Als je contact zoekt met de staff van de server, kun je mij een privébericht sturen.```

Users tried it, but it didn't work.

**Comment by Dragory** [comment]
Not sure what's up with it then. Here's my test setup where it works:

![image](https://user-images.githubusercontent.com/2606411/45901507-cf702e80-bdeb-11e8-865f-fb6a2e1c041f.png)

![image](https://user-images.githubusercontent.com/2606411/45901492-bcf5f500-bdeb-11e8-92b0-b672a03303da.png)

**Comment by JustxMeg** [comment]
`{
  "token": "",
  "mailGuildId": "458910463070044161",
  "mainGuildId": "458910463070044161",
  "logChannelId": "462666043941191680",
  "prefix": "/",
  "newThreadCategoryId": "462661219824697426",
  "snippetPrefix": "/",
  "typingProxy": "true",
  "typingProxyReverse": "true",
  "allowMove": "true",
  "useNicknames": "true",
  "mentionRole": "478641941190410260",
  "pingOnBotMention": "true",
  "botMentionResponse": "Als je contact zoekt met de staff van de server, kun je mij een privébericht sturen.",
  "closeMessage": "Bedankt dat je contact met ons hebt opgenomen! Deze case is nu gesloten, wanneer je opnieuw vragen hebt kun je mij nogmaals een privébericht sturen. \n \n_Alle gesloten cases worden bewaard op de server zodat wij deze in de toekomst erbij kunnen halen indien je opnieuw contact met ons zoekt. Zien we je in de <#461491805091790848>?_",

  "status": "Server hulp nodig? DM mij!",
  "responseMessage": "Bedankt voor je bericht, wij zullen je zo snel mogelijk voorzien van een reactie."
}`

This is my config.

**Comment by Dragory** [comment]
Oh right, so it's a same server setup. In a same server setup (or, well, any setup, but it's more apparent in same server setups) if you don't have any value set to `inboxServerPermission`, all users will be considered "staff" for the purposes of the bot. This means that their pings won't get logged in logChannel, nor will they get a `botMentionResponse` response.

The solution is to set `inboxServerPermission` either to one of the text values under "Eris.Constants.Permissions" at https://abal.moe/Eris/docs/reference (e.g. `"manageMessages"`) or to a role id that the staff have.

**Comment by JustxMeg** [comment]
Wait.. I don't understand this. :(

**Comment by Dragory** [comment]
All you need to do is set `inboxServerPermission` to e.g. `"managePermissions"` - a permission only your staff have.

**Comment by JustxMeg** [comment]
Ah, ManageMessages for example?

**Comment by Dragory** [comment]
Yeah, manageMessages, not managePermissions like I mistakenly wrote above.
