### ISSUE TITLE
AnonymReply not working for Snippets

### ISSUE THREAD

**Issue by NicoRazor** [Dragory/modmailbot#145]
when i set the anonymreply to true, it works perfectly but if i use a snippet to answer it still doesnt show as anonym (it sends: (Support) <supporters name> is there any way to make it also show as anonymous with snippet using? would be great

**Comment by HectorDiscord** [comment]
I have the same problem

**Comment by Dragory** [comment]
Known issue. Follow issue #82 for updates!
