### ISSUE TITLE
How to make bot work with Xampp

### ISSUE THREAD

**Issue by Huskydog9988** [Dragory/modmailbot#149]
Is there anyway I could have the bot work with xampp and both be outputting to the same website?

**Comment by Dragory** [comment]
You'd probably need to set up a reverse proxy in Apache that routes traffic from your website to the bot's port (8890). [This website](http://gyanmoti.in/2016/07/reverse-proxy-config-in-apache-xampp/) seems to have an example config you can use (replace `192.168.1.5:3689` with `127.0.0.1:8890` where 8890 is the bot's port - 8890 is the default).

**Comment by Huskydog9988** [comment]
Its working right now as far as I can tell. Thank you
