### ISSUE TITLE
Staff can't use commands

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Dragory/modmailbot#15]
I've created a server that looks like this 

![image](https://user-images.githubusercontent.com/18231531/28843171-1e27c9f2-76f8-11e7-8365-bcc318789046.png)

But my staff can't use any of the bot commands however, I can as the bot owner? Is there a certain role name I am supposed to use

**Comment by aequasi** [comment]
Bump, same issue.

**Comment by aequasi** [comment]
manageRoles apparently

**Comment by Dragory** [comment]
Hey! Yeah, sorry, at the moment the `Manage Roles` permission is required to use modmail commands. I will remove this requirement (and make it a setting instead) soon.

**Comment by Dragory** [comment]
I've released a new update which makes it so no perms are required by default. This can be configured with the `inboxServerPermission` config option. You can update the bot by redownloading the files (or using git).
