### ISSUE TITLE
Heroku Environment Variable

### ISSUE THREAD

**Issue by AXVin** [Dragory/modmailbot#151]
Hey, i am trying to use heroku. Can i know where i can set the environment variable for the token. Really don't want to leave it on a public config.json file so that anyone can see it.
I tried to put it in config.js file as default but it doesn't seem to work. Will appreciate the help!

**Comment by AXVin** [comment]
And also will i be able to access the logs?
I have overheard that the users using heroku to host modmailbot can't use it's logging feature. Correct me please if i am wrong.

**Comment by Huskydog9988** [comment]
First use the settings tab and there is an option to input variables, put the token there. (requires coding to work). And second i believe you can because heroku allows you to "open" your app you just have to push to that specific web server. Also these are general ideas I slapped together from my experience with heroku. I hopefully will update you if i figure this out as i want to do this as well .

**Comment by AXVin** [comment]
@Huskydog9988 A little late bud. I already figured out how to do that.
I had to put `process.env.VARIABLE_NAME` in config.js file. I was doing the same earlier too but then i was putting the token in a string on the dashboard (which wasn't needed because heroku converts it that way iirc). Now the things are working snoothly. You can see the changes [here](https://github.com/better-discord-mobile/modmailbot)! Thanks anyways

**Comment by AXVin** [comment]
But the main problem with using free dynos is that the changes are kept and slug and are reset every 24 hrs. That means all the set snippets and the logs get a reset.
Moreover i am still not able to get the link from logs to work. Might be something related to heroku which isn't allowing to access those files. If you could help me with that? Please

**Comment by reboxer** [comment]
> But the main problem with using free dynos is that the changes are kept and slug and are reset every 24 hrs. That means all the set snippets and the logs get a reset.
> Moreover i am still not able to get the link from logs to work. Might be something related to heroku which isn't allowing to access those files. If you could help me with that? Please

You can't access logs or attachments on heroku because they have all ports closed and you can't open them (and 8890, the one the bot uses by default is not opened).
I've already used heroku and is not good, i'd recommend moving to one of amazon's free tier vpn.

**Comment by Huskydog9988** [comment]
Think i found a way to push the site https://blog.teamtreehouse.com/deploy-static-site-heroku. Haven't tried but it should work. Btw using this repository - https://github.com/better-discord-mobile/modmailbot. If there is a more updated one i would like to know.

**Comment by Huskydog9988** [comment]
Scraped the tutorial for now. I recommend using glitch.com

**Comment by AXVin** [comment]
@Huskydog9988 I am still not sure why you linked a tutorial to host a static site though.
I tried to make everything in the config.js file as an environment variable so that it becomes easier for others to set their defaults directly from dashboard. But that doesn't work as the bot looks for the channel id and stuff everytime it has to do things instead of looking it on bot start(not saying it is bad)!
Also what to use glitch.com for?

**Comment by Huskydog9988** [comment]
glitch.com can be used to host your code. Im working with some friends to figure what needs to be changed rn in order for it to work on the website, as you can host the logs and stuff with glitch too.

**Comment by HectorDiscord** [comment]
Hm @Huskydog9988 can you send me the link of your glitch code please ?

**Comment by Huskydog9988** [comment]
Sorry can’t as it is broken and I didn’t use the .env file

**Comment by miramallows** [comment]
Personally don't suggest heroku for sqlite bots, but go ahead. config vars should do the trick.

**Comment by Huskydog9988** [comment]
The logs won’t save which is the only problem with using heroku.
