### ISSUE TITLE
Opening Log Links would lead to "This site can’t be reached"

### ISSUE THREAD

**Issue by MeladTheBad** [Dragory/modmailbot#156]
Hello, I have set the port to 8890
and for example I want to open this log
http://160.3.189.227:8890/logs/c556e06e-dfa4-4cd4-9c10-812fbbc1f54d
it says "This site can’t be reached
160.3.189.227 took too long to respond.
Search Google for 160 189 227 8890 logs c556e06e dfa4 4cd4 9c10 812fbbc1f54d
ERR_CONNECTION_TIMED_OUT"

Anyway to make it work ?
![error](https://user-images.githubusercontent.com/42744111/45910768-07439a00-be1d-11e8-9e68-bb8d161d9274.png)

**Comment by Dragory** [comment]
Make sure you've forwarded your ports so the port 8890 is accessible from the internet.

**Comment by MeladTheBad** [comment]
I have two bots running and they both have port 8890, however when both instances are running only one can open log links, the other shows this on console upon start up "[WARN] Web server error: listen EADDRINUSE :::8890"
are there any ports I can forward that works on the bot aside from 8890 ?

**Comment by MeladTheBad** [comment]
I got it to work now, thank you :D
