### ISSUE TITLE
how to delete thread from database?

### ISSUE THREAD

**Issue by thetayloredman** [Dragory/modmailbot#157]
one thread was manually deleted and whenever the user messages us there is already a #DELETED-CHANNEL

**Comment by Dragory** [comment]
Not sure what you mean by #deleted-channel. The bot would automatically close the thread in the background if its channel is deleted and make a new channel next time the user messages the bot.

However, you can use any sqlite database utility to view and edit the database. You should then be able to just delete the thread from the threads table.
