### ISSUE TITLE
Some questions about the updates

### ISSUE THREAD

**Issue by JustxMeg** [Dragory/modmailbot#159]
Hey,

In #69 people can close threads via DM, so if we have the prefix "/", people need to say "/close" in DM with the bot?
There is a option to have snippets anonymous now (#145), but do we have to re-add all the snippets or is there a quicker way?

**Comment by Dragory** [comment]
1. Yes, users will have to use the same prefix for `/close` your mods are using.
2. Snippets aren't inherently anonymous or public, but they can be *sent as* anonymous or public. By default, `!!shortcut` sends the snippet with your name and `!!!shortcut` sends it anonymously. The two settings that control these are `snippetPrefix` and `snippetPrefixAnon`.

**Comment by JustxMeg** [comment]
Thanks. Works perfectly.
