### ISSUE TITLE
"Member xxxxxxx not found in guild xxxxxxxx"

### ISSUE THREAD

**Issue by Sen10el** [Dragory/modmailbot#16]
Hi. The bot has been working great lately. But I just have a couple problems right now. First is when people PM the bot, it will make the thread successfully, but it will say they are not part of the server. Ex. ![image](https://user-images.githubusercontent.com/29514266/28936560-168e6976-7856-11e7-8e98-151f9969cece.png)
In the ode it says the line "Member xxxxxxxxxxxxxxxxx not found in main guild xxxxxxxxxxxxxxx" when they absolutely are. In both the mailbox server and the main guild server the bot has admin permissions.

Also side problem, I can't PM the bot without it throwing an error but other people are able to. When I try to message the bot, the error it throws is the following: (node:9332) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: 403 FORBIDDEN on POST /channels/xxxxxxxxxxxxx/messages
{"code": 50001, "message": "Missing Access"}

**Comment by Dragory** [comment]
The first issue is being discussed in #5 - a fix is coming soon!

As to the second one: you probably have DMs from non-friends blocked. Make sure "Allow direct messages from server members" is checked in both your user settings (under Privacy & Safety) and on the main server (click server name -> Privacy Settings).

**Comment by Sen10el** [comment]
Both settings are allowed, both in my settings and in the server settings specifically. Still strange, I'll see if there are any other options that I have that could be the cause of this issue. 

And also awesome, can't wait, not super problematic but it'll be nice to have :)

**Comment by Dragory** [comment]
I've released a new update which should fix the first issue. You can update the bot by redownloading the files (or using git).

**Comment by Sen10el** [comment]
Downloaded new version, currently giving error, I've attached the debug log. It says that the problem ends up being the node src/index.js. when downloading I tried both replacing the old files and creating a new folder and both are giving the same error.
[npm-debug.txt](https://github.com/Dragory/modmailbot/files/1198318/npm-debug.txt)

**Comment by Dragory** [comment]
Try removing the `node_modules` folder, and then running `npm install` again, and see if that fixes it.

**Comment by Sen10el** [comment]
That didn't end up working, I tried both the new and old folders, still to no avail.

**Comment by Dragory** [comment]
Then I would suggest:

1. Download the new version to a completely new folder
2. Copy `config.json` and the `db` folder from the old folder
3. Run `npm install` in the new folder
4. Run the bot in the new folder: `npm start`

If that works, you can delete the old folder.

**Comment by Dragory** [comment]
Sorry, I misread, you already tried a new folder. I looked through the log again and see you're running Node.js 6. Try installing Node.js 8 and then try again (restart cmd, remove node_modules, run npm install, run npm start).

**Comment by Sen10el** [comment]
I hate that I feel like I'm bugging you whenever I run into a problem just because I can't figure them out on my own :( But after I installed node.js 8 and restarted my computer the bot was able to turn on and no errors were produced during startup, but when I went to PM it from my alt account, I was met with this error: `(node:6280)` UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 404 NOT FOUND on POST /channels/330709239754653718/messages

{"code": 10003, "message": "Unknown Channel"}
(node:6280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Dragory** [comment]
This error can occur if one of the threads on the inbox server was deleted manually (i.e. instead of using !close). Not sure if that's what happened, but try deleting the `db/threads.json` file.

**Comment by Sen10el** [comment]
So now it is consistent in how it works overall but it still is a little buggy. I'm still getting that error above when the bot is PM'd from a new user. The problem is that right now, I would have to PM the bot twice and only the second message would relay in the inbox server, which can be really annoying.

The only part of the error message that has changed since deleting the threads.json file is the rejection id, where now it says: `(node:9944) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ReferenceError: restBot is not defined`

So this is after the first message, which will create the new thread, but that first message won't be relayed into the thread but every other one after will. Again, tested this on both the existing and a new download and showing the same error.

Thank you for all of your help. You've made an amazing application, I'm just being really particular.

**Comment by Dragory** [comment]
Are you sure you have the newest files? There are no references to "restBot" in the code anymore. I released a couple hotfixes after the initial big update, and this was fixed in one of them - you probably got your files right in the 5min the buggy version was up! 😛

**Comment by Sen10el** [comment]
Did a completely fresh download, copied over only the config file, ran npm install, restarted cmd, ran npm start. Everything works.

Thank you a ton for your help, patience and work on this project :)

**Comment by Dragory** [comment]
Great, and thanks! Feel free to open another issue if you have any problems in the future. Don't worry about "bugging me", that's what the issue tracker is here for!
