### ISSUE TITLE
[DragoryModBot] modmail inbox error??

### ISSUE THREAD

**Issue by LegendHunter** [Dragory/modmailbot#160]
How do I use the config options for dragory?

**Comment by LegendHunter** [comment]
Never mind I fixed it by changing id for mailGuildID to 484775284864974851

**Comment by LegendHunter** [comment]
But now I have this
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!
[WARN] The bot hasn't joined the main guild!

**Comment by Dragory** [comment]
There is a syntax error somewhere in your config. You can post it here if you want, but remove your token from it first!

**Comment by LegendHunter** [comment]
{
  "token": "",
  "mailGuildId": "484775284864974851",
  "mainGuildId": "484775284864974851",
  "logChannelId": "490905378708652032",
  "newThreadCategoryId": "493187893527969832",|
  "alwaysreply": "true",

  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
}

**Comment by LegendHunter** [comment]
> There is a syntax error somewhere in your config. You can post it here if you want, but remove your token from it first!

{
"token": "",
"mailGuildId": "484775284864974851",
"mainGuildId": "484775284864974851",
"logChannelId": "490905378708652032",
"newThreadCategoryId": "493187893527969832",|
"alwaysreply": "true",

"status": "Message me for help!",
"responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
}

PS C:\Users\Casey\Desktop\modmailbot-master> npm start
C:\Users\Casey\Desktop\modmailbot-master\src\config.js:39
throw new Error(Error reading config file! The error given was: ${e.message});
^

Error: Error reading config file! The error given was: JSON5: invalid character '"' at 9:3
at Object. (C:\Users\Casey\Desktop\modmailbot-master\src\config.js:39:9)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object. (C:\Users\Casey\Desktop\modmailbot-master\src\index.js:32:16)
at Module._compile (module.js:653:30)
PS C:\Users\Casey\Desktop\modmailbot-master>

**Comment by LegendHunter** [comment]
Hello?

**Comment by Dragory** [comment]
Logs cannot be deleted at this time without going into the database manually.

**Comment by LegendHunter** [comment]
> Logs cannot be deleted at this time without going into the database manually.

How do I make one?

**Comment by Dragory** [comment]
Make what? Going into the database manually would require using some sqlite database tool, such as SQLiteStudio, and opening `db/data.sqlite` with it. Note that editing the database manually is not officially supported, and you'll be doing it at your own risk.
