### ISSUE TITLE
Channel creation permissions

### ISSUE THREAD

**Issue by CaliLifeStyle** [Dragory/modmailbot#161]
Hello, I was reading through some problems and didn't find a solution for this one:
Based on default settings, when someone messages the bot, a new channel is opened and everyone in the server can see it and reply to it.  Is there something I need to configure to fix this?  I looked at the commands, but didn't see anything that indicated how to prevent people from seeing/replying to a message.  Here are my parameters in the config file:

{
  "token": "",
  "mailGuildId": "493140792722980914",
  "mainGuildId": "493140792722980914",
  "logChannelId": "493141293900234792",

  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
}

Thanks for your time!

**Comment by maidos** [comment]
you want this on your config.json newThreadCategoryId
create a new category and adjust itso only moderators can see it and @everyone cant read message. after that when someone dm the bot will create channel with permission synced under the category

**Comment by CaliLifeStyle** [comment]
Thanks! I’ll let you know how it goes.

**Comment by CaliLifeStyle** [comment]
Is this how it should look?

"token": "",
  "mailGuildId": "493140792722980914",
  "mainGuildId": "493140792722980914",
  "logChannelId": "493265572293902336",
  "newThreadCategoryId"

  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."

**Comment by maidos** [comment]
you need to add the category ID too. its missing value otherwise it doesnt know where to add the channels

**Comment by CaliLifeStyle** [comment]
It worked! thank you! For anyone else that might need this, here is how it looks: 

{
  "token": "",
  "mailGuildId": "493140792722980914",
  "mainGuildId": "493140792722980914",
  "logChannelId": "493265572293902336",
  "newThreadCategoryId": "493265431608557571",

  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
}
