### ISSUE TITLE
 [WARN] The bot hasn't joined one or more main guilds!

### ISSUE THREAD

**Issue by maidos** [Dragory/modmailbot#162]
this is a bug that only occur when i change the role name that bot creates when i invite tothe server.
or if i leave the role name intact and add addtional role it will start giving me this warning.

warning removes once i revert everything to vanilla

**Comment by Dragory** [comment]
Can you show me your config? Remove the token.

**Comment by maidos** [comment]
"token": "",
  "mailGuildId": "286881842789875713",
  "mainGuildId": "447368370996641792",
  "logChannelId": "415903367471169558",
  "prefix": "!",
  "closeMessage": "The ticket is now closed. If you have anymore questions simply reply again to create a new ticket.",
  "greetingMessage": "Thanks for contacting us. Please be patient while one of our moderator get notified by our bot.",
  "newThreadCategoryId": "492006038556639248",
  "requiredAccountAge": "12",
  "port": "8080",
  "url": "IP:PORT",
  "relaySmallAttachmentsAsAttachments": "true",
  "status": "I relay your messages to all moderators!!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
}

Aside from the warnings, the mod works as intended. i can dm bot and bot creating channels and delete it when issue close command

**Comment by Dragory** [comment]
And you're sure the bot is present in the main guild, i.e. guild with the id `447368370996641792`?

**Comment by Dragory** [comment]
Have you restarted the bot after inviting it?
