### ISSUE TITLE
PORT FOR LOGS

### ISSUE THREAD

**Issue by XxRazorxX** [Dragory/modmailbot#168]
what port do i have to set in order to make logs work? currently it just says website unreachable or something like that? nice bot by the way ;)

**Comment by Girtablulu** [comment]
port 8890 as mentioned inside the configuration option

**Comment by XxRazorxX** [comment]
Doesnt work obviously @Girtablulu

**Comment by Girtablulu** [comment]
Have you set port forwarding?

**Comment by XxRazorxX** [comment]
How do i do that? :thinking: @Girtablulu

**Comment by Girtablulu** [comment]
Inside your router

**Comment by miramallows** [comment]
same question

**Comment by Dragory** [comment]
Port forwarding is outside the scope of these GitHub issues. Please look into e.g. https://portforward.com/ for details and guides on port forwarding.
