### ISSUE TITLE
modmailbot@1.0.0 start: `node src/index.js`

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Dragory/modmailbot#17]
modmailbot@1.0.0 start: `node src/index.js`
npm ERR! spawn ENOENT

npm ERR! Failed at the modmailbot@1.0.0 start script 'node src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the modmailbot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs modmailbot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls modmailbot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kyle/Desktop/modmailbot-master/modmailbot/npm-debug.log

**Comment by LegitEzra** [comment]
Did you do "npm install" in the root of the bot.

**Comment by Dragory** [comment]
If this was after an update, remove the `node_modules` folder and then run `npm install` again.

**Comment by matematrix** [comment]
Same goes for me, I ran `npm install`, and I also did what @Dragory said,
the error still persists.
I attached the log file, maybe that will help.
Thanks 👍 
[npm-debug.txt](https://github.com/Dragory/modmailbot/files/1237437/npm-debug.txt)

**Comment by Dragory** [comment]
Please update to Node.js 8 and try again.

**Comment by matematrix** [comment]
I just installed Node.js today. So I guess I have the newest version :)

**Comment by matematrix** [comment]
^ Nevermind, I don't have Version 8. On Windows it isn't working for me, but on linux it is however

**Comment by LegitEzra** [comment]
Ok
