### ISSUE TITLE
Issue with attachment in DM

### ISSUE THREAD

**Issue by Roxyhands1** [Dragory/modmailbot#170]
Hey, so I understand I need to port forward etc to get the log links and attachments in PM but the problem is I am hosting the bot on AWS, I am literally lost on how to get this to work? Is there any alternative to getting the logs elsewhere for example?

**Comment by Dragory** [comment]
Currently there is no alternative way for getting logs. You can follow issue #45 for updates on that.

Assuming you're using an EC2 instance with nodejs on it, check out this article:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by Roxyhands1** [comment]
> Assuming you're using an EC2 instance with nodejs on it, check out this article:
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

Tyvm, I got it to work thanks to you! <333
