### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by HectorDiscord** [Dragory/modmailbot#172]
Can anyone who uses Glitch to host the bot send me the link of his page please ? I tried to use it but it's so strange...

**Comment by ieuangol** [comment]
> Can anyone who uses Glitch to host the bot send me the link of his page please ? I tried to use it but it's so strange...

I can help you direct message me and I'll be happy to help you on [Discord](https://discord.com) my tag and username is **ieuan#2109**.

**Comment by ieuangol** [comment]
Please close this issue now, since it's been resolved.
