### ISSUE TITLE
systemd issue on new version

### ISSUE THREAD

**Issue by evacfk** [Dragory/modmailbot#176]
Hi,

Two questions.

1. I've used this for almost a year now I believe, works fine. No issues whatsoever.

What would be the best way to update? I read to delete and reinstall my node files, do I also need to completely re-clone the repo? As for backup, what folders need to be backed up besides attachments/logs and config.json.

2. I installed a second version of this onto another bot (this is how I found out there were updates), however my systemd file is not working. It's a clone of the first installation i had which works with no issues.

Here's what the systemd file looks like:

`
[Unit]
Description=ModMail2
After=multi-user.target
[Service]
WorkingDirectory=/home/evacbots/modmailbot2/modmailbot
User=evacbots
Group=evacbots
ExecStart=/usr/bin/node /home/evacbots/modmailbot2/modmailbot/src/index.js
Type=idle
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
`

**Comment by reboxer** [comment]
i'd recommend to use PM2 to keep the bot up, really easy to use and you can make it start on system boot and if the bot crashes, it will restart it

**Comment by evacfk** [comment]
I don’t want to use PM2. 

All my other bots run on systemd and achieve the same thing as what you mentioned.

**Comment by Girtablulu** [comment]
I can say how I do it

I cloned the repo onto my Pi, for updating I run: git pull --> npm install --> systemd service stop --> systemd service start and I run on the newest version

**Comment by Dragory** [comment]
Before updating, back up the `db/data.sqlite` file and `attachments` folder.

1. You should be able to update by just downloading the newest version from [the releases page](https://github.com/Dragory/modmailbot/releases) and extracting it over the old files. If prompted to replace or merge folders (depending on OS), choose merge.

2. Are there any errors or similar messages in the systemd logs?

**Comment by evacfk** [comment]
Thanks for the updating info, here's the error I have in my sysmd log.

Oct 12 10:07:28 evacbot systemd[1]: Started ModMail2.
Oct 12 10:07:29 evacbot node[3136]: Can't take lock to run migrations: update `knex_migrations_lock` set `is_locked` = 1 - SQLITE_READONLY: attempt to write a readonly database
Oct 12 10:07:29 evacbot node[3136]: If you are sure migrations are not running you can release the lock manually by deleting all the rows from migrations lock table: knex_migrations_lock
Oct 12 10:07:29 evacbot node[3136]: { [MigrationLocked: update `knex_migrations_lock` set `is_locked` = 1 - SQLITE_READONLY: attempt to write a readonly database]
Oct 12 10:07:29 evacbot node[3136]:   name: 'MigrationLocked',
Oct 12 10:07:29 evacbot node[3136]:   message: 'update `knex_migrations_lock` set `is_locked` = 1 - SQLITE_READONLY: attempt to write a readonly database' }
Oct 12 10:07:29 evacbot systemd[1]: modmail2.service: Main process exited, code=exited, status=1/FAILURE
Oct 12 10:07:29 evacbot systemd[1]: modmail2.service: Unit entered failed state.
Oct 12 10:07:29 evacbot systemd[1]: modmail2.service: Failed with result 'exit-code'.

**Comment by Dragory** [comment]
I apologize for no response here. If you're still running the bot and experiencing this problem, please open a new issue after trying with the newest version. That being said, I think it's a permission issue - when you're running `npm start`, you're probably running this on a user that has permissions to modify the database file. It could be that whatever user the systemd service is using doesn't have these permissions.
