### ISSUE TITLE
Logs and web server.

### ISSUE THREAD

**Issue by coltoutram** [Dragory/modmailbot#179]
I have an openlitespeed web server on the same VPS that I'm hosting the bot on, is there a way to host the logs using openlitespeed? Is it possible to change the location of where the logs save?

**Comment by Dragory** [comment]
It is currnetly not possible to configure where the logs are saved. However, you should be able to create a virtual host in OpenLiteSpeed that points to the log directory. Alternatively, if the software supports it, you could set up a reverse proxy from OpenLiteSpeed to the bot's port (default 8890).

**Comment by LegendHunter** [comment]
> It is currently not possible to configure where the logs are saved. However, you should be able to create a virtual host in OpenLiteSpeed that points to the log directory. Alternatively, if the software supports it, you could set up a reverse proxy from OpenLiteSpeed to the bot's port (default 8890).

Dragory do you have discord I need to reac you quicker.

**Comment by coltoutram** [comment]
tbh where does it even save the logs? theres a folder "logs" but nothing gets saved in there?

**Comment by Dragory** [comment]
Logs are saved in the database (i.e. the `db/data.sqlite` file). More accurately, threads and their messages are saved in the database regardless of if the thread is closed - they're just called logs when you view them through the log link. This is also why alternative log locations are not currently supported: they would need to be saved externally after the thread is closed (in addition to having them in the database), and commands such as `!loglink` wouldn't be able to get the log's link before the thread is closed. This is on the TODO, but currently low priority. One temporary solution would be a command that has the bot send these logs as attachments through Discord.
