### ISSUE TITLE
bot.on('messageCreate', async msg => {

### ISSUE THREAD

**Issue by QuinnTDIP** [Dragory/modmailbot#18]
![screen shot 2017-08-04 at 11 33 55 am](https://user-images.githubusercontent.com/25911649/28977727-e09fc928-7908-11e7-949d-e8bb53b6472b.png)

**Comment by Dragory** [comment]
Hey, please update Node.js to version 8 or above and try again.

**Comment by LegitEzra** [comment]
Is the bot already running in a different terminal?

**Comment by QuinnTDIP** [comment]
@LegitEzra no @Dragory I did, I think it fixed
