### ISSUE TITLE
The new update update appears to have broken the entire bot

### ISSUE THREAD

**Issue by Huskydog9988** [Dragory/modmailbot#184]
![image](https://user-images.githubusercontent.com/39809509/47457852-38a9df80-d7a6-11e8-8852-cc608de43bf9.png)
(Don't know if you need that table missing error or not) As the title says as far as I can tell something is wrong with the bots code on dming people. Maybe it is out of date, idk.

**Comment by Huskydog9988** [comment]
Renamed as the bot dose not register !reply and etc. (same error code btw)

**Comment by Dragory** [comment]
Is this a fresh installation, or did you upgrade?

**Comment by Huskydog9988** [comment]
![image](https://user-images.githubusercontent.com/39809509/47508114-7ad42f00-d841-11e8-92bb-d20d736e53ad.png)
those are the current settings and I am still getting the error, even after I turned this feature off I still get the error

![image](https://user-images.githubusercontent.com/39809509/47508388-0c43a100-d842-11e8-837c-3abb75430bcc.png)

**Comment by Huskydog9988** [comment]
Ok thanks

**Comment by Huskydog9988** [comment]
worked
