### ISSUE TITLE
ResponseMessage being repeated more than once

### ISSUE THREAD

**Issue by LegendHunter** [Dragory/modmailbot#187]
Why is it when anyone messages the modmailbot it says the response message three times?

**Comment by Dragory** [comment]
Make sure you don't have any old Node.js processes running in the background (e.g. the bot running 3 times - if you're on Windows, check with Task Manager that all node.exe processes are closed before starting the bot).

**Comment by Dragory** [comment]
Are you still experiencing this issue?
