### ISSUE TITLE
Can't Send Pictures More Than 2mb

### ISSUE THREAD

**Issue by Ragnarok345** [Dragory/modmailbot#190]
So I enabled the ability to go all the way to 8mb that the bot would be able to forward for pictures, which used to work. Then enter some issues with my router and port forwarding, yadda yadda, and a month or so later, I'm finally able to turn that on again. But this is what I get when I send anything to the bot bigger than 2 mb. Any help? 
![image](https://user-images.githubusercontent.com/10534873/47946569-92a75500-deca-11e8-81d0-194c2eec7491.png)

**Comment by untuned** [comment]
The image appears to be explicit to Discord.  Try sending a different picture.

**Comment by Ragnarok345** [comment]
Well, but I tried a few different pictures. It seemed specifically related to size. Especially because that was just a picture of my desktop, which I’ve sent to it before. I’ll try it again, though.

**Comment by Dragory** [comment]
The message you're getting is specifically from Discord's side. Try turning off the explicit content filter in your server's settings (under "Moderation"), and see if that helps.

**Comment by Ragnarok345** [comment]
Explicit content filter is already set to "Don't scan any messages." Was by default. It seems more like the bot has "Safe Direct Messaging" turned on all of a sudden, but I don't know how to turn that off.

**Comment by Ragnarok345** [comment]
So this is how it should look for my port forwarding, right? This is how it was when it briefly worked before, but now nothing.

![screen shot 2018-12-09 at 5 37 45 pm](https://user-images.githubusercontent.com/10534873/49706219-7093a780-fbd9-11e8-9413-810fa837edda.png)
