### ISSUE TITLE
Node Gyp issue on npm install - Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by JoshCode** [Dragory/modmailbot#192]
This issue seems similar to  #116, but was not fixed by modmailbot `v2.16.0` (or was reintroduced in 2.17.0)

```
root@hal:/home/gilmore/dev/modmailbot/node_modules# npm install
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/gilmore/dev/modmailbot/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/gilmore/dev/modmailbot/node_modules/sqlite3/lib/binding/node-v67-linux-x64 --napi_version=3 --node_abi_napi=napi' (1)
```

Java version (because java version was mentioned in #116): `OpenJDK 11`
Node version: `v11.1.0`
npm version: `6.4.1`

node-gyp prerequisites are installed (Python 2.7, make, gcc, g++). Already tried both elevated and unelevated.

**Comment by Dragory** [comment]
Can you try with Node.js 10 (instead of 11) and see if that works? Delete the old node_modules directory before running `npm install` again.

**Comment by JoshCode** [comment]
That did it! Thank you!
