### ISSUE TITLE
public-id not installed with no nom install command

### ISSUE THREAD

**Issue by PrinzessinLia** [Dragory/modmailbot#194]
I tried to install the modmail bot on my raspberrypi, cause we really could need a bot like this one on our server. I did it with the npm install command, but unfortunately the module public-ip seems to be not installed unlike all the other modules. Can you give me a hint or help to fix my problem?

Thanks in advance

**Comment by Dragory** [comment]
If you run `npm i --no-save public-ip` manually, does that work?

**Comment by Dragory** [comment]
Are you still experiencing this issue?

**Comment by hugopilot** [comment]
I do :upside_down_face:. Using you purposed command and then `npm start` gives the error: `Please run "npm install" again! Package "public-ip" is missing.'. While running `npm install` and then `npm start` results in: `Error: Cannot find module 'public-ip'`

**Comment by hugopilot** [comment]
I temporarily fixed the problem by commenting
[`const publicIp = require('public-ip');`](https://github.com/Dragory/modmailbot/blob/aeb227f301806c6b3f0b6e6d4a275db54d0fb894/src/utils.js#L5) and replacing [`const ip = await publicIp.v4();`](https://github.com/Dragory/modmailbot/blob/aeb227f301806c6b3f0b6e6d4a275db54d0fb894/src/utils.js#L178) with `const ip = "a_hostna.me";`. `a_hostna.me` could be either your IP, DDNS name or domain.

**Comment by Dragory** [comment]
Changing code in `utils.js` should definitely not be required to fix this. The current recommended command in the README is `npm ci` instead of `npm install`. If you're still running the bot, can you see if that works (in the newest version)?

**Comment by hugopilot** [comment]
I'm currently on a holiday, coming back next saturday. I can test it out then.
