### ISSUE TITLE
pingOnBotMention doesn't seem to be working

### ISSUE THREAD

**Issue by Roxyhands1** [Dragory/modmailbot#196]
If I tag the bot in the main server on my account,, it wont ping in the mailbox server but when I use an alt to do so, it still pings in the mailbox server (logs channel) I dont want it to ping at all when the bot is mentioned in the main server, any help would be greatly appreciated.

**Comment by Dragory** [comment]
Looking at your previous issue (which you closed), you need to change the config values from `"false"` to `false` and `"true"` to `true` (so without quotes).
