### ISSUE TITLE
Can't start a bot!

### ISSUE THREAD

**Issue by Guliveer** [Dragory/modmailbot#198]
> C:\modmailbot\src\config.js:39
>   throw new Error(`Error reading config file! The error given was: ${e.message}`);
>   ^
> 
> Error: Error reading config file! The error given was: JSON5: invalid character '\"' at 10:3
>     at Object.<anonymous> (C:\modmailbot\src\config.js:39:9)
>     at Module._compile (module.js:643:30)
>     at Object.Module._extensions..js (module.js:654:10)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)
>     at Module.require (module.js:587:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\modmailbot\src\index.js:32:16)
>     at Module._compile (module.js:643:30)

that's the thing that pops-out when i type `npm start`

**Comment by myoreoslol** [comment]
@Guliveer Did you npm install it?

**Comment by Dragory** [comment]
There appears to be a syntax error of some sort in your config file (config.json). Please post it here (but remove the token first).

**Comment by Guliveer** [comment]
I had to upload this as .txt because GitHub doesn't allowed me to upload .json
[config.txt](https://github.com/Dragory/modmailbot/files/2630146/config.txt)

**Comment by Guliveer** [comment]
> @Guliveer Did you npm install it?

@myoreoslol 
yes, that was almost the first thing I did

**Comment by reboxer** [comment]
No need to delete anything, you have a lot of missing commas after each value, you are supossed to end them with a comma

`  "status": "DM me to contact staff!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
  
  "ignoreAccidentalThreads": true
  "mentionRole": "here"
  "prefix": "mm!"
  "snippetPrefix": "mm!!"
  "snippetPrefixAnon": "mm!!!"
  "typingProxy": true
  "typingProxyReverse": true
  "allowUserClose": true
}`

**Comment by Guliveer** [comment]
thanks for answer, I'll try it as soon as possible, I'll let you know if it works

**Comment by Guliveer** [comment]
ok, it's working thanks for your help

**Comment by myoreoslol** [comment]
@Guliveer No problem
