### ISSUE TITLE
i cannot seem to make a command to true

### ISSUE THREAD

**Issue by SheelaQueen** [Dragory/modmailbot#201]
I'm not sure if I am doing this correctly, but when making the json5 with the additional commands I add "false" as the default but I coudnt change it on the server so I went head and did "true" via the json5 file and it still doesn't work. I'm sure I'm doing something wrong I just cant figure it out

**Comment by Dragory** [comment]
For `true` and `false`, the value needs to be set *without* quotation marks. Example:

```
...
"allowMove": false,
...
```
