### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by daniel11420** [Dragory/modmailbot#208]
http://raymonf-is.ga/y/9bkne.png
it no work
i am latest ubuntu

**Comment by Dragory** [comment]
Make sure you've run `npm install` in the bot's directory. If you have and are still experiencing this issue, can you tell me the version of Node.js you're running?

**Comment by Dragory** [comment]
@PiGuy6248 Can you try on Node.js 10?

**Comment by PiGuy6248** [comment]
on 10.15.0 now, still not working.
