### ISSUE TITLE
npm install "aborted"

### ISSUE THREAD

**Issue by Jarifa** [Dragory/modmailbot#219]
I am trying to install the server on a A2 Hosting platform server. (CentOS7 Linux)
npm version: 6.4.1
Node version: 8.15.0

after using #npm install it starts loading modules, but after a while it will stop and returns "Aborted".
If I run npm install again after the error it instantly says the process is completed. 
![image](https://user-images.githubusercontent.com/39035187/52535755-7bda8f00-2d52-11e9-8559-69343740441f.png)

when I run the server after this, it will give me this error:
![image](https://user-images.githubusercontent.com/39035187/52535769-9f053e80-2d52-11e9-88b1-a8b1f6afaa3e.png)

it seems that npm install has not finished installing modules correctly, I've tried the latest version before reverting to node v8. but that also did not work.

**Comment by Dragory** [comment]
Hey! This is an issue with npm, so I'm unable to assist with that. However, before trying to install the packages again, delete the old `node_modules` folder. You can also try running `npm ci` instead of `npm install` if you're using a new enough version of npm.
