### ISSUE TITLE
Add a {user} variable into the botMentionResponse to tag users

### ISSUE THREAD

**Issue by KryptoUK** [Dragory/modmailbot#220]
It would be nice if we could mention the user who sent the message inside the botMentionResponse. Especially for more popular servers

**Comment by Dragory** [comment]
Forgot to comment back here. This feature was added to the bot on Feb 22nd (via https://github.com/Dragory/modmailbot/pull/225) and can be used by adding `{userMention}` to the botMentionResponse text.
