### ISSUE TITLE
[Feature Request] Snippet arguments

### ISSUE THREAD

**Issue by SnowyLuma** [Dragory/modmailbot#221]
Snippets currently only allow posting a predetermined text without any alteration, which leads to moderators still needing to type out longer messages if a portion of it changes for every user.

I'd like to be able to put arguments behind the snippet name to replace parts of the snippet with the argument, this could be done by simply assigning numbers to them.

To give an example: we often host giveaways and have the participants DM the mod mail bot if they've won, and it would help us out if we could hand out keys by using a snippet (eg. `--keys ABCD-EFGH`) to post a longer message explaining what to do if it doesn't work etc.

Thank you for the bot and taking the time to read this!

**Comment by Dragory** [comment]
This is now supported in v2.23.0. You can use `{1}`, `{2}`, etc. as placeholders which will be replaced by passed arguments when using the snippet.
