### ISSUE TITLE
error 504 when viewing logs

### ISSUE THREAD

**Issue by SpeedyCraftah** [Dragory/modmailbot#223]
Getting error 504 when trying to access the log link.
Thanks

**Comment by Dragory** [comment]
Unless I'm mistaken, this is an issue in your reverse proxy setup (504 is specifically a "Gateway Timeout error").

**Comment by SpeedyCraftah** [comment]
Hey thanks for the fast reply!
Should i send my config.js file?

**Comment by Dragory** [comment]
No, it's unrelated to that. It's related to whatever you're using as a reverse proxy between the bot and the internet, which I'm unable to help with.

**Comment by SpeedyCraftah** [comment]
Hm, okay. Is there anything else we can do for logging instead of going onto the link? Can we get the whole case another way? Because if i can, I can do the rest. Except i've never used eris, I'm a discord.js person. If you could help I would greatly appreciate it.
Thanks

**Comment by SpeedyCraftah** [comment]
Because we have a big server that has people constantly using mod mail. It would be very useful if we could view the contents of the logs.

**Comment by SpeedyCraftah** [comment]
I just noticed i can fetch all the data from the sqlite database. Thanks for the help anyway.

**Comment by SpeedyCraftah** [comment]
One last question. What table are the threads (if any) thanks

**Comment by Dragory** [comment]
That'd be `threads` for the threads themselves, and `thread_messages` for all messages in the thread.

**Comment by SpeedyCraftah** [comment]
Okay, thanks!

**Comment by smooreace** [comment]
Sorry to re-open this, but I have the same issue. can you elaborate on
"reverse proxy"? I don't know what, or where, I need to go/do to solve
this. I run the bot on a personal machine, the same one that is also
running my website.

**Comment by Dragory** [comment]
Do the log links from the bot have your IP + port (e.g. 127.0.0.1:9000) or have you set a custom URL?
