### ISSUE TITLE
bot not dm to user when i am close to message

### ISSUE THREAD

**Issue by Discordots** [Dragory/modmailbot#224]

**Comment by Dragory** [comment]
Please provide more information when opening an issue. Are you using the `closeMessage` option, but the bot is not sending a DM when you `!close` a thread?

**Comment by Discordots** [comment]
yes i am using !close option if i !close thread will closing but bot not sending dm to user u r thread closed like..

**Comment by Dragory** [comment]
Please post your config.json here (but remove the token first). Also, just to be sure, make sure you restart the bot after any config changes.

**Comment by Discordots** [comment]
yes i did all modules i restarted

**Comment by Dragory** [comment]
Right, can you post your `config.json` (without the token) in that case?

**Comment by Discordots** [comment]
const defaultConfig = {
  "token": null,
  "mailGuildId": null,
  "mainGuildId": null,
  "logChannelId": null,

  "prefix": "!",
  "snippetPrefix": "!!",
  "snippetPrefixAnon": "!!!",

  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible.",
  "closeMessage": true,
  "allowUserClose": false,

  "newThreadCategoryId": null,
  "mentionRole": "here",
  "pingOnBotMention": true,
  "botMentionResponse": null,

  "inboxServerPermission": null,
  "alwaysReply": false,
  "alwaysReplyAnon": false,
  "useNicknames": false,
  "ignoreAccidentalThreads": false,
  "threadTimestamps": false,
  "allowMove": false,
  "typingProxy": false,
  "typingProxyReverse": false,
  "mentionUserInThreadHeader": false,

**Comment by Dragory** [comment]
The `closeMessage` option needs to be set to the message that will be sent, e.g.

`"closeMessage": "Thank you, your ticket is now closed.",`

**Comment by Discordots** [comment]
now after place can do npm start r npm install?

**Comment by Discordots** [comment]
dude thanq u so much i got it.....

**Comment by Discordots** [comment]
is it possible tickets are in private only admin can read.... now the tickets all are seeing i m kept as main guild nd modguild id same ...

**Comment by Dragory** [comment]
You can set `newThreadCategoryId` to a private category's id (remember the quotes around the id), and the threads would open there, privately.

**Comment by Discordots** [comment]
bro can elobarate clear i m not understand

 "newThreadCategoryId": "548890917810077707",   is this crrect way?

**Comment by Dragory** [comment]
Yes. Then just set the discord permissions on that category so it's private.

**Comment by GabrielLewis2** [comment]
I'm sorry on behalf of @Discordots that reading their comments hurts everyone's brain.
