### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KSFlowers** [Dragory/modmailbot#232]
Seem to be having error R10

**Comment by Dragory** [comment]
I have no idea what that is. Please post a screenshot of the console window with the error.

**Comment by KSFlowers** [comment]
![image](https://user-images.githubusercontent.com/45467260/53696624-f2bff080-3e03-11e9-9460-5648182ee753.png)

**Comment by Dragory** [comment]
Yeah, that's a Heroku error, not a bot error. Check the issues linked above for more info.

**Comment by KSFlowers** [comment]
Do i make a Procfile and insert npm -Dserver.port=$PORT start

**Comment by Dragory** [comment]
I don't know, sorry. I haven't used heroku.
