### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by Smixite** [Dragory/modmailbot#233]
Seems to be having error DiscordRESTError[10008]

**Comment by KSFlowers** [comment]
![43a2fa9d-f38c-4c13-b914-3c29c6953a25](https://user-images.githubusercontent.com/45467260/53699114-d3cf5780-3e1f-11e9-99d0-3c9e4695f441.jpeg)

**Comment by Dragory** [comment]
Are you getting this error repeatedly or was that the only instance?

**Comment by Smixite** [comment]
Repeated

**Comment by Dragory** [comment]
Do you see it happening after any specific action (e.g. closing a thread, deleting a message, editing a message, etc.)?

**Comment by Dragory** [comment]
Are you still experiencing this issue?
