### ISSUE TITLE
Markdown text in the (nick)name does not get escaped

### ISSUE THREAD

**Issue by DarkView** [Dragory/modmailbot#235]
Having any markdown supported by discord in your (nick)name while using the bot will result in it showing up on the other side with it applied.
For example, if you have ||Dark|| as your name, the mods name will be spoilered in the response the user gets and vice versa. Same works for all other markdown.

So with \*Dark\* as my nickname, the user would get this as a response: (Moderator) _**Dark**_: \<Text\>
This is a really big issue if you put ``` around your name, as it will put the name in the response as a codeblock

**Comment by smooreace** [comment]
Talk to Discord about stopping children from using stupid crap in their
names!

**Comment by DarkView** [comment]
> Talk to Discord about stopping children from using stupid crap in their names!
Seeing as the markdown characters are just regular characters, i dont see that happening. Why disallow stars in (nick)names?

**Comment by smooreace** [comment]
Do you realize that Discord came to be as a business tool, and is still
very deeply entrenched in that realm as a collaboration?! Stars and sparkly
BS in a name isn't professional and very much doesn't make a person 'cool'!
It's what children do to attract attention!

**Comment by DarkView** [comment]
I do, but why does that matter? For now it is allowed so for now it is an issue.

**Comment by smooreace** [comment]
You asked a question... I simply answered.

You made a good point initially. So instead of hundreds of people having to
work around that issue, let's address it properly.... at the core of the
problem! That's how things are done efficiently.

**Comment by DarkView** [comment]
True, however i still feel like this should get a fix for modmail. It could cause some issues and so far discord isnt against it. If discord decides to block markdown in (nick)names, it can be removed again :)

**Comment by smooreace** [comment]
That's somewhat fair, but bandaids don't SOLVE anything. They just let
people pretend a problem no longer exists. YOU aren't the one coding that
bandaid! Imagine how long it will take 500 bot authors to "fix" this, and
then unfix it once the true problem is resolved. Compared to how long it
takes Discord to globally remove all the BS characters from a database of
all usernames.

Hundreds of hours vs a few keystrokes....

**Comment by DarkView** [comment]
I didnt say i wouldnt bring it to attention. But sometimes bandaids are needed

**Comment by Dragory** [comment]
Markdown in usernames/nicknames should now be escaped. Please open a new issue if you still see this problem somewhere.
