### ISSUE TITLE
Bot crashes randomly on !close 

### ISSUE THREAD

**Issue by shaba721** [Dragory/modmailbot#236]

**Comment by Dragory** [comment]
Can you send a picture of any error messages you get when this happens?

**Comment by shaba721** [comment]
https://paste.ee/p/4CLvS

**Comment by Dragory** [comment]
I apologize for the lack of response here. Are you still experiencing this issue (or did you switch to another bot)?

**Comment by shaba721** [comment]
i used pm2 so when it does crashes the bot auto restarts so not really sure but with pm2 im good.
