### ISSUE TITLE
Keeping the bot online 24/7

### ISSUE THREAD

**Issue by pikopie** [Dragory/modmailbot#241]
Hi,

I have read the previous resolved/closed issues, but couldn't find an answer, so I am asking here.

I have installed the bot on a VPS server, and was able to make it run after I typed "npm start" in the cmd window.  Everything works fine if I leave the cmd window open on my VPS server.  But whenever I close the cmd window, the bot would go offline.  Please help.  

Thanks.

**Comment by pikopie** [comment]
thanks, I am new to this, and still learning how all this works :)

**Comment by NicoRazor** [comment]
You could use something like pm2 to keep it running. 

https://pm2.io/runtime/

It would automatically restart once it crashes and it would run without a cmd/terminal opend
