### ISSUE TITLE
Localhost vs IP issues

### ISSUE THREAD

**Issue by GoryReceptacle** [Dragory/modmailbot#242]
Possibly similar to Issue#240

I have opened the ports and confirmed through a website that the port is open.

The logs show the url tracing back to my system but does not load, nor does attachments in discord when a user uploads something when it would normally show a preview when a link is shared.

If I removed the IP address and type localhost in the web browser everything works just fine. With this being only accessible by myself, the hoster, no one else can see logs or attachments.

I'm not sure what else is needed.

**Comment by Dragory** [comment]
That should be it, unless there's something further up the chain from you blocking the port (e.g. if you're hosting the bot on your own pc and using e.g. campus internet, they could have their own blocks put in place). Try with some different ports as well, the default is 8890.
