### ISSUE TITLE
Feature Reguest: Display the users current Voice Channel with command

### ISSUE THREAD

**Issue by DarkView** [Dragory/modmailbot#243]
Hey,

most people that report things happening in voice chat currently do one of the folling:
- Tell us the region but not the room number
- Tell us the room number but not the region
- Dont say region or number and just say they need help in their VC
So a command to get the current voice channel of a user would be great!

Regards,
Dark

**Comment by Dragory** [comment]
The user's current voice channel (if any) is now displayed in the thread header.
