### ISSUE TITLE
Allow loading of external modules/plugins to extend the bot

### ISSUE THREAD

**Issue by reboxer** [Dragory/modmailbot#247]
Since the pull request is closed, i was afraid you wouldn't be able to see my comment if i commented, i was thinking that i would be a good idea adding an if statement to check if the option `useExternalModules` (as an example) is true in the config to load modules added by users in `<rootDirectory>/externalModules` to not mess with the core files of the bot, what do you think? i'll PR it if you are ok with it.
PS: is no problem for me if you want to do it yourself with any other additions you can think of, just trying to improve the bot :D

**Comment by Dragory** [comment]
Perhaps an `externalModules` config option with an array of values that are passed more-or-less directly to `require`. Would allow using actual npm packages and any custom directories. I'll need to think about how the bot's API would be exposed to these external modules first though. Will put this up as "enhancement" for the time being.

**Comment by Dragory** [comment]
Hey! There is now basic support for this in v2.23.0. See the Plugins section in the README for more information.
