### ISSUE TITLE
Bot crash on every !close

### ISSUE THREAD

**Issue by Sinnoma** [Dragory/modmailbot#249]
EVERYTIME ! When I execute !close, the bot give me a error !

Error: Couldn't find your IP
    at pify.then.res (/Users/*************/modmailbot-master/node_modules/public-ip/index.js:48:10)

I execute npm install a lot of time, but nothing...
I'm on a MacOS Sierra (10.12.6)

npm version : 
{ npm: '6.7.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.34.0',
  node: '11.12.0',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.26.0',
  v8: '7.0.276.38-node.18',
  zlib: '1.2.11' }

I suppose I give everything, I let you help me !

**Comment by Dragory** [comment]
It seems the bot's crashing when it's trying to figure out your IP for the log links. You can set the "url" config option to `http://YOUR_IP:8890` (replacing YOUR_IP with your ip address) and it should no longer crash.

**Comment by Sinnoma** [comment]
WWWWHHHHAAATTTTTT ?????
I touch anything, I just configure config.json anndd, now he work TOTALLY, without touching with my IP adress
Strange...

**Comment by Sinnoma** [comment]
Erf, i'm just a idiot
I don't configure logChannelId
