### ISSUE TITLE
Everyone has permission to see the chat.

### ISSUE THREAD

**Issue by ManMaker** [Dragory/modmailbot#250]
I tried everything to fix/remove that, that not only Staff, but also normal users. I want to remove that but i don't know how. Please help me with this!
![Screenshot (26)_LI](https://user-images.githubusercontent.com/48062368/55033110-ae92cb00-5012-11e9-8f83-8610c30a4c85.jpg)

**Comment by Dragory** [comment]
You'll need to set `newThreadCategoryId` to a category that only moderators can see. That way the thread should be mod-only as well.
