### ISSUE TITLE
Attachments problem

### ISSUE THREAD

**Issue by Zounq** [Dragory/modmailbot#251]
Hi. When someone trys to send a picture to the modmail, it dosent show up. It Just goes blank. Please help

**Comment by Dragory** [comment]
Probably a port forwarding issue. Like logs, attachments are served from the machine the bot is running on by default. You can either look into opening the bot's port (8890 by default) or set `attachmentStorage` to `"discord"` and `attachmentStorageChannelId` to a storage channel's id in config.json (the storage channel can be any channel, it's where the bot will post attachments if you change attachmentStorage to "discord").

**Comment by Zounq** [comment]
And also, is there a way to make the bot send a message After doing !close?
Like, it sends a message where it says: You ticket has been closed...
