### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by T3NED** [Dragory/modmailbot#254]
Hello, I am having troubles with the logs. I have opened the port 8890 under TCP and restarted my computer but the link error is still a constant of that site cannot be reached. 

Many thanks.

**Comment by Dragory** [comment]
If the bot is otherwise running fine, there's still something blocking the port. Could be Windows Defender, your router, your ISP, etc. However, I'm unable to assist with that - the issue could be caused by a bunch of things, and can't be fixed from the bot's side.
