### ISSUE TITLE
Timeout Issues

### ISSUE THREAD

**Issue by GoryReceptacle** [Dragory/modmailbot#256]
Via CMD
```
C:\modmail\modmailbot-master\src>npm start
Loading modules...
Connecting to Discord...
Connected! Now listening to DMs.
[NOTE] Creating new thread channel xxxxxxxxx-xxxx (hid user info)
Error: Query timed out
    at DNS._ontimeout (C:\modmail\modmailbot-master\node_modules\dns-socket\inde
x.js:98:18)
    at Timeout.ontimeout (C:\modmail\modmailbot-master\node_modules\dns-socket\i
ndex.js:52:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

C:\modmail\modmailbot-master\src>
```

**Comment by Dragory** [comment]
This seems to be a DNS/network error of some sort. If it's happening every time you start the bot, I would recommend switching DNS servers (to e.g. Cloudflare's 1.1.1.1) and trying again. If it only happened once, it was probably a random network error and shouldn't require any action.

**Comment by Rekt100X** [comment]
Seems to want to listen to DMs but will crash when !logs are pulled. Might just be the recent update. I'll revert back to 2.19.

**Comment by GoryReceptacle** [comment]
Seems to want to listen to DMs but will crash when !logs are pulled. Might just be the recent update. I'll revert back to 2.19.

**Comment by Dragory** [comment]
The recent update shouldn't change anything related to this. Can you try setting the `url` config option manually in the config file? It should be e.g. `http://<your ip>:8890` (replacing `<your ip>` with your ip).

**Comment by GoryReceptacle** [comment]
Change the IP in the util.js but no change.

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd "C:\modmail\modmailbot-master\src"

C:\modmail\modmailbot-master\src>npm start
Loading modules...
Connecting to Discord...
Connected! Now listening to DMs.
[INFO] Failed to send message to thread channel for xxxxxxxx#xxxx because
the channel no longer exists. Auto-closing the thread.
[NOTE] Creating new thread channel xxxxxxxx-xxxx
Error: Query timed out
    at DNS._ontimeout (C:\modmail\modmailbot-master\node_modules\dns-socket\inde
x.js:98:18)
    at Timeout.ontimeout (C:\modmail\modmailbot-master\node_modules\dns-socket\i
ndex.js:52:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

C:\modmail\modmailbot-master\src>
```

The bot was able to receive a message and send a message but showed an error when a user uploaded a picture. I believe this is the same issue when the bot tried to close the thread.

**Comment by Dragory** [comment]
Sorry for no response here.

If you're still interested in running the bot, please put the IP in the `url` config option (e.g. `"http://12.34.56.78"`) instead of modifying bot files under `src` directly. Since this is a known issue that is generally solved by setting the `url` option, I'm closing the issue.
