### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by Zounq** [Dragory/modmailbot#257]
Hi, when someone sends a message to the bot, and the time [15:02] is Not correct to the original time. Like, it says [15:02] and it is 16:00.

The message looks like this: [15:50] Username: Message here

**Comment by Dragory** [comment]
This is with `threadTimestamps` set to `true`, right? Those timestamps are always in UTC (i.e. +00:00), not localized to any specific region. There's currently no option to change this.
