### ISSUE TITLE
Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443

### ISSUE THREAD

**Issue by smooreace** [Dragory/modmailbot#258]
Finally jumped back in to try to get this working again. updated to the newest release, used my original config.json. Fired it up the first time and everything acted as it should. I was able to send plain text messages back and forth as expected. I'm not sure if it was the testing of sending an attachment, or my trying to open a log, but one of those caused the error, and the bot crashed. Now trying to restart it causes an instant crash

`Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443`

**Comment by Dragory** [comment]
This is a network error of some sort - don't think I can do anything to solve it. However, it's related to addresses i.e. DNS. You could try switching to a different DNS server (e.g. Cloudflare's 1.1.1.1) and see if it works then.

**Comment by smooreace** [comment]
Adding an attachment to a message doesn't suddenly create DNS issues. I can kinda see if it was the clicking a link to a log entry, except there is no DNS issue with my domain. And neither situation would persist after the both was restarted if it were DNS based

**Comment by Dragory** [comment]
Based on the error, the bot was unable to resolve discordapp.com to an ip when trying to make an api call or download an attachment. That's why I called it a DNS issue.

**Comment by smooreace** [comment]
That makes sense... Was going to do a test. Fired up the bot to get the
error, then was going to do a trace to the domain. Except the bot started
fine that time.

Testing further to try to duplicate the crash from yesterday leads to a 404
error when I hit a link to a log entry. And trying to DM the BOT with an
image attachment I get the following. (bot is running on a different
machine)

> Error: EXDEV: cross-device link not permitted, rename
>> 'C:\Users\SMOORE~1\AppData
>
> \Local\Temp\2\tmp-25868CnFStF7t3647.tmp' ->
>> 'H:\xampp\modmailbot-master\attachme
>
> nts\562670124050677780'
>
>

**Comment by smooreace** [comment]
That did crash the bot BTW.

**Comment by Dragory** [comment]
Hmm, can you try placing the bot's files on the C: drive and see if that works? It seems there's an issue moving the downloaded attachments from the temp folder (which is on the C: drive) to the bot's folder (which seems to be on the H: drive). I might need to change it so the bot copies the file over and deletes the original instead of moving it directly, or an option to specify a custom temp folder where the files are first downloaded.

**Comment by smooreace** [comment]
I can do that temporarily.. but I'm sure you can see that's not a good
final solution!

**Comment by smooreace** [comment]
OK... moved, and got the DNS issue again. And confirmed its a DNS issue.
Strange as Im running Googles DNS 4.4.4.4

Connecting to Discord...
>
> Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
>
>
>> C:\modmailbot-master>ping discordapp.com
>
> Ping request could not find host discordapp.com. Please check the name
>> and try again.
>
>

**Comment by Dragory** [comment]
Sorry for no response here.

Since this is a DNS issue, I can't really do much to help from my end. If you're still interested in running the bot, I would recommend trying some other DNS servers (such as `1.1.1.1`).

**Comment by star-warrior** [comment]
Just check your Internet connection .... Thats the problem
