### ISSUE TITLE
Update issue (UPDATE THE REPO!)

### ISSUE THREAD

**Issue by QuinnTDIP** [Dragory/modmailbot#26]
I can't use the bot due to there not being the right settings (or something else?) and NEED HELP!
![screen shot 2017-08-17 at 2 21 38 am](https://user-images.githubusercontent.com/25911649/29400514-41bbf990-82f3-11e7-9941-17698694cb00.png)

![screen shot 2017-08-17 at 2 24 00 am](https://user-images.githubusercontent.com/25911649/29400485-30c860d8-82f3-11e7-8cff-af338e2070b9.png)

**Comment by Dragory** [comment]
This is, again, an issue with your Node version being too old. Update to at least Node.js 8 and confirm it's updated with `node -v`.
