### ISSUE TITLE
Changing Mod Mail Message

### ISSUE THREAD

**Issue by T3NED** [Dragory/modmailbot#260]
Hello, just a quick one. Where could I locate the message that responds to the user when they DM the bot? (where it is replied to the user)

**Comment by Dragory** [comment]
If I understood correctly which message you're referring to, that'd be the `responseMessage` config option.

**Comment by T3NED** [comment]
Yes, I know that. I would like to check if the user has any roles on the main guild. And if they don’t then return and send a message instead of opening a new thread

**Comment by T3NED** [comment]
What line and what file can I find where this message is sent?

**Comment by Dragory** [comment]
That'd be here:
https://github.com/Dragory/modmailbot/blob/2a20d9fdaa34a3c3c2ac9b70bc068d511458470f/src/data/threads.js#L151
