### ISSUE TITLE
Cannot send an empty message

### ISSUE THREAD

**Issue by Dezyox** [Dragory/modmailbot#263]
Error: DiscordRESTError [50006]: Cannot send an empty message

Sometime happend with Heroku

**Comment by Dragory** [comment]
Make sure you don't have e.g. the responseMessage option set to an empty string (`""`) as that might cause the bot to try to send an empty message.

**Comment by Dezyox** [comment]
That's happend when we do anything... And responseMessage is not empty in config.json and in config.js

**Comment by Dragory** [comment]
Can you show your current config.json (without the token)?

**Comment by Dezyox** [comment]
{
  "token": "-",
  "mailGuildId": "552900127262507009",
  "mainGuildId": "552900127262507009",
  "logChannelId": "559329611822137346",

  "status": "MP pour contacter le staff",
  "responseMessage": "Merci de votre message! Nous vous répondrons le plus rapidement possible"
}

**Comment by Dezyox** [comment]
const json5 = require('json5');
const fs = require('fs');
const path = require('path');

let userConfig;

// Try to find our config file from several options
const configFiles = [
  'config.json',
  'config.json5',
  'config.json.json',
  'config.json.txt',
  'config.js'
];

let foundConfigFile;

for (const configFile of configFiles) {
  try {
    fs.accessSync(__dirname + '/../' + configFile);
    foundConfigFile = configFile;
    break;
  } catch (e) {}
}

if (! foundConfigFile) {
  throw new Error(`config.json introuvable!`);
}

// Parse the config using JSON5
try {
  if (foundConfigFile.endsWith('.js')) {
    userConfig = require(`../${foundConfigFile}`);
  } else {
    const raw = fs.readFileSync(__dirname + '/../' + foundConfigFile);
    userConfig = json5.parse(raw);
  }
} catch (e) {
  throw new Error(`Impossible de lire le fichier config.json! L'erreur est: ${e.message}`);
}

const defaultConfig = {
  "token": "-",
  "mailGuildId": "552900127262507009",
  "mainGuildId": "552900127262507009",
  "logChannelId": "559329611822137346",

  "prefix": "!",
  "snippetPrefix": "!!",
  "snippetPrefixAnon": "!!!",

  "status": "contacteur de staff",
  "responseMessage": "Merci de votre message! Nous vous répondrons le plus rapidement possible.",
  "closeMessage": "Conversation fermée, merci d'avoir contacter le staff ! :wink:",
  "allowUserClose": true,

  "newThreadCategoryId": "559128466461556746",
  "mentionRole": "here",
  "pingOnBotMention": true,
  "botMentionResponse": "Afin de pouvoir contacter le Staff et recevoir un aide, vous pouvez m'envoyer un message privé ! :wink:",

  "inboxServerPermission": null,
  "alwaysReply": true,
  "alwaysReplyAnon": false,
  "useNicknames": true,
  "ignoreAccidentalThreads": true,
  "threadTimestamps": false,
  "allowMove": true,
  "syncPermissionsOnMove": true,
  "typingProxy": true,
  "typingProxyReverse": true,
  "mentionUserInThreadHeader": true,

  "enableGreeting": true,
  "greetingMessage": null,
  "greetingAttachment": null,

  "requiredAccountAge": null, // In hours
  "accountAgeDeniedMessage": "Votre compte Discord à été créer trop tôt pour pouvoir utiliser Mail Bot !",

  "relaySmallAttachmentsAsAttachments": false,
  "smallAttachmentLimit": 1024 * 1024 * 2,
  "attachmentStorage": "discord",
  "attachmentStorageChannelId": "559329611822137346",

  "port": 8890,
  "url": null,

  "dbDir": path.join(__dirname, '..', 'db'),
  "knex": null,

  "logDir": path.join(__dirname, '..', 'logs'),
};

const required = ['token', 'mailGuildId', 'mainGuildId', 'logChannelId'];

const finalConfig = Object.assign({}, defaultConfig);

for (const [prop, value] of Object.entries(userConfig)) {
  if (! defaultConfig.hasOwnProperty(prop)) {
    throw new Error(`Invalid option: ${prop}`);
  }

  finalConfig[prop] = value;
}

// Default knex config
if (! finalConfig['knex']) {
  finalConfig['knex'] = {
    client: 'sqlite',
      connection: {
      filename: path.join(finalConfig.dbDir, 'data.sqlite')
    },
    useNullAsDefault: true
  };
}

// Make sure migration settings are always present in knex config
Object.assign(finalConfig['knex'], {
  migrations: {
    directory: path.join(finalConfig.dbDir, 'migrations')
  }
});

// Make sure all of the required config options are present
for (const opt of required) {
  if (! finalConfig[opt]) {
    console.error(`Missing required config.json value: ${opt}`);
    process.exit(1);
  }
}

if (finalConfig.smallAttachmentLimit > 1024 * 1024 * 8) {
  finalConfig.smallAttachmentLimit = 1024 * 1024 * 8;
  console.warn('[WARN] smallAttachmentLimit capped at 8MB');
}

// Specific checks
if (finalConfig.attachmentStorage === 'discord' && ! finalConfig.attachmentStorageChannelId) {
  console.error('Config option \'attachmentStorageChannelId\' is required with attachment storage \'discord\'');
  process.exit(1);
}

// Make sure mainGuildId is internally always an array
if (! Array.isArray(finalConfig['mainGuildId'])) {
  finalConfig['mainGuildId'] = [finalConfig['mainGuildId']];
}

// Make sure inboxServerPermission is always an array
if (! Array.isArray(finalConfig['inboxServerPermission'])) {
  if (finalConfig['inboxServerPermission'] == null) {
    finalConfig['inboxServerPermission'] = [];
  } else {
    finalConfig['inboxServerPermission'] = [finalConfig['inboxServerPermission']];
  }
}

module.exports = finalConfig;

**Comment by Dezyox** [comment]
Hmmm, I think it's not because there is a error in config, but a error with an another bot, but his prefix is ., not !, Name bot : Echo

**Comment by Dezyox** [comment]
Nope, that's when a member join the server

**Comment by Dezyox** [comment]
That's just a error of my part, sorry
