### ISSUE TITLE
How to log

### ISSUE THREAD

**Issue by whootiewhoo** [Dragory/modmailbot#265]
![8890](https://user-images.githubusercontent.com/49308678/55729565-5f6e7200-59e4-11e9-80c7-0e7eb18fc32a.png)
i'm using port 8890 like told in all of the other log issues 

![port](https://user-images.githubusercontent.com/49308678/55729682-93e22e00-59e4-11e9-8dfa-e6eb46bb9286.png)
my port is open
![help](https://user-images.githubusercontent.com/49308678/55729800-d277e880-59e4-11e9-916f-d5401ce919a7.png)
I'm presented with this constantly

**Comment by Dragory** [comment]
If you remove the quotes around `"8890"`, does that help?

**Comment by SpeedyCraftah** [comment]
I had problems with this before, changing the port from a string to a number fixed it
