### ISSUE TITLE
Logs error heroku

### ISSUE THREAD

**Issue by neurax-serv** [Dragory/modmailbot#268]
```at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=neurax.herokuapp.com request_id=d5290f4f-407c-423c-ac5f-000ce25b451d fwd="194.44.36.115" dyno= connect= service= status=503 bytes= protocol=https```
This error i get, when i want to view logs.

**Comment by SpeedyCraftah** [comment]
This won't work on heroku as heroku doesn't allow write access. You need to find another host

**Comment by Dezyox** [comment]
You got a idea for a another host ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SpeedyCraftah** [comment]
You could use glitch.com

**Comment by McGRiMTV** [comment]
You are getting the error `"No web processes running"` which means that you have the web running, but you should have the worker running.

To Fix this, go to 'Dynos' and select uncheck web and then check worker.

I have been hosting my modmail bot on heroku for months now, and have had no issues.

If you need any more support please contact me on Discord @McGRiM#2354
