### ISSUE TITLE
Guild Joined At

### ISSUE THREAD

**Issue by T3NED** [Dragory/modmailbot#269]
I'm not to familiar with Eris, much like where we have the option to check if the account created at age is too low, could you help me check if the user messaging the bot has a required joinedAt age. So if the user has just joined the server, they cannot message the bot, so instead it returns and sends a message. 

-Thanks

**Comment by reboxer** [comment]
Sounds useful, will PR tomorrow 👌

**Comment by T3NED** [comment]
> Could be useful, will PR tomorrow 👌

Than

**Comment by T3NED** [comment]
Oops, didn't mean to close. Thank you

**Comment by Dragory** [comment]
This is now possible in version 2.21.0, thanks to @reboxer's pull request!
