### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by QuinnTDIP** [Dragory/modmailbot#27]
Attempted to run an instance of the bot, have run npm install & setup everything (I hope)

I have attempted this many times, here's a screenshot:

![screen shot 2017-08-17 at 2 24 00 am](https://user-images.githubusercontent.com/25911649/29498771-45f4f7b4-85c8-11e7-845f-82223fd0188f.png)

**Comment by QuinnTDIP** [comment]
![screen shot 2017-08-20 at 7 23 44 pm](https://user-images.githubusercontent.com/25911649/29499718-215ea6a6-85dd-11e7-85e3-b0e9aeed540a.png)

**Comment by QuinnTDIP** [comment]
The error has changed :\

**Comment by Dragory** [comment]
The second error seems to indicate there's something already running on port 8890. You can change the "port" value in config.json to something else, such as 9200.

**Comment by QuinnTDIP** [comment]
Ahh (Another modmail bot xD) Thank you
