### ISSUE TITLE
Suggestion: auto-move on !close command; possibly !close 15m <extra> 

### ISSUE THREAD

**Issue by YesJimPossible** [Dragory/modmailbot#271]
To prevent clutter in busy moments while many threads have a timed closure, it would be nice to have a command that automatically moves threads to a "closing" category and perhaps moves them back as well. 

So `!close 15 move` would set a timer for closing, move the thread to another category and move it back if the close command is cancelled. 

Similar but slightly different to AndreasGassmann's suggestion [here.](https://github.com/Dragory/modmailbot/issues/127)

**Comment by DarkView** [comment]
Merging into #127
