### ISSUE TITLE
Bot crashes

### ISSUE THREAD

**Issue by pikopie** [Dragory/modmailbot#273]
Hi this is the cmd log:-

![image](https://user-images.githubusercontent.com/48026548/56572519-cd748500-65f1-11e9-8d3e-5de5f8917def.png)

Please help.  Thanks !

**Comment by pikopie** [comment]
Update:

I downgraded by my nodejs to 8.5 version, and it no longer crashes.  But now pictures sent to the ModMail won't open as shown in the screenshot below:-

![image](https://user-images.githubusercontent.com/48026548/56632781-f3e7fe00-668d-11e9-8086-ce89278951a8.png)

Please help.  Thanks !

**Comment by Jarifa** [comment]
quick workaround; change the config to include: "attachmentStorage": "discord"

**Comment by pikopie** [comment]
> quick workaround; change the config to include: "attachmentStorage": "discord"

This is what happened after I added "attachmentStorage": "discord" in the config file:-

![image](https://user-images.githubusercontent.com/48026548/57183937-4cb56300-6ee6-11e9-9d41-12998e070158.png)

Anything I am missing?  Thx in advance.

**Comment by pikopie** [comment]
I have just read most of the previous issues.  Do I need to type out (1) "attachmentStorage": "discord", and (2) "attachmentStorageChannelId" myself?  or are these already found in the config.json?  As I don't see these two anywhere.  Thanks.

**Comment by Dragory** [comment]
You need to add them both manually. The example config file only contains a few common options by default.

**Comment by pikopie** [comment]
thanks !  fixed !
