### ISSUE TITLE
Error: Cannot find module '/home/container/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'

### ISSUE THREAD

**Issue by ZachZeop** [Dragory/modmailbot#274]
I have the same issue as shown here:
https://github.com/Dragory/modmailbot/issues/217

but no explanation or fix was provided on how to solve this issue. I know it was closed so I apologize but I can't figure this out. Please help.

**Comment by Dragory** [comment]
Try running `npm rebuild` and if that doesn't work, delete the entire node_modules folder and run `npm install` again.

**Comment by ZachZeop** [comment]
Hey, I deleted node_modules and then ran npm install a few times with no success. But oddly, with the way I'm doing it, I fixed it by deleted node_modules, made npm install the startup command and then after it was done installing, changed the startup command to npm start.
