### ISSUE TITLE
Log issue

### ISSUE THREAD

**Issue by Nxhyy** [Dragory/modmailbot#275]
Hello, I was wondering if you could help me fix the logs and i have already look through some of these threads on github but all they say is "make sure port 8890 is open" but i don;'t know how to do that.

**Comment by Dragory** [comment]
The exact steps would depend on your specific setup. See https://portforward.com/ for instructions for port forwarding. If you're running the bot on a VPS/other server, you'll need to ask your host for more info on this. The issue could also be due to a firewall blocking the port.
