### ISSUE TITLE
Opening the log files.

### ISSUE THREAD

**Issue by T3NED** [Dragory/modmailbot#285]
Hello, I keep getting the error of `Error: Couldn't find your IP`. How can I fix this? 

I have tried to put my public ip in like this `IP:PORT` to the `URL` config option, but I get an error in the browser, when I use localhost it works fine, but mine is on a VPS so I cannot use local

**Comment by Dragory** [comment]
So `"url": "http://<vps ip>:<port>"` did not work? What's the error you get in that case? Also verify that the port is correct (the bot uses 8890 by default).

**Comment by T3NED** [comment]
> So `"url": "http://<vps ip>:<port>"` did not work? What's the error you get in that case? Also verify that the port is correct (the bot uses 8890 by default).

**Comment by T3NED** [comment]
Oh, the VPS Ip, thank you
