### ISSUE TITLE
Confirmation before opening a new thread

### ISSUE THREAD

**Issue by Googlelt** [Dragory/modmailbot#286]
If you could add the ability to attach a file to the Response when a user DM's the ModMail Bot.

### **_Example._**
```json 
"responseAttachment": "./logo.png"
```

Another Suggestion would be an option in config.json to have New Thread confirmations On the first message before a new thread is opened and all online staff are pinged the Bot will DM the User back Asking if they're sure they want to contact staff (_With support for a custom confirmation message_)

### **_Example._**
```json
"newThreadConfirmation": true,
"confirmationMessage": "Your about to contact support if this was an accident you don't need to respond. If you need Help reply with \"yes\" "
```

Or something along those lines. because the number of people I get messaging the ModMail bot saying .help or !help ?help or commands or them saying just What are the commands for the bot. is insane.

_I absolutely love this Modmail bot. and I've recommended it to many other server owners who are now using it. <3_

**Comment by Dragory** [comment]
Thank you for the suggestions! Both sound very useful, especially the latter for cutting down accidental modmails from people who respond to the greeting message with something like "sorry?".

**Comment by ANONYM-ANONYM** [comment]
I like idea for cofirmation before opening new thread. Maybe add react menu with whitecheckmark and x emoji to choose if you really want to open a new thread.

**Comment by DarkView** [comment]
Merging into #357
