### ISSUE TITLE
Inbox Server Permissions

### ISSUE THREAD

**Issue by T3NED** [Dragory/modmailbot#289]
Hello, I have tried using the config option called `inboxServerPermission` but it doesn't seem to work. I have attempted to use both an array and a string.

**Comment by Dragory** [comment]
Hey, can you show what values you're using in the option? Also, by "doesn't seem to work", do you mean *no one* is able to use the commands or everyone is?

**Comment by T3NED** [comment]
Yes, no one is able to use the commands. I was using ‘USE_VAD’. This usually works with my other bots. I tried it in an array and string, didn’t allow anyone to use the commands.

**Comment by Dragory** [comment]
Did you solve the problem?

For others stumbling across this issue, the value to set foot inboxServerPermission can be found in https://abal.moe/Eris/docs/reference under "permissions".
