### ISSUE TITLE
SyntaxError: /Users/quinnhammerlund/modmailbot-Bencadenc/config.json: Unexpected token } in JSON at position 611

### ISSUE THREAD

**Issue by QuinnTDIP** [Dragory/modmailbot#29]
I can't find the error, Help? 
![screen shot 2017-08-21 at 5 50 15 pm](https://user-images.githubusercontent.com/25911649/29541374-3d0731fe-8699-11e7-914f-c46d1429c1c9.png)

**Comment by Dragory** [comment]
Remove the last `,` on line 14.

Also, reset your bot token now that you posted it publically!

**Comment by QuinnTDIP** [comment]
I forgot about the token (Stupid Quinn!!) And thanks!

**Comment by QuinnTDIP** [comment]
I'm still getting that error 🤔

**Comment by Dragory** [comment]
Make sure each row, apart from the ones with { } and the last one (port) have a trailing comma.

**Comment by QuinnTDIP** [comment]
ok
