### ISSUE TITLE
Blocked embed exceeds 6000 characters 

### ISSUE THREAD

**Issue by SpeedyCraftah** [Dragory/modmailbot#291]
I've realised that when I tried running the blocked command, it didn't work. So I checked logs and got error 400 bad request embed exceeds 6000 characters. A reaction menu would be perfect for this
Clean debug: https://hasteb.in/owizeban

**Comment by Dragory** [comment]
The errors in the log seem to be originating from a python app. Are you sure you're not talking about another modmail bot, such as https://github.com/kyb3r/modmail?

**Comment by SpeedyCraftah** [comment]
My mistake
