### ISSUE TITLE
help need

### ISSUE THREAD

**Issue by nani210033** [Dragory/modmailbot#294]
bro when i send msg using automatic they shown role msg also i want disable role msg plz help

see below pic they mention my role..
https://gyazo.com/d9d7289578e69f59b632eca21a2e0d2f

**Comment by Dragory** [comment]
The role is only shown if it's visible separately in the sidebar, like so: 

![image](https://user-images.githubusercontent.com/2606411/58632841-8748ca80-82ef-11e9-9db3-744506c5662f.png)

If you disable that, ModMail should not include the role name anymore.

**Comment by nani210033** [comment]
Bro any possible is there while without trun of  display role option

**Comment by nani210033** [comment]
U r really greate broo

**Comment by nani210033** [comment]
Thanx for helping me out
