### ISSUE TITLE
Logs error

### ISSUE THREAD

**Issue by Infinity1231** [Dragory/modmailbot#295]
Hey, I'm hosting my bot on glitch and whenever I send !logs, I see a http link and I can't open it. It's a IP:Port link. Any help? Can I possibly change the port to 3000?

**Comment by Gamerholic** [comment]
I have exactly the same problem.

**Comment by Dragory** [comment]
Sorry for no response here earlier. The port can be changed with the `port` config option. Regardless of what port is being used, if you're unable to open the logs (while the bot is running), the issue is usually due to port forwarding or a firewall.
