### ISSUE TITLE
Issues with permissions and accidental-opens

### ISSUE THREAD

**Issue by Gamerholic** [Dragory/modmailbot#296]
How do I make it so that only a specific role can use the newthread command and other commands? Also in which file can I set the words that don't open a thread? Oh and when I open the log link, the page errors.

**Comment by Dragory** [comment]
- You can set `inboxServerPermission` to a role id to restrict modmail commands to that role only.
- There's no config option to change the "accidental thread words" at the moment, but you can edit them in `src/data/constants.js` under `ACCIDENTAL_THREAD_MESSAGES`
- What error are you getting when opening the log link? Make sure the port the bot uses (8890 by default) is opened on the machine/network the bot is running on to access the logs!

**Comment by sporkwitch** [comment]
Related, should probably add `!close` to the accidental list, as I've had a few try to close as I closed it for them, opening a new thread

**Comment by sporkwitch** [comment]
Submitted #315 for the accidental reopen when trying to close
