### ISSUE TITLE
issue with the database when using pm2 watch

### ISSUE THREAD

**Issue by Hector6704** [Dragory/modmailbot#297]
Hello, I'm trying to start modmail with pm2, but it keeps restarting until it resets the token. 
This is my logs: 
![image](https://user-images.githubusercontent.com/42733258/58870722-060f8000-86c1-11e9-931f-b60d8f8d9c4e.png)
I tried without watching but it still restart at some point

**Comment by Dragory** [comment]
A regular pm2 start (without watch) should only restart when the bot crashes. Watching the files, like in your image, would restart the bot any time the database file updates - which is any time a new thread is opened or similar. If the bot is still restarting with a regular pm2 start, you should check the logs (pm2 logs) for any errors you might be getting that would crash the bot.

**Comment by Hector6704** [comment]
ok, now it works when I don't watch. Thanks !

**Comment by smooreace** [comment]
Sorry to reopen this, but @Hector6704 , can you give some insight into your setting up PM2 for this. It seems a bit more obscure than most other things we use PM2 for

**Comment by Hector6704** [comment]
Well I just started it like that: `pm2 start src/index.js --name modmailbot
--watch`.
Now I don't watch it
