### ISSUE TITLE
Couldn't find IP

### ISSUE THREAD

**Issue by LastxAlive** [Dragory/modmailbot#298]
![image](https://user-images.githubusercontent.com/48368615/58896829-ba73cb00-86ee-11e9-86af-a5a1a80872f5.png)
"Error: Couldn't find your ip" everytime I close a thread why is this?

**Comment by Dragory** [comment]
The bot is trying to find the bot's IP to generate links to the log files. If this fails (like it does for you), you can set the address manually with the `url` config option.

**Comment by LastxAlive** [comment]
where would I set this url option? and how? sorry I'm not too code at this

**Comment by smooreace** [comment]
Read the config... its pretty obvious and has nothing to do with "code"

**Comment by LastxAlive** [comment]
you see I don't know where to start xD I'm so bad what file do I go in to set it?

**Comment by smooreace** [comment]
Read the instruction

**Comment by Dragory** [comment]
Config options are added to your `config.json` file, similar to the ones already there. So e.g. in this case, you'd add:

`"url": "http://123.123.123.123:8890"` (where 123.123.123.123 is your ip, check e.g. https://www.myip.com/)

Between the starting `{` and ending `}`. Make sure each line (except the { and }) have a comma at the end.
