### ISSUE TITLE
Rehosted images don't embed properly

### ISSUE THREAD

**Issue by ahalekelly** [Dragory/modmailbot#3]
When sending an attachment from the modmail to the user, it gets relayed as an attachment, however when going from the user to the modmail, it gets rehosted on the server and linked to. There's an issue with my server where the attachments aren't accessible, probably a firewall issue, but doesn't it just get relayed it as an attachment? I assume you have a reason for this.

**Comment by ahalekelly** [comment]
Nevermind, just found this comment in the code.
> Get a local URL for all attachments so we don't rely on discord's servers (which delete attachments when the channel/DM thread is deleted)

**Comment by ahalekelly** [comment]
I got the firewall fixed, but it doesn't embed the image in the message. Is this the normal behavior?

**Comment by ahalekelly** [comment]
I figured out that the message was being sent before the attachment was ready to be served. Adding a 100ms delay to all messages fixes it and properly embeds the preview. However, it'd be better to only delay the ones with attachments. Where would be the best place to insert a setTimeout?

**Comment by ahalekelly** [comment]
Check [this commit](https://github.com/ahalekelly/modmailbot/commit/e0b06f17d7c4b0a4a99b921fdeaa452e32919bf1), it works but is not very clean. Is there a better way to do it.

**Comment by Dragory** [comment]
Since the attachment saving functions return a promise, one possible way would be to store the promise for each attachment in a Map of attachment id => promise, and then have a function attachmentReady(attachmentId) which returns that promise. This should probably be done in attachments.js. I'll add this after work today!

**Comment by Dragory** [comment]
This should be solved in the latest version. Can you give it a try?

**Comment by Dragory** [comment]
Closing this as the issue should have been fixed in an earlier update.
