### ISSUE TITLE
Problem with starting the bot

### ISSUE THREAD

**Issue by defaultdiego** [Dragory/modmailbot#301]
I would also like to know how to add commands as i want a closing message but i dont know how to do this if you could leave some type of explanation or a file to explain how to add the commands that would be great thanks :)

**Comment by defaultdiego** [comment]
I would also like to know how to add commands as i want a closing message but i dont know how to do this if you could leave some type of explanation or a file to explain how to add the commands that would be great thanks :)

**Comment by Dragory** [comment]
There is no way to add commands other than editing the source code (which I don't offer support for). However, closing messages are supported by default. See the configuration options list in the README for `closeMessage`. These options are put in `config.json` like the ones that are already there.

**Comment by defaultdiego** [comment]
@Dragory In the issue below this one im not sure of what applies to the issue i am having could you please tell me what i need to do as i cannot get the bot to work

**Comment by Dragory** [comment]
You said "it did not give me any warnings when running npm install or npm ci". Did it give any output? Note that the `node_modules` folder is supposed to reappear - that's what `npm install`/`npm ci` does. Deleting it (which `npm ci` does automatically) is just a way to make sure you have fresh versions of all packages.

**Comment by defaultdiego** [comment]
![image](https://user-images.githubusercontent.com/51521352/59523522-768c7d00-8ec9-11e9-8d33-e6c37235c9a2.png)
 This is what happens

**Comment by Dragory** [comment]
Did you let `npm ci` finish, and it gave no output, or did you cancel it? And which version of Node.js are you running (`node --version`)?

**Comment by defaultdiego** [comment]
10.16.0
yes i let it finish ill try again will it say when its finished

**Comment by defaultdiego** [comment]
yeah i just tried it again and it gave no output

**Comment by defaultdiego** [comment]
![image](https://user-images.githubusercontent.com/51521352/59536797-a5681a80-8eec-11e9-803b-56029d38263b.png)
This is happening now @Dragory i tried to see if it worked for my friend and he had the same problem i think i have done everything right ill make a list below of exactly how i installed it.

1. Downloaded node.js 10.16.0 https://nodejs.org/en/download/
2. Downloaded as zip then extracted to another folder
3. made a copy of config.example and renamed the copy config
4. opened the config file and filled in the sections 
![image](https://user-images.githubusercontent.com/51521352/59537800-8454f900-8eef-11e9-91df-ad7c076c9e0c.png) then saved it and closed it
5. opened cmd and typed in cd C:\Users\Admin\Desktop\Discord\modmailbot-master
6. npm ci then waited for that to finish then npm start then the error came up i have tried the npm i -g npm as shown by the image above

i'm not sure if there's some type of program i need to install to make this work

**Comment by jakyu1** [comment]
Yea I think me and default are having the legit same issues. @Dragory  I don't know if this this possible or not but could you send a previous version of the bot to us to see if that works cause it might just be the version not working for us for some reason.

**Comment by Dragory** [comment]
You can see old releases of the bot on the ["Releases"](https://github.com/Dragory/modmailbot/releases) page.

That being said, none of this should be related to any changes made in the bot; at the very least, if `npm` was having issues with e.g. `npm ci`, there would be an error of some sort. But instead, `npm ci` seems to finish without any output and not install half of the required packages. Would either of you be willing to figure this out over remote desktop via TeamViewer or something?

**Comment by defaultdiego** [comment]
![image](https://user-images.githubusercontent.com/51521352/59550311-05000d80-8f61-11e9-90f9-56c45295df3e.png)

I tried an older version and it worked 2.20.0 im not sure what the problem is with the newer version but i would rather a newer version than an older so i hope you figure out what the problem is :)

**Comment by defaultdiego** [comment]
could you also send me examples of how to add configuration options please

**Comment by jakyu1** [comment]
@Dragory  I would do this over discord so I can share screen with you but not where someone ive never met can take control of my pc (no offense) but I just dont trust anyone but if 2.20.0 worked for default might try that first then see what happens

**Comment by defaultdiego** [comment]
The bot works really well thanks for your help @Dragory

**Comment by defaultdiego** [comment]
@jakyu1 Have you tried it yet?

**Comment by Dragory** [comment]
The main change in package.json since 2.20.0 is the dev version of Eris. Considering that's also one of the packages that were not installed when you ran `npm ci`, that's a likely culprit.

I just noticed there's a new stable release of Eris (as of 5 days ago), so I'll be updating the package.json to use that and will make a new release shortly.

**Comment by Dragory** [comment]
@defaultdiego @jakyu1 
There, can you try with [release 2.24.0](https://github.com/Dragory/modmailbot/releases/tag/v2.24.0)?

**Comment by defaultdiego** [comment]
Thank you I will try it when I get back to my pc
