### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ggggguuuuu** [Dragory/modmailbot#302]
1. add embed message for new thread * “ info user “
is better And arranged " roles , account age , ....”

2. true or false , embed message replay bot with person “ DM “
3. hide ip ( example: 174.156.64.21:8890/logs/url ) 
4. Become logs can use ( html + txt + ip )
5. imgur embed *
6. response Messages : can add text More + imgur ; embed ( true or false)
Special file name ؛ Messages

7. add status ; busy , online , watching, streaming, Idle

thank you for reading,

**Comment by Dragory** [comment]
Hey, thank you for the suggestions!

1. Good suggestion, the header is getting a bit bloated right now. Only issue is that logs will still need to have a text, non-embed representation of the message, but that should be doable.

2. Can you elaborate on this? Do you mean making replies to/from the user embeds?

3. You can do this by setting the `url` config option

4. Can you elaborate on this?

5. Can you elaborate on this?

6. Can you elaborate on this? Do you mean making the responseMessage an embed?

7. This should be easy to add. Do you mean just a static value you can set in the config, or dynamic somehow?

**Comment by sporkwitch** [comment]
Note that you need to either have a domain or DDNS set up to access it by FQDN instead of IP

**Comment by Nisyyyy** [comment]
About embeds on response message , its a really good idea.
