### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by WhiteRiderSSB** [Dragory/modmailbot#303]
Is it possible to make the new threads appear in a certain category such as: Support Tickers. I cant find out how. Just tell me the file name and the line of code its on and ill fix that!

**Comment by Dragory** [comment]
You can set `newThreadCategoryId` in the config to the id of the category you want new threads to appear under.

**Comment by WhiteRiderSSB** [comment]
oh im dumb. thanks for the quick response bud
