### ISSUE TITLE
idk how to make a new plugin

### ISSUE THREAD

**Issue by vincentdistoer** [Dragory/modmailbot#307]
idk how to... bc it says it loads but it dont work

**Comment by Craftzman7** [comment]
please provide more detail as to what is wrong

**Comment by mesub7** [comment]
Hi there! Please see the [plugin API doccumentation](https://github.com/Dragory/modmailbot/blob/master/docs/plugin-api.md) to see how you can create a plugin.

**Comment by Gugu7264** [comment]
This might be closed too
