### ISSUE TITLE
upgrade system logs

### ISSUE THREAD

**Issue by gg25465** [Dragory/modmailbot#316]
> logs

change log form path to `txt` file ,

- [ ] upload .txt  Attachment `Discord` or `local`
           Feature :
1. protection publicip v4 [Attack DDos]
2. public ipv4 will be invisible to everyone

 i wish to apply it like image files and videos.

**Comment by sporkwitch** [comment]
Do you mean to have the bot upload the text file as an attachment, rather than linking it and hosting a local Webserver?

I could see this being nice to have, but it's not really a security concern; if you're worried about your own mods ddosing you, get different mods.

**Comment by smooreace** [comment]
Good point! It's funny how server owners like to 'employ' people they don't
trust. But, the text file option does seem like a good option. And it would
help a lot of people that have the problem with opening their logs. Myself
being one of them for a LONG time!

**Comment by sporkwitch** [comment]
Fix your port forwarding or rent a vps. If the server is bug enough to warrant a tool like this, $5/mo is nothing for the uptime and accessibility 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by smooreace** [comment]
Port forward was never the issue. Neither was any firewall.

**Comment by gg25465** [comment]
> Do you mean to have the bot upload the text file as an attachment, rather than linking it and hosting a local Webserver?

yes,

**Comment by reboxer** [comment]
> 1. protection publicip v4 [Attack DDos]
> 2. public ipv4 will be invisible to everyone

If you are worried about your own mods DDoSing your server (or giving the IP to someone else) and the IP of your server being public, you can get a cheap domain and setup cloudflare which isn't difficult, you can even setup HTTPS. This would cover both of your concern.

**Comment by Dragory** [comment]
Please follow issue #106 for updates on this.
