### ISSUE TITLE
Message link in pingOnBotMention

### ISSUE THREAD

**Issue by Ev-1** [Dragory/modmailbot#318]
Change the message sent in the modmail server to include a link to the message the ping occured in instead of just a channel mention. This would make it easier to find the correct message in busy chats or to find older mentions without having to resort to using the search function.

Current behaviour
> Bot mentioned in #general by ABC#1337: "@modmail hello"

Suggested new behaviour
> Bot mentioned in #general by ABC#1337: "@modmail hello"
> https://discordapp.com/channels/guildID/channelID/messageID

**Comment by sporkwitch** [comment]
@Ev-1 I've implemented this in #319.  It hasn't been merged yet, but if you like you can pull from that branch in my fork.

**Comment by untuned** [comment]
this can be closed

**Comment by sporkwitch** [comment]
Partly my fault, i forgot to use the correct keyword in my commit comment so that it would automatically close it when it was merged.
