### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by Garcia1008** [Dragory/modmailbot#32]
When I try to _npm install_ my terminal responds with a _No repository Field_[
<img width="1280" alt="captura de pantalla 2017-09-13 a la s 18 21 49" src="https://user-images.githubusercontent.com/29993298/30405352-e7c7634c-98b0-11e7-900d-8167f4e7a832.png">
](url)

Steps 1-4 and 6  have been done correctlt

**Comment by Dragory** [comment]
You can safely ignore that warning, though there should be more output from npm install. Did you interrupt it before it finished? Is there a node_modules folder in the bot's folder with subfolders inside?

**Comment by Garcia1008** [comment]
There is a node_modules folder as a suborder. No, I didn't interrupt the install

**Comment by Dragory** [comment]
See if you can run the bot. It's possible the npm install finished fine, though I'm curious why there's no output.

**Comment by Garcia1008** [comment]
<img width="1280" alt="captura de pantalla 2017-09-13 a la s 18 53 31" src="https://user-images.githubusercontent.com/29993298/30406040-deba817c-98b4-11e7-9f8f-e5211c930c25.png">
I have istall Node like 2 times so that can't be

**Comment by Dragory** [comment]
Please make sure you install version 8 or higher of node. The default download on the website is the LTS version 6. After upgrading node, please delete the aforementioned node_modules folder, run npm install again, and try running the bot again.

**Comment by Garcia1008** [comment]
Is working. Thanks! 💯 🥇
