### ISSUE TITLE
Add requiredUserRole(s) and roleDeniedMessage

### ISSUE THREAD

**Issue by Ev-1** [Dragory/modmailbot#320]
Some servers have member role systems that require users to get a role(usually by reading rules) in order to get access to the full server. In order to avoid getting a bunch of similar messages along the lines of "how do write in the server?" `requiredTimeOnServer` can be used, but it is not optimal. Since some people read the rules right away and others read them after a day this can lead to people who have read the rules being unable to message modmail and people who haven't being able to use it.

A feature similar to `requiredTimeOnServer` but for roles would therefore be a nice addition to the bot.

**Comment by sporkwitch** [comment]
Don't give the bot read or write perms in that channel and they won't know about it.
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by Ev-1** [comment]
I guess that works in most cases.
