### ISSUE TITLE
Can't find nmp ci?

### ISSUE THREAD

**Issue by RichardzPlayz** [Dragory/modmailbot#323]
Where do I find npm ci  and npm start to do the last 2 steps of the tutorial?

**Comment by reboxer** [comment]
[npm ci](https://docs.npmjs.com/cli/ci.html) and [npm start](https://docs.npmjs.com/cli/start.html) are [node package manager](https://www.npmjs.com/) commands, you just have to type `npm ci` and then `npm start` in your command line if you have installed npm and node with nvm.

**Comment by RichardzPlayz** [comment]
npm ci doesn't work at it tells me 

Did you mean
      c
      i

**Comment by Dragory** [comment]
Make sure your Node.js is updated to at least v10 (you can see your current version with `node --version`). If that doesn't help, run `npm i -g npm` to update npm itself.
