### ISSUE TITLE
Logs not opening

### ISSUE THREAD

**Issue by lexmark66** [Dragory/modmailbot#325]
Hey guys! My logs aren't opening once I click on the link for them. (The bot is on a hoster, so it does not need port forwarded.)

![image](https://user-images.githubusercontent.com/19616107/62013389-e5fbba80-b15f-11e9-8904-19f31180414b.png)

**Comment by sporkwitch** [comment]
Ports still need to be allowed on the firewall and the bot needs to be running. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by lexmark66** [comment]
> Ports still need to be allowed on the firewall and the bot needs to be running. v / r Robert Klebes Mobile: 571-492-8639 https://keybase.io/sporkwitch https://www.linkedin.com/in/klebes
> […](#)
> On July 28, 2019 5:49:02 PM EDT, lexmark66 ***@***.***> wrote: Hey guys! My logs aren't opening once I click on the link for them. (The bot is on a hoster, so it does not need port forwarded.) ![image](https://user-images.githubusercontent.com/19616107/62013389-e5fbba80-b15f-11e9-8904-19f31180414b.png) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #325

There is not a firewall on the Hoster, and the bot is running.

**Comment by Dragory** [comment]
The host may still be blocking some ports by default. If the bot is running, the problem is either due to an incorrect IP being used in the log URL (the bot should detect this automatically, but you can also set the `url` option manually) or a firewall blocking connections to the port somewhere.
