### ISSUE TITLE
Channel Won't Sync with the Category 

### ISSUE THREAD

**Issue by SamuelPlays** [Dragory/modmailbot#328]
Hi so when i have my category perms so that some people can't see different modmails. Well when ever it is in the modmail section and I move it over to one of the teams i have in my server the mods can still see it when they should not but when i go in channel settings it ask me to sync the perms. Is there a way the bot can this auto because I see it works for other servers were you can't see the channel but for me its  not working. Please let me know if you have an answer thanks.

**Comment by Dragory** [comment]
Se the `syncPermissionsOnMove` option to `true` in your config and it should sync the perms automatically.

This should really be enabled by default, not sure why it's not.

**Comment by SamuelPlays** [comment]
Thanks! It worked. Not sure why it was not not like before. Appreciate the help!
