### ISSUE TITLE
Improved log layout/styles

### ISSUE THREAD

**Issue by Huskydog9988** [Dragory/modmailbot#330]
What I'm proposing is a better website UI design. The goal is to have the logs to look like a discord chat. Ex: ![image](https://user-images.githubusercontent.com/39809509/62582936-281dae00-b87c-11e9-8fae-2729752971f3.png)

I've already begun work on this with my branch [here](https://github.com/Huskydog9988/modmailbot/tree/improved-logs). This is mainly broken and any ideas as to how to fix this would be greatly appreciated.

(BTW this new version does use pug as its method to the logs.)

**Comment by Dragory** [comment]
I would probably prefer it in plain html or something like ejs rather than pug, but I like the idea! That being said, I think it should be an option or have both available somehow (e.g. appending `/pretty` to the log URL).

You said your branch is currently "mainly broken" - how so?

**Comment by Huskydog9988** [comment]
The reason I’m using pug is so I can have a template then fill in the messages. The bot is broken in the way logs are displayed, at first it would only show as [object, Object]. Lastly I might just make the `pretty` option a config var as `/pretty` would have to be manually added to each log instead of just having it auto do it.

**Comment by Dragory** [comment]
Perhaps the option could change the link that's posted? That way both options would be available, and the option would control which is the "default".

**Comment by sporkwitch** [comment]
Should be able to template it with HTML and in-line CSS. Keeps things simple. It's just text logs, after all, no need to go crazy. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by Huskydog9988** [comment]
It is just text logs but the current version is very tedious to read. Also I’ll look into using ejs instead.

**Comment by chrissie1234** [comment]
I'm working on making it looks like the Discord interface. Not sure if I'm going to release it though.

**Comment by Huskydog9988** [comment]
That was and is my goal, I just haven't gotten to fixing my code and adding the css.
