### ISSUE TITLE
Suggestion: Automatically limit thread only for first replyer

### ISSUE THREAD

**Issue by BadCoder1337** [Dragory/modmailbot#331]
When a lot of mods online they can compete for an answer. 
Instead possible `!claim` command (from #174) bot can temporarily lock permissions only for first typing mod.
Its can simply implemented with locking when a first `TYPING_START` event received and preventing being unlocked with further `TYPING_START` events. 
Similar functionality implemented in VKontakte Group DMs.
![image](https://user-images.githubusercontent.com/16510197/62644297-7604e580-b952-11e9-96b7-ff3bd6ea76e5.png)

**Comment by ANONYM-ANONYM** [comment]
👍

**Comment by DarkView** [comment]
Merging into #174
