### ISSUE TITLE
npm ci blocked

### ISSUE THREAD

**Issue by Tseacen** [Dragory/modmailbot#334]
I try install npm ci, but the loading blocked after this line :
`node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.3.1 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\Thomas\Downloads\modmailbot-2.25.0\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.9/node-v72-win32-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.9/node-v72-win32-x64.tar.gz
node-pre-gyp info install unpacking node-v72-win32-x64/node_sqlite3.node
`
It's normal? I tried to wait but the loading is blocked for about ten minutes. Without error, without anything.

**Comment by Dragory** [comment]
It should definitely not take 10 minutes. Can you try again, to make sure it wasn't just a temporary problem? If that doesn't work, try deleting the `node_modules` folder and running a regular `npm install` instead of `npm ci`.
