### ISSUE TITLE
Bot connects, but can't resolve the guild due to it being too large

### ISSUE THREAD

**Issue by ThatGuyJustin** [Dragory/modmailbot#335]
With how discord is handling the ready event from the gateway, large guilds take longer to resolve and therefore the bot is unable to find it when it fires the `getInboxGuild` function. 

The guild has 200k+ members, so it makes sense it would take a bit for the API to fire off the `guildCreate` event for it.

Only Error when the bot connects and is awaiting DMs: `Error: The bot is not on the modmail (inbox) server!`

I'm unsure of a way to personally fix it myself or I would have.

**Comment by sporkwitch** [comment]
Because it hasn't been invited to the inbox server... 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by ThatGuyJustin** [comment]
The guild in question is the only server the bot is in.

**Comment by Dragory** [comment]
I published version `v2.26.0` which should wait until all guilds have become available before initializing the bot. Can you give it a try?

**Comment by ThatGuyJustin** [comment]
Yes, it works! Thank you for pushing an update in such a short amount of time. I'll let you know if any other issues arise!
