### ISSUE TITLE
i cant edit config

### ISSUE THREAD

**Issue by jonathan123700** [Dragory/modmailbot#339]
when i try to add new configuration options into config.json the bot doesnt start, what is wrong?
![test123](https://user-images.githubusercontent.com/54201120/63208054-80547b80-c0d8-11e9-9f8c-8d58db4a22a4.PNG)

**Comment by lexmark66** [comment]
You put a slash before the command.

**Comment by jonathan123700** [comment]
in the command prompot?

**Comment by sporkwitch** [comment]
The error tells you what's wrong: there is an invalid character (in this case a forward slash) in one of the lines of the config file. Fix the errors you made in the file. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by jonathan123700** [comment]
oh i solved it, but how to disable the bot?

**Comment by ClearlyElevated** [comment]
Your should also probably reset your token
