### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Garcia1008** [Dragory/modmailbot#34]
Status in the bot is not working, how can I fix it?
<img width="240" alt="captura de pantalla 2017-09-13 a la s 23 48 04" src="https://user-images.githubusercontent.com/29993298/30412620-5fefddb8-98de-11e7-82a7-4ca285cdd2a3.png">
<img width="1280" alt="captura de pantalla 2017-09-13 a la s 23 48 36" src="https://user-images.githubusercontent.com/29993298/30412621-602a0bbe-98de-11e7-8bfb-5c00fedf50d1.png">

**Comment by LegitEzra** [comment]
I believe this is an eris error not modmailbot eris is what modmailbot is coded in and eris has not been working correctly since the most recent discord update

**Comment by Garcia1008** [comment]
When will these be fixed? Or how can I fix the bug

**Comment by Dragory** [comment]
I pushed an update that uses a newer version of Eris. Please download the new version and run `npm install` again.

**Comment by Garcia1008** [comment]
Thanks!
