### ISSUE TITLE
the logs don't display

### ISSUE THREAD

**Issue by jonathan123700** [Dragory/modmailbot#340]
when i open the log link it says "The site does not allow to establish a connection" or something like that, what can i do to fix this?

**Comment by sporkwitch** [comment]
You are effectively looking for someone to run this for you. You seem to lack the basic foundational knowledge to even find these answers. I suggest googling various guides about hosting servers and basic networking and systems admin. These are not issues with the bot, but with your knowledge of the basics. It's outside of scope for here.

See also: http://www.catb.org/~esr/faqs/smart-questions.html
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes
