### ISSUE TITLE
Error: The "listener" argument must be of type Function. Received type object

### ISSUE THREAD

**Issue by DanBennettUK** [Dragory/modmailbot#344]
The error `Error: The "listener" argument must be of type Function. Received type object` appears when attempting to start the bot.

Happens in master branch as well as the last 10 tagged releases.

Attempting to upgrade from 2.11.1.

**Comment by Dragory** [comment]
Does the error have a stack trace after/under it (i.e. list of files/sources where the error is originating from)? Make sure you're also using Node.js 10 or higher. Have you made any modifications to the code?

**Comment by DanBennettUK** [comment]
Annoyingly not. It's literally just that text then exits.

If you have an idea where it may be originating from I can whack some lines in to get more information out.

There's been no code modifications (on 2.11.1 there was, but I've reset the branch before upgrading to the latest tag so no changes are tracked)

`npm ci` was ran on upgrade. Re-ran it now to retest but still no joys!

**Comment by Dragory** [comment]
If you change this line https://github.com/Dragory/modmailbot/blob/master/src/index.js#L54 to use `err.stack` instead of `err.message`, can you see if there's a stack trace?

**Comment by DanBennettUK** [comment]
```sh
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at request (https.js:272:10)
    at Object.get (https.js:276:15)
    at refreshVersions (/home/ec2-user/modmailbot_new/src/data/updates.js:43:9)
```

**Comment by Dragory** [comment]
Can you confirm which Node.js version you're running as well?

You should be able to bypass the error by setting the config option `updateNotifications` to `false`, but I'd very much like to figure out what's causing the error.

**Comment by DanBennettUK** [comment]
Ahar - that could explain it. Currently on `v10.4.1`. I'll look at whether upgrading is viable (without breaking another bot...!). Should be fine to do. If a hotfix goes out I'll give that a shot too! :-)

**Comment by Dragory** [comment]
Can you try `"updateNotifications": false` (i.e. no quotes around `false`)?

**Comment by DanBennettUK** [comment]
That bypasses and works!

Current config has all quotes, so will check that they all work without (I've picked this up from someone else, personally I hate quotes on true/false!)

**Comment by Dragory** [comment]
Honestly I should have some better type checks on the config. An option that expects `true`/`false` should definitely let you know there's a mistake if it's quoted 😛

**Comment by Dragory** [comment]
Closing this since it's an older issue and there's since been a patch that fixes the original error on earlier versions of Node.js.
