### ISSUE TITLE
Better Logs

### ISSUE THREAD

**Issue by spAnser** [Dragory/modmailbot#35]
`!logs <user>` Probably works well but fails once you realize that you forgot the name of the user you closed a ticket with recently.

Would be nice to see a log channel of opened and closed channels with the usernames.

**Comment by Dragory** [comment]
By default, the bot posts a list of closed channel with the usernames on the server's default channel (=same id as server itself). This is currently bot configurable to other channels, but I'm adding that option in the near future.

**Comment by Dragory** [comment]
I pushed a new update that includes a `logChannelId` option. Set this option to the ID of the channel where you want logs posted.

**Comment by spAnser** [comment]
Works well thank you.
