### ISSUE TITLE
error when responding to a message

### ISSUE THREAD

**Issue by noahggarrett** [Dragory/modmailbot#351]

**Comment by noahggarrett** [comment]
Error while replying to user: DiscordHTTPError: 500 INTERNAL SERVER ERROR on POST /api/v7/channels/551595418429947905/messages

**Comment by Dragory** [comment]
By responding to a message, do you mean when you `!reply` / `!r` to a modmail thread? Do you get this error every time you do that, or just randomly? Can you try again after a few hours and see if it still happens?

These ("internal server error") are generally random errors from Discord's side (hence "internal", referring to an error the servers encountered as opposed to a mistake on the bot's part (which would have an error code of 400-499)). As far as I know there's nothing I can do to fix them - but they are usually pretty rare, so they shouldn't cause a lot of problems. However, if you're getting them all the time in a reproducible manner, then that could be something to look into.

**Comment by Computer-Man497** [comment]
I've came across this and what I done was create a new discord bot, with a new token etc...Try that and see if that works.

**Comment by noahggarrett** [comment]
The issue is very rare and only happened ounce to me so it is very likely that is a interval error with discord
