### ISSUE TITLE
On what basis are these Images Hosted?

### ISSUE THREAD

**Issue by Pretuer** [Dragory/modmailbot#352]
I am confused will the Images get hosted by the Hosting data Discord Api or the PC running it?

**Comment by sporkwitch** [comment]
The default behaviour is to store the image on the machine you host the bot on.

**Comment by Pretuer** [comment]
Okay so If I'm correct this stores all files into the PC so we can see what they have put in? Correct?

**Comment by Dragory** [comment]
Yes. By default all attachments sent to the bot via DMs are stored on the PC, and then linked in the thread using the bot's built-in web server (used to attachments and logs).

If you want to change this so they're reposted on a discord channel instead and then linked from there, you can set the following 2 options:
```json
{
    "attachmentStorage": "discord"
    "attachmentStorageChannelId": "channel id here"
}
```
