### ISSUE TITLE
guilds issue

### ISSUE THREAD

**Issue by blexon-g** [Dragory/modmailbot#356]
whenever i try to connect modmail it says Connected, waiting for guilds to become available

**Comment by ClearlyElevated** [comment]
is the bot in both servers? This is something you should be asking in the discord support server. or googling. this isnt an issue or a error with the bot

**Comment by sporkwitch** [comment]
As we discussed, you need to include the logs, or there's nothing we can do.

**Comment by blexon-g** [comment]
C:\Users\thebl>cd C:\modmailbot-master

C:\modmailbot-master>npm start
Connecting to Discord...
Connected, waiting for guilds to become available
