### ISSUE TITLE
[Suggestion] Alerting a User when the thread has been closed

### ISSUE THREAD

**Issue by VeraxonHD** [Dragory/modmailbot#359]
A lot of the time, users don't know when threads have been closed. This can lead to moderators/staff members having to close twice, for example if the user thanks a mod for their help after the mod already closed the thread.

I propose a small message to be sent to the user that would tell them that the thread has been closed, (and possibly make the logs they had available to them at the same time?) in the guise of 

"Thanks for your report. The moderator has marked the issue as resolved and has closed the thread. If you encounter further problems, please don't hesitate to DM here again! Logs for future reference: <logs link>"

I believe this would be of great benefit to mods and users alike. I'd add a PR myself, but it might take a while.

**Comment by SnowyLuma** [comment]
This already exists, you have to set the `closeMessage` option in your config.

**Comment by VeraxonHD** [comment]
Ah, cheers. I'm just a lowly mod on our server so I haven't seen the config file. I'll ask the admins go sort that out. Cheers!!
