### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by Grussle** [Dragory/modmailbot#362]
When I run the code I get an error that says 
Error: ENOENT: no such file or directory, scandir '/app/db/migrations'
I have the files set in the code so I don't know why I'm getting this error.
I'm hosting the bot for someone on glitch.

**Comment by Computer-Man497** [comment]
Is their any stack trace?

**Comment by Dragory** [comment]
They seem to have solved this, based on their messages on Discord. The issue ended up being that they hadn't moved the `db` folder over (they had a bit of a non-standard setup).
