### ISSUE TITLE
responseMessage Should support multiple lines of text

### ISSUE THREAD

**Issue by Fluxty** [Dragory/modmailbot#364]
We cannot give the user more information on what kind of info they should be sending to the bot :(

**Comment by Dragory** [comment]
Ah, good catch! I'll get that fixed soon.

**Comment by sporkwitch** [comment]
It should already; just put a newline in the setting: `\n`

**Comment by Fluxty** [comment]
> It should already; just put a newline in the setting: `\n`

That doesn't work for me either, it just prints the newline character literally.

**Comment by Dragory** [comment]
With the new config format, the idiomatic way to do multi-line strings is a bit different than it was with config.json. I think that's not currently supported for responseMessage, so I'll need to fix that.

**Comment by Dragory** [comment]
Just updating here, `responseMessage` supports multiple lines nowadays (and has since Jan 19).
