### ISSUE TITLE
Anonymous Responses not showing anonymous

### ISSUE THREAD

**Issue by NexExMachina** [Dragory/modmailbot#366]
When the Anonymous responses is set to true if you use a snippet it doesn't send anonymous.

https://files.paranoid.gg/Discord_2019-12-09_01-13-24.png

**Comment by Dragory** [comment]
You can tweak the prefixes for snippets and anonymous snippets (and e.g. flip them so !! sends an anonymous snippet) using the `snippetPrefix` and `snippetPrefixAnon` options. See the [Configuration](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#snippetprefix) page for more information.
