### ISSUE TITLE
Error while I use !close

### ISSUE THREAD

**Issue by JustPoppy** [Dragory/modmailbot#37]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle modmailbot@1.0.0~prestart: modmailbot@1.0.0
6 info lifecycle modmailbot@1.0.0~start: modmailbot@1.0.0
7 verbose lifecycle modmailbot@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle modmailbot@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\ensismensi1\Downloads\modmailbot-master\modmailbot-master\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files\Google\Compute Engine\sysprep;C:\Program Files\nodejs\;C:\Users\ensismensi1\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle modmailbot@1.0.0~start: CWD: C:\Users\ensismensi1\Downloads\modmailbot-master\modmailbot-master
10 silly lifecycle modmailbot@1.0.0~start: Args: [ '/d /s /c', 'node --trace-warnings src/index.js' ]
11 silly lifecycle modmailbot@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle modmailbot@1.0.0~start: Failed to exec start script
13 verbose stack Error: modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid modmailbot@1.0.0
15 verbose cwd C:\Users\ensismensi1\Downloads\modmailbot-master\modmailbot-master
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.6.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
22 error Exit status 1
23 error Failed at the modmailbot@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

That was error.

**Comment by Dragory** [comment]
This particular issue was solved in DMs (missing config value)
