### ISSUE TITLE
Where can I change the Greeting message and make the reply anonymous

### ISSUE THREAD

**Issue by playapotner** [Dragory/modmailbot#376]

**Comment by sporkwitch** [comment]
RTFM
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by playapotner** [comment]
Where is the manual?

**Comment by Dragory** [comment]
The manual is linked on the front page of this repository:
https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md

The option you're looking for is `greetingMessage` and the `!ar` command to send anonymous replies.
