### ISSUE TITLE
Bot is crashing on !close command

### ISSUE THREAD

**Issue by EvilWalks** [Dragory/modmailbot#38]
As the title states. The bot is crashing whenever I try and use the !close command on a thread. It is running locally, but I intend to move it to an Amazon EC2 instance, once I work out how to keep it running smoothly. 

Any ideas as to what the problem might be? 

This is the error text that is output: 

Error: Query timed out
    at DNS._ontimeout (C:\Users\skinb\Desktop\Discord\modmailbot-master\node_modules\dns-socket\index.js:98:18)
    at Timeout.ontimeout (C:\Users\skinb\Desktop\Discord\modmailbot-master\node_modules\dns-socket\index.js:52:10)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\skinb\AppData\Roaming\npm-cache\_logs\2017-10-16T05_48_35_756Z-debug.log

**Comment by Aevroze** [comment]
Came here to report the same issue.

**Comment by Dragory** [comment]
Hmm, this is possibly related to the `public-ip` package I'm using. If you set the config option `url` to your own ip (e.g. `"http://123.123.123.123:8890"` - remember the port), does it still crash?

**Comment by EvilWalks** [comment]
I think I'm possibly adding that config line in wrong, as upon entering it, the bot fails to even start. 

Formatted as such:   "url": "http://***.***.***.***:8890"

Error output below: 

> modmailbot@1.0.0 start C:\Users\skinb\Desktop\Discord\modmailbot-master
> node --trace-warnings src/index.js

C:\Users\skinb\Desktop\Discord\modmailbot-master\src\config.js:6
  throw new Error(`Config file could not be found or read! The error given was: ${e.message}`);
  ^

Error: Config file could not be found or read! The error given was: C:\Users\skinb\Desktop\Discord\modmailbot-master\config.json: Unexpected string in JSON at position 299
    at Object.<anonymous> (C:\Users\skinb\Desktop\Discord\modmailbot-master\src\config.js:6:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\skinb\Desktop\Discord\modmailbot-master\src\index.js:6:16)
    at Module._compile (module.js:624:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\skinb\AppData\Roaming\npm-cache\_logs\2017-10-16T12_28_57_470Z-debug.log

**Comment by Aevroze** [comment]
The default setting for the log channel is to use the server's default channel, so that shouldn't be causing the crash. I had to revert to an older version to make sure it stays working, so I'm not able to test the url config option personally.

**Comment by Dragory** [comment]
As far as I know, the concept of a default channel is being phased out from Discord. I'll make the log channel option mandatory soon.

**Comment by Aevroze** [comment]
Ok, that would definitely help. I can confirm that after setting a log channel, it doesn't crash on close. Thanks!
