### ISSUE TITLE
Error: connect ETIMEDOUT 

### ISSUE THREAD

**Issue by wc3717** [Dragory/modmailbot#380]
Keep getting this error after starting the bot:
`Error: connect ETIMEDOUT 
            at TCPConnectWrap.afterConnect [as oncomplete] <net.js:1056:14> (
    errno: 'ETIMEDOUT'
    code: 'ETIMEDOUT'
    syscall: 'connect'
    address:
    port: 
)`

**Comment by sporkwitch** [comment]
Note the lack of address or port listed; is the machine connected to the internet?  Is there an error indicating the program couldn't bind to a port?  Did you modify any files other than config.ini?

**Comment by wc3717** [comment]
I did have the address and port but I didn't want to display it on the issue. And yes, the thread and snippets have been modified for no normal reply, only anonymous but the other ones we host don't have that change.

**Comment by wc3717** [comment]
Still having this issue every few days.

**Comment by wc3717** [comment]
Here is an image: https://img.ays.best/6JcN6.png

**Comment by Dragory** [comment]
This is a network error, and I don't think there's much that can be done from the bot's side to fix it. I'd recommend having the bot on some auto-restart mechanism (such as pm2) to restart it in these cases.

**Comment by wc3717** [comment]
I have setup pm2 - will see how it goes. Thanks @Dragory

**Comment by BadCoder1337** [comment]
I'm also often getting ETIMEDOUT errors. From mine monitoring this error happens only at Linux systems. I host many bots on my Linux machine. Everything fine with discord.js bots. Only trashy eris throwing random net errors.

**Comment by sporkwitch** [comment]
Most likely the other library is handling the exception and retrying the connection. We could make this do the same but choose not to. Use a process manager like pm2. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes
