### ISSUE TITLE
errors on arm architecture

### ISSUE THREAD

**Issue by hlugt** [Dragory/modmailbot#382]
Hi, am I correct that it can not run on an arm or arm64 architecture? I get errors on sqlite when running npm ci. 
Or do I need to use an older version of nodejs maybe? (tried with 12)

**Comment by GenryMg** [comment]
Hello, it is possible. I have ran the bot on my raspberry pi 4b before, and it works perfectly. you might need to follow the instructions here: https://github.com/mapbox/node-sqlite3/issues/933#issuecomment-389759765. Feel free to contact me if you have any issues, or join the support server: https://discord.gg/zYf67ww

**Comment by hlugt** [comment]
Hi, thx for your reply. I will check it out!

**Comment by GenryMg** [comment]
np, if you face any errors or challenges, just tell me. my discord is GenryMg#0001 btw, you can friend me or find me in the support server

**Comment by hlugt** [comment]
Hi thanks. Sqlite now build fine (well: a lot of warnings, but looked like these are as expected. Have to wait and test the bot a bit, but this issue can be closed.

Again, thx!
