### ISSUE TITLE
Feature request:  Option for anonymous supplicants

### ISSUE THREAD

**Issue by dopeghoti** [Dragory/modmailbot#390]
It can be useful in some cases to offer people the option to contact the mod teams anonymously.  Notwithstanding the fact that records can still be extracted from the logs and the console, it might be worth looking into allowing people to open an anonymous help request which would have a channel name _not_ identical to the supplicant's Discord name, and with the supplicant's name redacted or replaced in the dialogue.

**Comment by Gugu7264** [comment]
This is now possible on the v3 of the bot :)
This can be closed now.
