### ISSUE TITLE
Feature Request:  Have the Bot open a DM with a user on ping

### ISSUE THREAD

**Issue by dopeghoti** [Dragory/modmailbot#391]
For ease-of-use and prevention of clutter, it would be nice to have an option for the Bot to, when pinged with an @ by a user, open a new thread as though the `!newthread` command had been issued.  Bonus points for an optional opening message or for using the standard one.

**Comment by dopeghoti** [comment]
More bonus points for purging the message with the ping in the open channel.

**Comment by Gugu7264** [comment]
This has been added, I think this request can be closed?

**Comment by ANONYM-ANONYM** [comment]
Hi, can you please create plugin for creating threads also with reaction panels on servers (something like Ticket tool panel)

So when user react with defined emoji to defined message modmail will start thread with him
