### ISSUE TITLE
How to host 24/7 for free

### ISSUE THREAD

**Issue by tearless98** [Dragory/modmailbot#399]
How do you host the bot 24/7 for free. Because when I go offline, it goes offline too. I tried so many tutorials online but it doesn't work, thanks.

**Comment by mesub7** [comment]
Most free hosts are quite sketchy. You could try google cloud platform.

Being honest though, there is no such thing as a truly free host.

Or you could get somebody else (that you trust) to host your bot for you.

**Comment by skybird23333** [comment]
try heroku?

mesub7 <notifications@github.com> 于2020年6月12日周五 下午11:22写道：

**Comment by sporkwitch** [comment]
Not supported. You might get it working, but it's extra work and has issues. You won't find help here for making it work. The bot is designed to run on a normal environment; heroku and similar are not normal environments, not intended for production use. 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by Dragory** [comment]
Specific hosting providers are out of scope for the issues here, so closing issue.
