### ISSUE TITLE
Node can't find config.josn

### ISSUE THREAD

**Issue by QuinnTDIP** [Dragory/modmailbot#4]
<img width="643" alt="screen shot 2017-05-09 at 11 32 05 am" src="https://cloud.githubusercontent.com/assets/25911649/25861749/3735b290-34ab-11e7-844f-3ccee83d801d.png">

**Comment by Dragory** [comment]
Hey, you need to run the script with `node`. The full command is:

`node src/index.js`

**Comment by QuinnTDIP** [comment]
ahhh, Thanks

**Comment by QuinnTDIP** [comment]
ok...... Something new, 
![screen shot 2017-05-29 at 12 51 47 pm](https://cloud.githubusercontent.com/assets/25911649/26558356/9cfdfa7a-446d-11e7-9966-1c298c6f5cfa.png)

**Comment by ahalekelly** [comment]
You need to copy config.example.json to config.json and insert your Discord tokens.

**Comment by QuinnTDIP** [comment]
still have the same response :|
<img width="509" alt="screen shot 2017-05-30 at 11 30 38 am" src="https://cloud.githubusercontent.com/assets/25911649/26593949/6fc99c08-452b-11e7-95cc-4c7f7745244e.png">

**Comment by Ohitseddie** [comment]
same problem :/

**Comment by Dragory** [comment]
This mean you haven't copied the `config.example.json` file and named the copy `config.json`. Make sure you do this and fill in the values before running the bot.

On Windows, if you have "Hide known file extensions" enabled (default), you may need to name the file just `config` instead (as the extension is already there, just hidden).

**Comment by QuinnTDIP** [comment]
I'm still getting the same issue, I have ALL files in the screenshot too.
![screen shot 2017-06-26 at 7 26 18 am](https://user-images.githubusercontent.com/25911649/27539150-f4ee36c6-5a40-11e7-92ec-e0b81ae3abf8.png)
