### ISSUE TITLE
Randomly crashes

### ISSUE THREAD

**Issue by nickyo1011** [Dragory/modmailbot#401]
After some time, the bot will stop and go offline and when I go to my PC the cmd says press any key to continue.

**Comment by Dragory** [comment]
Please send screenshots of any errors you get

**Comment by nickyo1011** [comment]
![15922361858767677498705275223399](https://user-images.githubusercontent.com/64706033/84678720-5b9a8180-aefe-11ea-8c2a-487a5540a7c7.jpg)
![15922362370506026305904473126385](https://user-images.githubusercontent.com/64706033/84678803-740a9c00-aefe-11ea-80bd-95151bf585f5.jpg)

**Comment by dopeghoti** [comment]
Those are DNS errors.  That's a problem with your network configuration or your internet connection.

**Comment by nickyo1011** [comment]
My internet is fine though

**Comment by dopeghoti** [comment]
Seemingly not if you are getting periodic DNS errors.

**Comment by nickyo1011** [comment]
I have never had any problems with any other programs besides this one

**Comment by Craftzman7** [comment]
@nickyo1011 if your internet is fine the configuration for your DNS may not be. I recommend checking your DNS settings to see what is going on.

**Comment by Gugu7264** [comment]
Is this still happening/up-to-date?
