### ISSUE TITLE
I'm having an issue with the log system

### ISSUE THREAD

**Issue by Jethro-spec** [Dragory/modmailbot#404]
No logs are being made when tickets are closed, nothing is being wrote to the log folder. Please help me, if anyone has any experience fixing this issue i'm rarely active on github, my discord is Forgotten#1804

**Comment by Dragory** [comment]
The `logs/` folder is not used for logs anymore. It exists in the bot's code for backwards compatibility reasons. Nowadays, all logs are written to the sqlite database in `db/data.sqlite` and accessed through the log links you get when you close a thread.
