### ISSUE TITLE
Nicknames not updating properly

### ISSUE THREAD

**Issue by Froosk** [Dragory/modmailbot#407]
I have noticed in my server that the nickname of the user which appears in the beginning of the thread is not up to date with the user's current nickname. Having done some tests on it myself, I can also confirm that it doesn't update properly when I change my own nickname and message the bot. To me, it looks like a caching issue, and I'm curious to know why the nickname isn't being fetched from Discord's API.

**Comment by lmaoguy123** [comment]
I think you need to restart bot and after i think nicknames will be updated

**Comment by SuperSajuuk** [comment]
@Immortalizd Did you enable the Server Members list privileged intent for your bot application? If not, your bot will not receive the members list, which means the vast majority of updates relating to server Members will not be received by the bot, leading to data being outdated.

**Comment by Immortalizd** [comment]
> @Immortalizd Did you enable the Server Members list privileged intent for your bot application? If not, your bot will not receive the members list, which means the vast majority of updates relating to server Members will not be received by the bot, leading to data being outdated.

Sorry for the very late reply, but yes, I have done that. The bot still doesn't update the nicknames.

**Comment by Gugu7264** [comment]
@Immortalizd I tested it and I couldn't reproduce this, does that still happen? If yes, what's your modmail version?
