### ISSUE TITLE
Different "fallback" text if user has no hoisted roles

### ISSUE THREAD

**Issue by SuperSajuuk** [Dragory/modmailbot#414]
Currently, if a user has the ability to use Modmail bot commands but has no hoisted roles, the fallback text is to show "Moderator". In some situations, this can be highly confusing.

In the server where I'm currently running an instance of Modmail, we have users with Admin perms that are representatives of a company involved with a discord reward element of that server (Fig). We've only just started recently asking one of those representatives to respond to Modmail threads relating to the Fig<->Discord integration not working as intended, and his reply was sent as being from a "Moderator", which can be confusing because they aren't moderators of the discord.

It would be nice if there was a toggle option that would use the highest role they have as the name next to their anonymous replies, instead of Moderator, in those cases where they do not have any hoisted roles.

(You may say the solution is to just "hoist them", but that's not suitable because they don't need to be hoisted, they work in the background and are not "front and center" members of the server to need any hoisting, and it would encourage users to mindlessly send them DM's for support, which is not appropriate in this case),

**Comment by mesub7** [comment]
@SuperSajuuk Hi there!
Version 3 allows the moderator to set their own role with `!role name`. Whilst this may not fully solve your issue, I think it should help in some way.

**Comment by SuperSajuuk** [comment]
@mesub7 Yeah I saw the changelog, I updated and it resolves the issues fully.

**Comment by Dragory** [comment]
You can also set the default fallback role with the new `fallbackRole` option! The option is just text - e.g. `fallbackRole = Staff`.
