### ISSUE TITLE
The bot is not responding to commands

### ISSUE THREAD

**Issue by SweetieRick** [Dragory/modmailbot#416]
When using the bot commands in the modmail thread I cannot issue any bot command. Example, I am gesturing a thread with a user into the inbox server, and I issue the command `!close 1h`, the bot is completely irresponsive into the thread channel. If someone can help me, I can be very helpful

**Comment by Dragory** [comment]
This is most likely not a bug, but something to do with the bot configuration. You should join the support server at https://discord.gg/vRuhG9R so we can take a better look at the issue!
