### ISSUE TITLE
Bot stuck on "Connected! Waiting for guilds to become available..."

### ISSUE THREAD

**Issue by DutchCheese** [Dragory/modmailbot#423]
I don't know what it is but it's stuck on 'Connected! Waiting for guilds to become available...'.
I've added a port in config.ini, I've added the right port + url in config.js, but it's stil not working.

**Comment by Dragory** [comment]
Make sure `mainGuildId` and `mailGuildId` are set properly, and that the bot is invited to both servers (or the 1 server if you're doing a single-server setup).

**Comment by DutchCheese** [comment]
Thank you for your fast answer.

I'am doing a single-server startup and checked the id's 3 times.

**Comment by Dragory** [comment]
Is the bot invited to the server?

**Comment by DutchCheese** [comment]
Yes it is, with administrator permissions.

**Comment by Dragory** [comment]
I've seen this error reported before, even with everything in check like in your case. In these cases, it has usually resolved itself by restarting the bot a couple times. Give that a try!

(Side note: The bot should definitely not have administrator permissions. "Manage Channels" for the ModMail category and basic message permissions should be enough.)

**Comment by DutchCheese** [comment]
Thank you very much, i will try everything you said.

Can it be a problem if i'm not hosting it on my pc? I'm hosting it at a company.

**Comment by Dragory** [comment]
No, that should not be an issue. Hosting on a rented server - e.g. a VPS - is generally recommended, but you can also host the bot on any regular PC.

**Comment by DutchCheese** [comment]
I restarted it 15 times +, isn't that enough 😆? 

Am i doing it right?
![image](https://user-images.githubusercontent.com/52927357/89687605-d2ea0180-d900-11ea-84b3-1fbec0e48de7.png)

I copied the id of both channels on the photo and the id of the server.

mainGuildId = Here i pasted the server id
mailGuildId = here i pasted the modmail-inbox channel id
logChannelId = here i pasted the modmail-log channel id

Thank you very much for your fast support!

**Comment by Dragory** [comment]
Ah, right. `mailGuildId` should be set to the server id as well. In a two-server setup this would be different from `mainGuildId`, but in a single-server setup (like here) they should be the same.

To set a category for new threads, set `categoryAutomation.newThread = CATEGORY ID HERE`

**Comment by DutchCheese** [comment]
Wow your so awesome! Hours of looking for an answer with my hosting.

Thanks for your time and fast answers!
