### ISSUE TITLE
Bot puts everyone in channel

### ISSUE THREAD

**Issue by DutchCheese** [Dragory/modmailbot#424]
The bot is putting everyone of the server in the message ticket. This is just happening today, yesterday it wasn't doing that.

Thank you.

**Comment by Dragory** [comment]
Can you elaborate on what you mean by that? New threads use the permissions of the category where the thread is created (which is set with `categoryAutomation.newThread`), so if the category is publicly visible, the thread is publicly visible.

**Comment by DutchCheese** [comment]
I have no category for my threads. I will try that tho. Thanks

**Comment by DutchCheese** [comment]
He isn't recognizing the category id.

**Comment by mesub7** [comment]
Verify that it is the correct ID.

**Comment by DutchCheese** [comment]
Checkt it 2 times xD, i'm trying again now.

**Comment by DutchCheese** [comment]
I fixed it by changing the bot permissions and putting it above everyone, sometimes it's the simple things. Thanks @Dragory and @mesub7 for your help.
