### ISSUE TITLE
Dynamic links aren't picked up by the bot.

### ISSUE THREAD

**Issue by mesub7** [Dragory/modmailbot#426]
I know it isn't used much but dynamic links (such as Spotify parties) aren't really picked up by the bot. 

They just come up as blank messages to the recipient/staff (depending on who sent it).
![Screenshot_20200815-164818](https://user-images.githubusercontent.com/49169805/90315931-3a164000-df17-11ea-97db-b80db96b608a.png)
![Screenshot_20200815-164800](https://user-images.githubusercontent.com/49169805/90315933-3b476d00-df17-11ea-80cc-42724046bf35.png)

**Comment by Dragory** [comment]
Fixed in 25998fa8a297645fc2e7c8a83a45d2c26439b7de
