### ISSUE TITLE
[Suggestion] Paste Service 

### ISSUE THREAD

**Issue by ClearlyElevated** [Dragory/modmailbot#435]
Adding a Hastebin or PasteBin command so users can get the terminal logs automatically posted to a paste site something similar to [this](https://paste-.glitch.me) it would make support a lot easier for the helpers if all the users needed to do is run a command like 

 ---

> **Example**`[p]debug` / / `[p]logs`

**Comment by Gugu7264** [comment]
Doesn't have sense as you can't send messages of more than 2000 characters on Discord, if the user sends it then the bot see it??
Or I didn't get you?

**Comment by ClearlyElevated** [comment]
> Doesn't have sense as you can't send messages of more than 2000 characters on Discord, if the user sends it then the bot see it??
> Or I didn't get you?

`Doesn't have sense?` what does that mean? i am referring to adding a pastebin or hastebin api command to create paste from within the bot. for text that is longer then 2000

**Comment by Gugu7264** [comment]
Well, people can't send messages longer than 2000 characters on discord... So you either couldn't send or use a command that sends to Pastebin..?

**Comment by DarkView** [comment]
Merging into #45
