### ISSUE TITLE
Suggestion: "Does this answer your question" before opening a thread

### ISSUE THREAD

**Issue by FindingEDENxo** [Dragory/modmailbot#438]
Would it be possible for modmail to have a "does this answer your question?" thing before it opens a thread? 
Kinda like the word hacker is seen in their initial message, and it recommends to them: Are you trying to report a hacker?. If they yes, it responds would respond with the associated response then ask them if this solves their issue and then could talk them to mod mail if their issue isn't resolved.

**Comment by Ronish1122** [comment]
Would be great to have a thing like this

**Comment by DarkView** [comment]
Merging into #357
