### ISSUE TITLE
Add "listening to" or "watching" status to the config

### ISSUE THREAD

**Issue by LiamDun** [Dragory/modmailbot#439]
Add a configuration that allows you to set "listening to" or "watching" status instead of "playing"
so maybe something like BotStatus: Watching or Listening to (with the default being "playing")

**Comment by EvanVS** [comment]
I also really want this! I have seen other servers edit their bots to do it.

**Comment by mesub7** [comment]
I mean, if you know JavaScript then you can definitely go ahead and edit the code to your liking. We can't give support for that though

**Comment by LiamDun** [comment]
I guess there's really no point for suggestions than huh?

**Comment by mesub7** [comment]
I never said that suggestions were bad, I'm just saying that if you can't wait for Dragory or somebody to add it to the bot and you know what you're doing, you can just do it.

**Comment by mesub7** [comment]
@LiamDun This feature is now in the (beta.)[https://github.com/Dragory/modmailbot/releases/tag/v2.31.0-beta.2]

**Comment by LiamDun** [comment]
cool, thanks a lot
