### ISSUE TITLE
[Suggestion / bug] Emoji in the config file

### ISSUE THREAD

**Issue by LiamDun** [Dragory/modmailbot#446]
You can't use any unicode on the config.ini file which means you can't have things like emoji on the "Playing x" status
not a major issue but would be nice to get this working

**Comment by Dragory** [comment]
I'm not able to reproduce this on my end - you can definitely use emojis in the config (see below). Make sure the file is being saved properly as UTF8!

![image](https://user-images.githubusercontent.com/2606411/91917983-37af3680-ecca-11ea-8bec-3b4de8701818.png)
![image](https://user-images.githubusercontent.com/2606411/91917969-29f9b100-ecca-11ea-8638-f96e90124d8c.png)
