### ISSUE TITLE
Better category

### ISSUE THREAD

**Issue by Ronish1122** [Dragory/modmailbot#450]
If a user DM the bot the bot send's a message like (react to this to open a report thread)and then add 2 ,3 or 4 reactions according to the config and when the user reacts on any one reaction it opens the ticket in a specific category like for bugs , suggestions,reports etc having something like this in mod mail would be amazing

**Comment by Eight8-7020** [comment]
That would just make using this as a public bot easier. Just host a seperate instance with the same token but different categoryAutomation.newThread and mainGuildID for each server in my opinion

**Comment by Ronish1122** [comment]
having 4 different bots for 4 different tasks is not what i prefer instead if one bot could do this it would be great

**Comment by Dragory** [comment]
This is now possible with plugins. It's something that likely won't be included in the core bot itself, but a plugin can implement. There is a `#plugin-requests` channel on the support server if you'd like to request someone to work on such a plugin!
