### ISSUE TITLE
Crash when running !newthread <bot_id>

### ISSUE THREAD

**Issue by Breeze-ui** [Dragory/modmailbot#452]
When you use the command !newthread bot_id, the bot shuts down with an error message "Cannot DM this user".
This command can be probably made in such a way that if you enter the bot's id it either ignores or sends a message something like "You can't make me message myself".

**Comment by Ronish1122** [comment]
I don't really think that the bot is supposed to make a ticket with itself and I don't know why you would try using that

**Comment by Eight8-7020** [comment]
It is a feature, and yes, it is supposed to create threads. 
But I am using the beta and I have tried doing it and it's not an issue: it creates a thread but when I try and send it a message it just says "Error while replying to user: Cannot send messages to this user" which kinda makes more sense

**Comment by Breeze-ui** [comment]
What im saying is, instead on logging the error in console, it can say the error in discord, or alteast ignore that command so that the bot doesn't shut down. The main issue im talking about is, the bot shuts down when u do so.
