### ISSUE TITLE
Documentation Inccorect

### ISSUE THREAD

**Issue by KK964** [Dragory/modmailbot#454]
v2.31.0-beta1
In the config docs, it says 'mysqlOptions.username' to set the mysql username. If you try to use that in the config, you get the error 'Missing required option: "ser"'.
I read the cfg.schema.json and in mysqlOption, it says user instead of username. To fix the missing option error, change 'mysqlOptions.username', to 'mysqlOptions.user'.

**Comment by Dragory** [comment]
Good catch, thank you! Updated the dev documentation.
