### ISSUE TITLE
Bug: mentionrole does not disable

### ISSUE THREAD

**Issue by mesub7** [Dragory/modmailbot#458]
Version: 2.31.0-beta.1
Description: Modmail does not disable mentionrole, causing it to ping @here.
Config: 
```
# Required settings
# -----------------
token = token
mainServerId = 710448635502133299
inboxServerId = 710448635502133299
logChannelId = 758002069675311174

# Add new options below this line:
# ----------------------------------
categoryAutomation.newThread = 736984637758373951
closeMessage = Thanks for testing this out!
mentionRole =
port = 8892
reactOnSeen = on 
responseMessage = Thanks for sending us a message. This is just for testing
status = with Pogmas.
typingProxy = on
```

**Comment by Dragory** [comment]
Thanks for catching that! I updated `mentionRole` to accept `none` as a value, and also consider an empty value (`mentionRole = ""`, see quotes) as the same as `none`.

So, going forward, use one of the following:
```ini
mentionRole = none
mentionRole = ""
```

**Comment by mesub7** [comment]
Update

Beta 2 fixes this but it is now called <@none> 

![Screenshot_20200926-203349](https://user-images.githubusercontent.com/49169805/94348881-c13af580-0037-11eb-93ba-cafebdaf553e.png)
