### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by Corrupt04** [Dragory/modmailbot#462]
hi i was wondering if it is possible to send a message through a bot to every user
we currently use the mail mod bot and that allows you to open a ticket with a user and then message them
it would be great if you would be able to run a command such as:
!sendtoall <message>

**Comment by Eight8-7020** [comment]
It sounds like 1 way to get yourself banned from using the discord api

**Comment by Corrupt04** [comment]
you could just cap it to 6 per min (once every 10 secs). so for a server of 120 people, it would take 20 mins to send to everyone

**Comment by Corrupt04** [comment]
> It sounds like 1 way to get yourself banned from using the discord api
you could just cap it to 6 per min (once every 10 secs). so for a server of 120 people, it would take 20 mins to send to everyone

**Comment by dopeghoti** [comment]
Such a workaround of the letter of the API is still likely to get your API key suspended at the very least, and your API privileges revoked in whole as a very real potential consequence of the plan.

**Comment by Dragory** [comment]
This is not something I'm willing to implement in the core bot. You can do so — at your own risk — by using a plugin, but it's not a feature I would add to the bot natively.

**Comment by ClearlyElevated** [comment]
Not worth the risk man. Anymore then 20 or so people you run the risk of getting banned. I added a feature like this and accidentally activated it and it sent 2200 DMs and i was banned before the bot could finish sending the DMs

**Comment by Eight8-7020** [comment]
There is a reason that everyone pings exist.
If they have everyone pings off, there's a reason for it, they clearly don't want notifications
DMing them doesn't make it any different, they'll just block the bot.
