### ISSUE TITLE
Bot crashes if an attachments gets added

### ISSUE THREAD

**Issue by Girtablulu** [Dragory/modmailbot#47]
Hi

Great bot but I found out a little problem with it.
If someone ads an attachment to their message to the bot he crashes and I have to restart everything.

**Comment by Dragory** [comment]
Hey! Please make sure the user the bot is running on has write permissions on the `attachments/` directory.

**Comment by Girtablulu** [comment]
Issue fixed by downgrading from nodejs 9.x to 8.x
