### ISSUE TITLE
Deleting the channel thread does not close the ticket

### ISSUE THREAD

**Issue by Pearl8520** [Dragory/modmailbot#470]
I've had this bug present ever since the bot was in 2.31.0 beta 0 and now, we're in beta 2 and it's still present

**Comment by dopeghoti** [comment]
If you delete a channel, how is the bot supposed to know (as it is not monitoring things in real-time)?  To close the thread, use the _command_ to do so (e. g. `!close` as described at https://github.com/Dragory/modmailbot/blob/master/docs/commands.md#close).  The _bot_ will then take care of deleting the channel.

**Comment by Pearl8520** [comment]
Yea i didn't know that at the time..
