### ISSUE TITLE
Embed

### ISSUE THREAD

**Issue by CyteOP** [Dragory/modmailbot#471]
An embed feature will make it look cooler. So uwu

**Comment by mesub7** [comment]
Not really, on mobile it looks terrible. 

I believe a plugin will be developed once the bot leaves the beta

**Comment by CyteOP** [comment]
Then a help menu for mods?

**Comment by mesub7** [comment]
No sadly. Check the commands list [here.](https://github.com/Dragory/modmailbot/blob/master/docs/commands.md)

**Comment by Eight8-7020** [comment]
It's been brought up as an idea for a plugin before
