### ISSUE TITLE
[SUGGESTION] Claim feature

### ISSUE THREAD

**Issue by Breeze-ui** [Dragory/modmailbot#476]
Say someone DMed Modmail and the thread gets opened.

Now we can have a "!claim" command which when used by a particular mod, The thread becomes replyable only to the claimed moderator. And the thread gets hidden from all other mods. In case we need to show this thread to other mods after claiming, we can use the command "!public" or something to make the thread visible to all other mods. 

This feature can be made "off" by default and can be turned on if needed.

For the other mods to see all the active threads, we can also maybe have a command like "!allthreads" and this can display all the threads including hidden along with the channel id. If a another moderator wants to enter the claimed thread, he can maybe use "!claim channel-id" Im not sure of this.

You may ask what will be the use of this command. This will be helpful for big servers that receives many threads daily. For very small issue, a single moderator may claim the thread and finish it off himself. This also reduces the number of threads u see. So that u don't get confused which thread is what issue.

I'm not sure if this is that worth to be added, also I feel I haven't written the idea completely, If you got any doubts pls leave a comment below and let's discuss!

**Comment by ANONYM-ANONYM** [comment]
Great idea. Please add it

**Comment by DarkView** [comment]
Duplicates #174
