### ISSUE TITLE
[SUGGESTION] Let the user configure auto-replies to be used to answer common questions

### ISSUE THREAD

**Issue by Curioo** [Dragory/modmailbot#477]
It would be nice for the moderation team to answer commonly asked questions by using commands such as
!knownbug - This could maybe automatically answer this; "This is currently a known bug and we are working to fix it!"
or maybe
!dmproof - If you've experienced a user dm advertising, we are going to need the following info from you: proof1, proof2.

This could really improve **workflow** for mods as they dont need to type out answers for common questions hundreds of times.

**Comment by mesub7** [comment]
Do you mean [snippets?](https://github.com/Dragory/modmailbot/blob/master/docs/snippets.md)

**Comment by Curioo** [comment]
Yep, thats the one. Thanks!
