### ISSUE TITLE
Would it be possible to pin the first message in a mod mail thread?

### ISSUE THREAD

**Issue by Markimoomoo** [Dragory/modmailbot#479]
Would it be possible to pin the first message in a mod mail thread?

**Comment by Gugu7264** [comment]
By "the first message", what do you mean?
The user message, the bot message when it pings or the bot message with user's infos?

**Comment by ANONYM-ANONYM** [comment]
Yes, this would be useful to pin first message (Info message with username, account age, ...) when new thread is opened

**Comment by Markimoomoo** [comment]
> By "the first message", what do you mean?
> The user message, the bot message when it pings or the bot message with user's infos?

I mean the account info and stuff.

**Comment by ANONYM-ANONYM** [comment]
This is now possible in new version, you can close this @Markimoomoo
