### ISSUE TITLE
[BUG] Configuration file changes are not reflecting in bot

### ISSUE THREAD

**Issue by lyellread** [Dragory/modmailbot#482]
I am in the process of deploying modmailbot, and most of it works great -- props! 

When I add configuration options:
```
alwaysReplyAnon = on
```
or 
```
attachmentStorage = discord
attachmentStorageChannelId = ******************
```

Nothing changes about the bot. Further, even with `alwaysReplyAnon` commented out, ~~I can not run `!ra` or `!replyanon`~~. 

I am running `node 12.19.0`, `npm 6.14.8`, `modmailbot 2.30.1` on `ubuntu 18.04.5`

My config is currently:
```
# Required settings
# -----------------
token = <token>
mainGuildId = ******************
mailGuildId = ******************
logChannelId = ******************

# Add new options below this line:
# ----------------------------------
categoryAutomation.newThread = ******************
allowUserClose = on
# alwaysReplyAnon = on

# attachmentStorage = discord
# attachmentStorageChannelId = ******************

responseMessage = Thank you for your message! An Officer will reply to you here as soon as possible
status = Moderation
threadTimestamps = on
typingProxy = on
updateNotifications = off
```
Any idea what could be happening?

~Lyell

**Comment by mesub7** [comment]
Try `!ar` and let me know how it goes

**Comment by lyellread** [comment]
@mesub7 `!ar` works great, my bad :). My issue still stands with the configurations, however.

**Comment by mesub7** [comment]
You also need alwaysReply to be enabled for this feature to work

**Comment by lyellread** [comment]
Wow, I misread that part of the docs completely. Thank you again, @mesub7. For now we are OK with links for logs, so I'll close this ticket
