### ISSUE TITLE
Broken all over the place

### ISSUE THREAD

**Issue by dannymichel** [Dragory/modmailbot#490]
I updated to the latest and my staff cant .close threads and half the commands are not working.
Is all this known?

**Comment by Dragory** [comment]
No, this is not normal at all. You're the first one I'm hearing reporting this. Are you seeing any errors in the bot's console?

**Comment by dannymichel** [comment]
there are no errors in the bot console

**Comment by Gugu7264** [comment]
Could you please send the actual file tree you have on your server/computer/whatever your bot is running on?

**Comment by dannymichel** [comment]
```
DiscordRESTError [20026]: Your bot has been flagged by our anti-spam system for abusive behavior. Please reach out to our team by going to https://dis.gd/report and selecting "Appeal an Action Trust and Safety took on my bot" as the Report Type.
    at RequestHandler.request (node_modules/eris/lib/rest/RequestHandler.js:71:15)
    at Client.getDMChannel (node_modules/eris/lib/Client.js:979:36)
    at Thread.getDMChannel (src/data/Thread.js:417:16)
    at Thread._addThreadMessageToDB (src/data/Thread.js:130:34)
    at Thread.saveCommandMessageToLogs (src/data/Thread.js:507:17)
    at Client.<anonymous> (src/main.js:122:14)
```

**Comment by dannymichel** [comment]
i use the same bot token for a lot of things and everything else works.

**Comment by Gugu7264** [comment]
Well, it doesn't have anything to do with modmail bot, you should contact discord as the error message states.

**Comment by Dragory** [comment]
Yeah, this error is unrelated to modmail itself. Please follow the steps in the error to contact Discord.
