### ISSUE TITLE
How do you add the bot to a server?

### ISSUE THREAD

**Issue by S1D3ARM5** [Dragory/modmailbot#50]
Im a newb

**Comment by Dragory** [comment]
Once you've created your bot at https://discordapp.com/developers/applications/me, there's a "Generate OAuth2 URL" button on the bot's page that gives you the link to invite it.

**Comment by sporkwitch** [comment]
Extra clarification: make sure to convert it to a "bot user" first, or the oauth link just errors.

**Comment by sporkwitch** [comment]
@S1D3ARM5 were you able to get this sorted out?

**Comment by S1D3ARM5** [comment]
@sporkwitch I was able to get it right. It works beautifully now. Thanks!

**Comment by sporkwitch** [comment]
@S1D3ARM5 make sure to mark it closed :)
