### ISSUE TITLE
npm is not recognized, also need help with downloading node.js 14

### ISSUE THREAD

**Issue by kevlu8** [Dragory/modmailbot#502]
Hey there, I have downloaded node.js 14.15, it is node.exe in my downloads folder. However, when I run start.bat it says "npm is not  recognized as an internal or external command ...". Is there some sort of node.js installer I missed? Thanks

**Comment by Dragory** [comment]
For help setting up the bot, please visit the support server instead: https://discord.gg/vRuhG9R
