### ISSUE TITLE
Use domain name instead of IP

### ISSUE THREAD

**Issue by byeuji** [Dragory/modmailbot#503]
When a log is recorded from a user interaction and the conversation is closed, the bot generates a URL like:

http://numeric.ip.address:port/logs/uuid

Would it be possible to add a configurable domain name, and output that instead? Like:

http://domain.com:port/logs/uuid

I'm sure there are other features of the bot that could benefit from using domain name as a nice-to-have, instead of raw IP address.

**Comment by SnowyLuma** [comment]
See the [`url`](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#url) config option, it does what you need.

**Comment by byeuji** [comment]
Awesome. Thank you!
