### ISSUE TITLE
object null is not iterable

### ISSUE THREAD

**Issue by YouTube-ZelcaLT** [Dragory/modmailbot#504]
I'm using my snippets but my bot crashes and says this:
Error: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Client.<anonymous> (D:\modmailbot-master\src\modules\snippets.js:63:32)
Press any key to continue . . .
I don't know what to do as i'm unfamiliar with js... Anyone help me?

**Comment by Eight8-7020** [comment]
Have you edited any code?

**Comment by mesub7** [comment]
Hi there! It would be better if this was discussed in the [support server](https://discord.gg/vRuhG9R).
