### ISSUE TITLE
Snippets don't seem to be working

### ISSUE THREAD

**Issue by Samwalton9** [Dragory/modmailbot#51]
I have a number of snippets defined (and `!snippets` shows them to be present) but using them in a chat (with !!snippet, snippet replaced with a snippet name) doesn't seem to work:

```
Available snippets (prefix !!):
dealt, declinestreamer, hi, noproof, noted
```

But doing !!dealt in a modmail ticket just prints `!!dealt`. Any ideas why?

**Comment by Dragory** [comment]
Hey! Are you seeing any errors in the bot console?

**Comment by Samwalton9** [comment]
Turns out this was a case of PEBKAC - we briefly had two modmail bots running and the thread we were testing snippets in had accidentally been opened by the other bot. Snippets work fine in other threads. Thanks anyway!
