### ISSUE TITLE
Small internet stutters will completely take down the bot

### ISSUE THREAD

**Issue by EternalllZM** [Dragory/modmailbot#511]
Hi, I run several self-hosted mod mail instances on Windows Server Core 2019. All of them are on v3.2.0, unfortunately I am running into the following issue which I believe is a small failure in internet connection to Discord. 
The ISP is residential 200/40mbps and the hardware is an HP Proliant G8 DL320e V2

The bot should keep trying to connect or at least have a configuration for a timeout period, instead of immediately failing and requiring manual intervention. As you can see, at the bottom of the image it requires pressing a key and re-running the start.bat cmd.
If this is not possible, let me know.

Here is the log:
![image](https://user-images.githubusercontent.com/43221983/101205366-206a4700-3633-11eb-8fe7-f9301dec13e0.png)

Thank you.

**Comment by sp00nd** [comment]
Happens a lot more often now. I can not even narrow down the cut in service. Today it went out while I was monitoring it and could not find any reason why.

**Comment by DarkView** [comment]
As a workaround, you can also use a service like pm2 (the bot includes a `modmailbot-pm2.json` file in which you would only need to change the name) which will automatically restart the bot on errors.
Hosting any service used in production on a residential internet connection is also suboptimal.

**Comment by GeekCornerGH** [comment]
> As a workaround, you can also use a service like pm2 (the bot includes a `modmailbot-pm2.json` file in which you would only need to change the name) which will automatically restart the bot on errors.
> Hosting any service used in production on a residential internet connection is also suboptimal.

@DarkView I am running Modmailbot from home and i dont have any problem

**Comment by sp00nd** [comment]
Modified the start.bat file to ignore errors and just relaunch. I hope it changes for simple disconnect errors to automatically restart, while keeping critical stops under a "pause" action. Not going to pull request what I did as always restarting on any error is dangerous.

Residential ISP is not a problem. I host several more discord bots and gameservers/PLEX for tens of hundreds without any issues. If there is any stutter, it is never more than a second or two. Uptimerobot never reports any outage.
