### ISSUE TITLE
Suggestion | Can we get a Delete log command? 

### ISSUE THREAD

**Issue by teheim** [Dragory/modmailbot#516]
I wondered if it was possible to get a command that deletes logs. So i can rid users of spammy tickets and test tickets. 
Like "!Delete logentry <Log URL>"

**Comment by Dragory** [comment]
This is a feature that's being planned for after the bot has a more robust permission system! Currently, the bot only distinguishes between "staff or not", and a command like deleting logs should in most cases only be usable by admins/server owners.

**Comment by mesub7** [comment]
(Dupe of #494)
