### ISSUE TITLE
Error 50001: DiscordRESTError [50001]: Missing Access

### ISSUE THREAD

**Issue by ghost** [Dragory/modmailbot#517]
See attachment
![Screenshot 2020-12-19 223515](https://user-images.githubusercontent.com/69178724/102705956-84535900-424a-11eb-8cbc-dafb0bacff15.png)

**Comment by mesub7** [comment]
Hey there! This means that the bot is missing access to the channel it created. Ensure that it has the correct permissions. If you are still having issues then feel free to find us on the [support server.](https://discord.gg/vRuhG9R)
