### ISSUE TITLE
Suggestion: AntiRaid System

### ISSUE THREAD

**Issue by ZerlsDev** [Dragory/modmailbot#522]
When a x (customisable) amount of threads are made within x (customisable) amount of seconds it does a custom action. e.g not create a thread, block them then stops ignoring them etc after x (customisable) seconds, etc with a logging feature and log like 

"**AntiRaid Detected** - Blocking/Ignoring @1, @2, @3"

and edits for members dming the bot within the timeout, or just sends "**AntiRaid Detected** - Ignoring/Blocking @user"

**Comment by pratyushsnake** [comment]
this should be added to the bot its really use full

**Comment by Pace1337** [comment]
Yeah please

**Comment by DarkView** [comment]
Merged into #267
