### ISSUE TITLE
Response Message not sending

### ISSUE THREAD

**Issue by NexExMachina** [Dragory/modmailbot#527]
With MySQL active response message does not send, removing the mysql fixes the issue

**Comment by NexExMachina** [comment]
Not sure what I've missed

**Comment by Dragory** [comment]
MySQL settings are not related to `responseMessage` functionality - I have the bot running with MySQL and a functioning `responseMessage` right now. Can you join the support server so we can troubleshoot the issue? https://discord.gg/vRuhG9R
