### ISSUE TITLE
[Question] Serve attachments through Discord's CDN.

### ISSUE THREAD

**Issue by BStorm888** [Dragory/modmailbot#53]
Is there a way to serve attachments through Discord's CDN instead of through the server the bot is hosted on? If not, could a feature be implemented to do that? Thanks.

**Comment by Dragory** [comment]
There is no option for this at the moment, but I could look into implementing it in the near future.

**Comment by Dragory** [comment]
Hey! I've added an option to send small attachments (<2MB, so most images etc.) as regular Discord attachments in the upcoming update to the bot. The update will be released within the next week.

**Comment by BStorm888** [comment]
Awesome, thanks so much!

**Comment by Dragory** [comment]
The update has been released (more details in README and CHANGELOG). Closing issue.
