### ISSUE TITLE
Log as TXT file?

### ISSUE THREAD

**Issue by StoneMcDev** [Dragory/modmailbot#535]
I was wondering if there can be a feature added for logs to be saved as a TXT file not a link

**Comment by mesub7** [comment]
Hi there, it's already possible!
See [this.](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#attachmentstorage)

You'll want to change it to `discord` and provide a channel ID that the bot can see.

**Comment by StoneMcDev** [comment]
> Hi there, it's already possible!
> See [this.](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#attachmentstorage)
> 
> You'll want to change it to `discord` and provide a channel ID that the bot can see. 

Well thanks but I checked the link and couldn't find it can you screen shot the area where it says it for me

**Comment by mesub7** [comment]
https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#attachmentstorage

**Comment by mesub7** [comment]
This is the best I can do at the moment.

**Comment by mesub7** [comment]
https://cdn.discordapp.com/attachments/740585774055161986/798254396634038272/Screenshot_20210111-180721.png

**Comment by StoneMcYT** [comment]
im trying to save my logs as a txt not save atatchements

**Comment by mesub7** [comment]
Yes, it'll save it as a .txt file in a discord channel so you can download
it.

**Comment by Dragory** [comment]
The setting for logs specifically is [`logStorage`](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#logstorage). Setting `logStorage = attachment` in your config file will save each log as a .txt file in the `logs/` folder and send them as an attachment in your log channel.
