### ISSUE TITLE
Suggestion : Add Watching Or Listening Or Live Status Option

### ISSUE THREAD

**Issue by EAZYBLACK** [Dragory/modmailbot#537]
Add Watching Or Listening Or Live Status Option To Modmail Bot Like In Config.ini
status= Watching
status= Watching DMs

**Comment by mesub7** [comment]
You mean [`statusType`?](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#statustype)

**Comment by EAZYBLACK** [comment]
Oh I Didnt Know This Thx
