### ISSUE TITLE
[Suggestion] Allow admins to edit/delete other staff replies

### ISSUE THREAD

**Issue by Retr0-01** [Dragory/modmailbot#539]
I believe trusted people should have complete control over the bot when it comes to managing threads.

**Comment by Dragory** [comment]
Agreed - this is something I'm looking to add in the future, but it will require a more robust permission system first to differentiate between moderators and admins/owners. I'll update here when there's been more work on that.

**Comment by Retr0-01** [comment]
Awesome! Thanks in advance.

**Comment by DarkView** [comment]
Duplicate of #520
