### ISSUE TITLE
Can't see the previous logs for anyone using the !logs command

### ISSUE THREAD

**Issue by pratyushsnake** [Dragory/modmailbot#541]
please help me out

**Comment by mesub7** [comment]
How are you hosting the bot?

**Comment by SnakePratyush** [comment]
> How are you hosting the bot?

I am hosting it on repl.it

**Comment by mesub7** [comment]
Using repl.it is not recommended.

**Comment by SnakePratyush** [comment]
> Using repl.it is not recommended.

Any alternatives that I can use and the bot doesn't die because of inactivity??

**Comment by mesub7** [comment]
I'm willing to continue this [in the support server.](https://discord.gg/vRuhG9R)

**Comment by pratyushsnake** [comment]
> I'm willing to continue this [in the support server.](https://discord.gg/vRuhG9R)

thank you for replying and looking in the issue, i tried to run the command once again and this time it worked me and gave me the links to the logs but took some time about 3-4 mins to send them, but as this issue is not about the late response i am closing the issue
