### ISSUE TITLE
Not responding!

### ISSUE THREAD

**Issue by RoundingExplorer** [Dragory/modmailbot#544]
The bot is not responding with Thank you for your message! Our mod team will reply to you here as soon as possible.
My config.ini is
```
token =My_token
mainServerId = 804398915612049500
inboxServerId = 804398915612049500
logChannelId = 804399054867267634

# Common settings
# ----------------------------------
prefix = plsmessage
inboxServerPermission = manageMessages
status = Playing a game of postcards
responseMessage = Thank you for your message! Our mod team will reply to you here as soon as possible.

# Add new options below this line:
# ----------------------------------
manageMessages=true

useGitForGitHubPlugins = on
categoryAutomation.newThread = 804399019916263505
```
I have not mentioned my token

**Comment by RoundingExplorer** [comment]
Also I am not being able to make any dm replies

**Comment by RoundingExplorer** [comment]
@Dragory help please

**Comment by mesub7** [comment]
We'll be able to help in the [support server.](https://discord.gg/vRuhG9R)

**Comment by RoundingExplorer** [comment]
I got no help there

**Comment by mesub7** [comment]
Try again.

**Comment by RoundingExplorer** [comment]
Can I get help here?

**Comment by mesub7** [comment]
It's much easier to get help in the discord. 

Regardless, do you get any errors in the console?

**Comment by RoundingExplorer** [comment]
No

**Comment by mesub7** [comment]
Does the bot connect to discord?

If it does, then does replying normally work?

Could you also try and use it without your custom prefix?
