### ISSUE TITLE
Question: How do i put everything in embeds??

### ISSUE THREAD

**Issue by CyberDudeJ** [Dragory/modmailbot#550]
How do i put everything in embeds because I want it to look more professional and more colourful

**Comment by mesub7** [comment]
You can make your own plugin or wait for Dragory to make one.

**Comment by CyberDudeJ** [comment]
how
i am new to making bots :/

**Comment by CyberDudeJ** [comment]
and "plugins" as you say
also Idk how to set the able to move setting and making categories

**Comment by mesub7** [comment]
See this article [on plugins.](https://github.com/Dragory/modmailbot/blob/master/docs/plugins.md#creating-a-plugin)
re Moving tickets: They're enabled by default.

If you require further support I would recommend you join the [discord server.](https://discord.gg/vRuhG9R)

**Comment by CyberDudeJ** [comment]
oki
