### ISSUE TITLE
Force all replies to be "anonymous"

### ISSUE THREAD

**Issue by SuperSajuuk** [Dragory/modmailbot#553]
Currently, in one of the servers I use modmail in, mods are able to send replies either identifiable or anon. However, due to the potential for personal attacks to be made against mods who send identifiable replies, and the fact some mods send anon replies only, a way to make it so that you can force all replies to be anonymous, regardless of them using !reply or !anonreply, would be super useful.

**Comment by teheim** [comment]
https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#alwaysreply

"
alwaysReplyAnon
Default: off
If alwaysReply is enabled, this option controls whether the auto-reply is anonymous
"

**Comment by mesub7** [comment]
We did discuss this in the support server and while it does do the job (slightly), it requires `alwaysReply` to be enabled which isn't useful for conversations between staff members (yes there is !note but people could forget and I believe it can hinder conversation)

**Comment by SuperSajuuk** [comment]
> https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#alwaysreply
> 
> alwaysReplyAnon
> Default: off
> If alwaysReply is enabled, this option controls whether the auto-reply is anonymous

As per mesub7, your idea forces mods to use !note: our mod team is used to just chatting normally in modmail and using commands to communicate with a user only. It would just hinder conversation and confuse our team, and almost certainly responses will be sent that aren't meant to be sent, leading to a poor relationship between mods and users.

**Comment by JetCrooked** [comment]
I wonder if you could set !r to be a command alias of !anonreply (it does !reply by default but maybe that can be overridden with an explicitly defined alias)

**Comment by JetCrooked** [comment]
another idea: turn on useNicknames and give a common nickname to all your mods in your staff server, so that replies from different mods look identical to the user
