### ISSUE TITLE
The bot is not on the inbox server

### ISSUE THREAD

**Issue by Turbinator-JP** [Dragory/modmailbot#560]
I have edited the configs so that the inbox server is the same as the main server using the server ID, however, when I go run the bot I keep getting an error saying 'BotError: The bot is not on the inbox server!'
I don't understand how to fix this

**Comment by mesub7** [comment]
Did you save and restart the bot?

If you require more support, it will be best if you visit the [support discord server.](https://discord.gg/vRuhG9R)
