### ISSUE TITLE
Have the bot respond if @'d

### ISSUE THREAD

**Issue by SuperSajuuk** [Dragory/modmailbot#569]
A common issue I've run into within one of the servers I'm running Modmail on is people not knowing _how_ they're meant to contact the team through the bot. We've had users DM'ing mods individually (and not using Modmail) or people @'ing the bot in chat, thinking that it will make a thread that.

I'd like a way for the bot to respond to "user" pings, ie people who are not considered moderators by the bot, with a message defined in config.ini, saying that they need to send the bot a direct message in order to contact the team. EG "Hi there <user who @'d me>, unfortunately you've pinged me in the chat. To contact the moderation team in private, you need to send me a Direct Message. Just click on my name and type a message into the textbox. If you do not see this option, you need to make sure your DM's are open in this server!"

**Comment by DarkView** [comment]
To reply when the bot is mentioned: https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#botmentionresponse

To open a thread when the bot is mentioned: https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#createthreadonmention

**Comment by SuperSajuuk** [comment]
Didn't know this was a feature already. closing.
