### ISSUE TITLE
Command !move does not work with numbers

### ISSUE THREAD

**Issue by Girtablulu** [Dragory/modmailbot#57]
I gave our categories a number before the name 

> 1 - open
> 2 - in progress
> 3 - and so on....

but sadly the !move command does not work with numbers. If I try **!move #number** the bot throws it into a random category only **!move #name** it works as intended.

and it would be nice if we could use a short command **!m** <category> as well for less typing. (yes I'm lazy)

**Comment by Dragory** [comment]
Hmm, the numbers should definitely work (the "algorithm" it uses to match what you wrote is basically just checking which category name has the longest match for what you wrote). I'll look into this.

Good point about the alias! Everything else has one, so why not this as well.

**Comment by untuned** [comment]
Here's what I did: https://i.untuned.me/DleCdv.png
Doing either `!move 2` or `!move 3` worked fine.

**Comment by Dragory** [comment]
Are you still experiencing this issue?

**Comment by Girtablulu** [comment]
ah no you fixed it :) thanks a lot
