### ISSUE TITLE
[Suggestion] Attempt reconnect after network interruption.

### ISSUE THREAD

**Issue by Mondrethos** [Dragory/modmailbot#571]
Hi,

When the bot servers from any network interruption, the process crashes. It would be preferred if it instead waited and retried over a period of a few minutes at least. If it continues to fail, it should exit cleanly at some point (preferably confirgurable)

**Comment by Dragory** [comment]
The bot currently reconnects automatically on any of the following network errors:

* "CloudFlare WebSocket proxy restarting"
* "Connection reset by peer"
* "ECONNRESET"

Are you experiencing a specific error that isn't automatically reconnecting?

**Comment by crckhub** [comment]
Hello,
I have had frequent issues with Discord API timeouts, so I started using PM2 (a process manager) to automatically restart the bot when it stopped.
You should look into that as well if you are not using it yet, it's very useful as you can monitor and restart the bot from a web browser and the pm2-discord module can send the console output produced by the bot via a Discord webhook straight to a Discord channel.
This fixed my issues with network disconnects / timeouts, maybe it can help you as well if you are not already using PM2
