### ISSUE TITLE
Error EADDRINUSE: Error: listen EADDRINUSE: address already in use :::8890

### ISSUE THREAD

**Issue by StoneMcYT** [Dragory/modmailbot#574]
I got this error when starting my bot

**Comment by Dragory** [comment]
This error means that there is already something else using the port `8890`. If you have other modmail bots running on the same machine, make sure you use a different port for each one (set the `port` config option, e.g. `port = 8891`). Sometimes the bot's process can also get stuck for various reasons and keep the port "in use" - in this case, closing the Node.js process that's stuck should fix the issue (via task manager on Windows, `kill` on linux, etc.).

**Comment by StoneMcYT** [comment]
Thx i see the issue i was running 2 diffrent modmail bots at once as they were using the same port. Again thx
