### ISSUE TITLE
The thing that logd issue isn't working

### ISSUE THREAD

**Issue by omxpro** [Dragory/modmailbot#579]
So what happened is the thing that comes defult with the bot is not working "Modmail thread #1 with OmxproYT#7508 (582515504221126669) was closed automatically because the channel was deleted
Logs: http://136.244.87.209:8890/logs/09daa75b-716b-4a7a-a489-c0ab6ab7485e" the ip with the port is saying this
https://cdn.discordapp.com/attachments/824375311193997364/825403693955284992/unknown.png

**Comment by Dragory** [comment]
You will have to forward the port 8890 to be able to view logs. If you need some help with this, feel free to join the support server: https://discord.gg/vRuhG9R
