### ISSUE TITLE
starting doesnt work!

### ISSUE THREAD

**Issue by Hatekuro** [Dragory/modmailbot#58]
when i type `npm start` after `npm install`
 i have much errors.
 Can you @Dragory help me?
![image](https://user-images.githubusercontent.com/37068047/36974657-b28c1c82-2077-11e8-9e56-0911cb9c4b62.png)

**Comment by Dragory** [comment]
Hey, can you show me what's higher in the console? Before the part you posted.

**Comment by Hatekuro** [comment]
![image](https://user-images.githubusercontent.com/37068047/37253992-6366744c-2539-11e8-9953-077121722a4d.png)
That one error is in Polish: 
> %1 nie jest prawid³ow¹ aplikacj¹ systemu Win32.

> 

InENG: 
> %1 is a incorrect application on system Win32

**Comment by Dragory** [comment]
Hmm, try deleting the `node_modules` folder and then re-running `npm install`.
