### ISSUE TITLE
Suggestion - Change messages to embeds

### ISSUE THREAD

**Issue by ghost** [Dragory/modmailbot#584]
Hello, messages should be changed to embeds. I feel like I'm on Discord compact mode when I'm reading tickets, not fun. 

Simple embeds would go a long way, I'm sure many others would agree.

**Comment by azgoodaz** [comment]
I fully disagree with this. Embeds are horrible and look ugly.

**Comment by Dragory** [comment]
The bot uses a text-only format by default, and this is unlikely to change as many users (including myself) prefer this. There will, however, be an official embed plugin in the future.

**Comment by Eegras** [comment]
@DarkView has made a plugin to support embed messages.  https://github.com/MMPlugins/EmbedMessages
