### ISSUE TITLE
Possible feature request?: Enable use of moderator nickname aliases in modmail threads

### ISSUE THREAD

**Issue by byeuji** [Dragory/modmailbot#605]
Our server is an offshoot of our reddit community, and so I alias my username in our Discord server to match my reddit user ID so users know who I am across platforms. But in modmail, it only lists my base ID.

If there's an option to enable use of aliases/nicknames is available, please let me know. Otherwise, it'd be great to create this as a feature.

Specifically, I'd like *moderator* nicknames to show -- the current behavior or showing a user's full Discord ID (and NOT their alias) is perfect as-is, and I wouldn't want to change that. So if you adopt this feature for both mods and users, I'd prefer if they had individual configuration options.

**Comment by Dragory** [comment]
You can turn this on by setting `useNicknames = on` in your config! See the link below for more details:

https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#usenicknames

**Comment by byeuji** [comment]
You da best
