### ISSUE TITLE
Whats AlwaysMove and how can i enable it?

### ISSUE THREAD

**Issue by clashwithA** [Dragory/modmailbot#61]
Can you help me please. I dont know how to set the always move feature up thanks :)

**Comment by Dragory** [comment]
Always move? Do you mean always reply?

**Comment by Dragory** [comment]
Ah, **allow**Move. Right, if allowMove is set to `true` in config.json, moderators can move threads between channel categories on the inbox server with `!move name` where `name` is the name of the category (or close to it).

**Comment by clashwithA** [comment]
So in Config.Json I should type "Allowmove" (space) "true" is that correct? also when the bot goes offline i can`t reply to the previous open log when its back online again. Is that a bug?

**Comment by clashwithA** [comment]
Weird i dont have a line like that in config.json. 

All i have is this:

{
  "token": "Token",
  "mailGuildId": "Guild id",
  "mainGuildId": "main guild id",
  "logChannelId": "log channel",


  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
}

Also i dont see any errors in cmd but when i shut the bot down and after turning the bot back on i cant reply to messages or do anything.

**Comment by Dragory** [comment]
The bot's data doesn't change between restarts. There's something else you're doing that you're leaving out. Do new threads still work after a restart? Are you manually deleting channels? Also, are you running the newest version of the bot?

**Comment by clashwithA** [comment]
Yes i just upgraded to the new version today. No i dont get the message. yes new threads do work after the restart also im not manually deleting channels .

**Comment by clashwithA** [comment]
Also i cant close channels after restart either. Just tried it out and the issue is still occurring @Dragory 👍

**Comment by Dragory** [comment]
The only way this would be happening is if `db/data.sqlite` was somehow getting reset/overwritten on bot restart. Is there any reason that would be happening?

**Comment by clashwithA** [comment]
After checking the bot files i can`t find a file/folder name db/data.sqlite weird.

**Comment by Dragory** [comment]
If you're running the latest version, there should be a folder called `db` in the bot's folder, with a file called `data.sqlite` inside it.

**Comment by clashwithA** [comment]
i updated the bot again but i still didn`t get a folder named db. Am i doing something wrong?

**Comment by Dragory** [comment]
The bot's download comes with the folder. It should be there regardless. Where are you downloading the bot, and can you take a screenshot of the bot's folder?

**Comment by clashwithA** [comment]
![2018-04-08](https://user-images.githubusercontent.com/27364892/38468607-b4f26790-3b40-11e8-9611-0a39ed85749b.png)

There you go. I typed npm install after removing the node_modules also before that i backed up an copy of the folder (just in case) also after that i typed in npm start

**Comment by Dragory** [comment]
Either you're running an old version of the bot, or you deleted the `db` folder. The folder is included in the download you get from this github page: https://github.com/Dragory/modmailbot/archive/master.zip

**Comment by clashwithA** [comment]
Hey. I deleted node_modules and i typed in npm install and then typed in npm warn and a bunch of words came up then i typed npm update and it changed a few thing but i still haven't got db folder. I haven't deleted anything. I dont know what im doing wrong. Help?

**Comment by Dragory** [comment]
Before doing anything else, download the latest files from https://github.com/Dragory/modmailbot/archive/master.zip

**Comment by clashwithA** [comment]
Hey the db issue is solved. I needed to merge the download with the old one and weird thing is that it updated itself. Also how to i enable allow move in config? Thanks for the help

**Comment by clashwithA** [comment]
![2018-04-10](https://user-images.githubusercontent.com/27364892/38554067-19cd63d0-3cb9-11e8-93b2-8c94bc32b59f.png)

Is this updated correctly? :)

**Comment by Dragory** [comment]
For whatever reason some of the files are still the old, Feb 11 version. Did you extract the *entire* .zip archive over the existing files, or only some of them?

**Comment by sporkwitch** [comment]
To be extra thorough, backing up the db directory, doing a fresh clone, and then pasting back in the db dir seemed to work fine spinning up a new instance today.  The previous instance was the old version and had the issue you're experiencing.  Just tested and it definitely is resolved in the current source.

**Comment by clashwithA** [comment]
I did the existing files @Dragory

**Comment by Dragory** [comment]
I recommend doing what @sporkwitch recommended above:

1. Take a backup of `config.json`, the `db` folder and the `attachments` folder
2. Download a fresh copy of the bot's code and extract it in a completely new folder
3. Place the files/folders from step 1 in the new folder

**Comment by clashwithA** [comment]
just did that. The weird thing is that i dont have a line in config.json where i can write "alwaysmove " and change it to true

**Comment by Dragory** [comment]
That's because you need to add it there yourself - the config doesn't include all options by default, just a few common/required ones.

So, add a new line in `config.json` before the last line, and make it `"allowMove": true`
(Also make sure the line above the one you added has a comma at the end, and that the new line you added does not)

**Comment by clashwithA** [comment]
Thanks. It works now. Awesome support 😃 btw im not making it fully live just yet as it still has a few features which i need to configure to manage all of the 700+ members successfully 👍

**Comment by sporkwitch** [comment]
@clashwithA make sure to close the issue if it's been resolved
