### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by redsk1ns** [Dragory/modmailbot#62]
Great bot! 

i am having trouble with the logs. They aren't on the pc I am hosting on under botfolder/logs-its completely empty. The links aren't working so I'm sure that has something to do with it. NodeJS 8.11.1. Thank you.

**Comment by Dragory** [comment]
Hey! Since the February update, logs are stored in the database file `db/data.sqlite`.

**Comment by redsk1ns** [comment]
Must be a port issue somewhere for showing logs on discord. Will play around with it. Thank you!

**Comment by Dragory** [comment]
Unless there's an error, a screenshot would probably not do much. It's very likely related to port forwarding or a firewall.

**Comment by redsk1ns** [comment]
I'm stuck. Tried on 2 Ubuntu laptops, Windows, swapped routers and on AWS Ubuntu server. I don't get logs/attachments anywhere. Google failed me or I am not searching the right terms. The logs/attachments message/url send but it times out each time. Any other ideas? Sorry to hassle you. Thanks!

**Comment by Dragory** [comment]
Unfortunately, unless there's an error (which would indicate it's an issue with the bot), it could be a lot of things - likely something with port forwarding or a firewall. Make sure to [forward your ports](https://portforward.com/), or if you're using AWS, check their network/security settings (I'm not too familiar with AWS myself).

**Comment by sporkwitch** [comment]
I'd like clarification on what is meant by "not displayed."  Is it not posting the link in the configured log channel?  Are you not able to access the link?  The former would be a Discord permissions issue, the latter most likely firewall or port forwarding.  Just had to set up a new one today and everything seems to work just fine, even set nginx to proxy it so we have TLS.
