### ISSUE TITLE
Temporarly Stop/Autorespond Close Incoming Messages

### ISSUE THREAD

**Issue by JaymeiF** [Dragory/modmailbot#622]
Imagine if you will a sudden influx of around 11k people who all feel like messaging Mod Mail.

Simple Answer - Turn off the bot.
Advanced - Global command to "turn off" incoming DM.
Complex - Accept messages, autorespond and close.

Some/all/none of this may already be available or not going to happen but would be nice to see.

**Comment by DarkView** [comment]
Duplicate of #267
