### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by dakshya2090** [Dragory/modmailbot#623]
Pls share your modmail code on replit.com so that I can run bot 24/7

**Comment by Dragory** [comment]
You can upload and use the bot on repl.it, though we can't offer host-specific support right now.

**Comment by dakshya2090** [comment]
How to upload?

**Comment by Dragory** [comment]
For help setting the bot up on repl, please ask on the support server: https://discord.gg/vRuhG9R
We can't offer host-specific help in the GitHub issues here.

**Comment by dakshya2090** [comment]
I'm already in your server and my username is BLAZEGAMER#1525
