### ISSUE TITLE
Feature request: multi-server support

### ISSUE THREAD

**Issue by sporkwitch** [Dragory/modmailbot#63]
I've never worked with Node or I'd look into just adding it myself (I'm a Python and C guy), but would it be possible to add support for having the bot monitor / join multiple servers, and include in the log thread which server it originated from (or which of the monitored servers the user in question is in, in the case of a DM)?

While It's obviously lightweight, it feels silly to run separate instances per server, even if using the same token.  In terms of settings it seems like it would be simple enough to accept multiple "mainServer" entries, or use an array instead of a string.

**Comment by Dragory** [comment]
The main issue is figuring out what to do if the user is in multiple
servers. Should the bot mark the log as being from *all* of those servers,
or should it ask the user which one they're messaging from?

Technically, the bot already supports multiple servers - it just doesn't
show the origin anywhere.

**Comment by Dragory** [comment]
The main issue is figuring out what to do if the user is in multiple servers. Should the bot mark the log as being from *all* of those servers, or should it ask the user which one they're messaging from? That ambiguousness has been the main reason I haven't implemented proper multi-server support yet (though technically, the bot *does* support multiple servers - it just doesn't show the origin anywhere).

**Comment by Dragory** [comment]
Something like this should definitely be possible. I haven't implemented proper multi-server support yet because it can be ambiguous which server the user is messaging from (if they're in multiple ones), but I suppose it's not an issue if it's directed to the same modteam anyway.

**Comment by sporkwitch** [comment]
Yup, the only things I see being necessary would be having it list which servers they're in from the monitored list, and allowing multiple mainGuildId for reacting to [at]mentions.  Easy enough to add "please say which server this is in regard to" in the auto-reply when they first PM it.

* Accept multiple "mainGuildId" in settings
* Specify origin server when reporting [at]mention of the bot
* List mutual servers in ticket open

I think those three would cover all that's actually needed, without significant headache or overcomplicated changes.  Presumably the bot is only joined to the servers that team is monitoring, so listing mutual would give you the info needed, and if they're on multiple, can just set the autoreply to have them say which it's for (we already have a message pointing people to official support for in-game issues and pointing out we just handle the discord).

That actually does remind me of another useful feature: allowing the person that messaged the bot to close the ticket themselves.  Since adding that message we get a fair few "hi"s and if we do reply it's "nevermind, didn't know what it was for"; if they could close their own tickets, it'd save the trouble of closing the ones opened in error.

**Comment by Dragory** [comment]
For the last paragraph, take a look at the `ignoreAccidentalThreads` option. It ignores common "accidental" thread-starters such as "hi", "thanks", etc.

That being said, it should be easy enough to add a !close command for the users as well, though probably disabled by default. You could then inform the users about the command in the auto-reply.

**Comment by sporkwitch** [comment]
Already had that one enabled to deal with those ones, where it comes up is "some jerk is cheating on [server]" to which the autoreply covers it with "we're only the discord guys, go to [official support url for game] for in-game issues".  A lot of times they don't say anything after, would be nice if they could self-close to save us the trouble.

But yep, I think we're definitely on the same page.  I'd do it myself and submit a pull request, but i've never worked with node, like i said; port it to python and we can talk :P

**Comment by Dragory** [comment]
Hey! I added support for this in **2.9.0**. Can you see if it works for you?

Also, thank you for helping out with the issues in this repository! I really appreciate it!

**Comment by Dragory** [comment]
The [WARN] would indicate there's only one main guild. If you used the format you mentioned there, try `["id1", "id2"]` instead!

**Comment by sporkwitch** [comment]
These result in the warning on mentions:
1) `"mainGuildId": "1234,5678",`
2) `"mainGuildId": "1234, 5678",`
3) `"mainGuildId": "1234",`
`"mainGuildId": "4567",`

This results in a crash on npm start:
"mainGuildId": "1234", "5678",

No form, with either only one or multiple main ids, are generating entries for [at]mentions of the bot

**Comment by sporkwitch** [comment]
So I derped and those brackets are how you specify an array in JSON; entering it that way resolves both the warnings on mentions, and it now shows member servers and local nicknames in the thread creation message.

It is still not logging mentions in member servers, though.

**Comment by Dragory** [comment]
Oh yes, that is true, the bot ignores mentions from people in the inbox server!
Also, in regards to JSON comments, I'm planning on switching the config parser to [JSON5](https://github.com/json5/json5) which, among other things, supports commas!

**Comment by sporkwitch** [comment]
Comments, you mean? :P  And glorious!

**Comment by Dragory** [comment]
Oops, yes, comments* 😛

**Comment by sporkwitch** [comment]
The missing comma was derpy on my part; I just nuked the branch and pull request.  I can't think of a way to describe it in the readme that wouldn't just be more confusing; best to just wait until the switch to JSON5 and put a commented-out example in the single example config, as is normal for these kinds of things.
