### ISSUE TITLE
`loglink` doesn't work in suspended threads

### ISSUE THREAD

**Issue by wasdennnoch** [Dragory/modmailbot#632]
Currently, you have to `unsuspend`, `loglink` and `suspend` a thread to get the link. This issue seems to have once been fixed in v2.19.0, but I guess it's been broken again in v3.

Having a quick look at the code, it seems that `loglink` only works in either open threads or when providing the thread ID - which you usually don't know unless you call `loglink`.

Using v3.3.2.

**Comment by mesub7** [comment]
Hello. 

I would say this isn't a bug. 

Suspending a thread means that it is 'frozen in time', so no commands (apart from `unsuspend` work).

**Comment by JetCrooked** [comment]
just because it's not a bug doesn't mean it shouldn't be changed though? being able to use !loglink in a suspended thread would be better than not being able to use it ¯\_(ツ)_/¯

**Comment by DarkView** [comment]
Funilly enough if you know the Thread ID or number the command will work in suspended threads.
This is to do with the `_thread` object not being passed to the command if used from a suspended thread
![3094-DiscordCanary-1627356018](https://user-images.githubusercontent.com/7890309/127090091-f06ef04e-5fc0-4db4-8e87-8272a3ada093.png)
