### ISSUE TITLE
Content must be 2000 or fewer in length (Bug)

### ISSUE THREAD

**Issue by Hector1801** [Dragory/modmailbot#633]
If you request the bot to send a preview of a snippet that contains more than 2000 characters (or even the **!snippets** command if it has more than 2000 characters) **outside** a ticket, the bot will crash and it'll display this in the console?
https://cdn.discordapp.com/attachments/621406922175676417/858883116790054912/unknown.png

It should not be a problem as Discord increased the limit to 4000 characters recently, and, in any case, it should split the message into more parts, just as it does when you run those commands inside a ticket (because yes, inside tickets it's someway fixed and works as intended).

**Comment by SuperSajuuk** [comment]
Bots can’t use the 4000 character limit.

**Comment by Hector1801** [comment]
Oh, I see. Anyway it's still a bug. The bot should still split the message into more parts, just as it does inside tickets.

**Comment by melihteke** [comment]
is there any way for workaround ? 
Is there a way to get more than 2000 ?

**Comment by mesub7** [comment]
You could probably make a new issue requesting that the bot automatically splits content longer than the 2000-character limit into multiple messages.
