### ISSUE TITLE
Replit Logs Issue

### ISSUE THREAD

**Issue by Thisisnotharry** [Dragory/modmailbot#635]
I host the modmail bot on Repl.it, and everything works smoothly, apart from the logs.

I don't see any way to change the default URL of the logs, it just sends something such as **(random-IP-here)/logs/(log-id)**
I would like to know if there is a way I can change the **(random-IP-here)** to the repl hosting link _- or any link for that matter -_ as I have found manually changing the IP to the repl link in the address bar fixes this issue, but is a bit of a pain.

Help would be appreciated. I apologise if I am asking this in the wrong place but I am new to this.

**Comment by Dragory** [comment]
You can use the [`url` option](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#url) to configure what's shown instead of **(random-IP-here)**! For example:

```
url = http://myproject.myusername.repl.it
```
