### ISSUE TITLE
Bot Crashes Every Day or Two

### ISSUE THREAD

**Issue by Ragnarok345** [Dragory/modmailbot#64]
So I run the bot 24/7 on my Mac Mini that I have on permanently, and every couple days or so, the bot just randomly crashes. No idea why. I've got I have a picture of the crash below, and I know, it says to update, which is why I've included what happens when I do that, too. It tells me to run as an administrator, but I'm the only administrator on the computer.
<img width="499" alt="crash" src="https://user-images.githubusercontent.com/10534873/38947868-e05ee00c-42f2-11e8-898e-ba24ec30b2a7.png">
<img width="500" alt="update" src="https://user-images.githubusercontent.com/10534873/38947872-e67c2ab2-42f2-11e8-8b69-347c880373dd.png">

EDIT: I've got it updated now. _Totally_ forgot about sudo. Time will now tell if it stops crashing. Apologies if this wastes anyone's time.

**Comment by sporkwitch** [comment]
Make sure you're using the latest version; if you originally installed before mid-February, you'll need to nuke the ./src folder, at minimum (you can really nuke everything but config.json, ./attachments, and ./db).  Back that stuff up, do a fresh clone, restore the backups.

**Comment by Dragory** [comment]
The error, ECONNRESET, looks like an issue of some sort with your connection and/or the Discord API. I would recommend running the bot with something that auto-restarts it, such as foreverjs or pm2.
