### ISSUE TITLE
Transfer reactions

### ISSUE THREAD

**Issue by NoodlesDev987** [Dragory/modmailbot#640]
When user reacts on message sent from bot in dms, react on that message on modmail Discord server and the same when staff reacts on message sent in modmail thread channel, react to the message in user's dms.

**Comment by DarkView** [comment]
This would only work partially.
The bot cannot reacto to messages with emoji from servers that it is not on, so any custom emoji would fail to be added.

**Comment by NoodlesDev987** [comment]
So don't do this for custom emojis that are not from servers where bot is.
