### ISSUE TITLE
Allow other roles to reply

### ISSUE THREAD

**Issue by Legendaryteam-29** [Dragory/modmailbot#647]
Hi, 
I'm trying to add roles that can respond to threads but can't find an extension for that.
Can someone help me ?

**Comment by Mr-dot-cmd** [comment]
You can add another role by adding [] at the end of inboxServerPermission and you will have multiple role that can reply to thread
example:
inboxServerPermission[] = <role_id>
inboxServerPermission[] = <role_id>
