### ISSUE TITLE
TypingProxy Works, TypingProxyReverse Does Not

### ISSUE THREAD

**Issue by Ragnarok345** [Dragory/modmailbot#65]
As the title says. I realize this is probably my issue, not the bot's, but I need help nonetheless. I want both of these on, but when I add TypingProxyReverse to the json, the bot can't launch anymore. This is the effect I get. Also happens with relaySmallAttachmentsasAttachments. 
<img width="498" alt="screen shot 2018-04-18 at 10 57 13 am" src="https://user-images.githubusercontent.com/10534873/38949513-7317bea6-42f7-11e8-9aa7-e9a68772e1da.png">

Any help appreciated.

**Comment by Dragory** [comment]
Make sure the second-to-last line in config.json (i.e. the line before `}`) doesn't have a comma at the end.

**Comment by Ragnarok345** [comment]
Oh, you're kidding. Let me try it. Thank you!

**Comment by Ragnarok345** [comment]
Ok, I changed that, and now I get this.
<img width="499" alt="screen shot 2018-04-18 at 11 09 38 am" src="https://user-images.githubusercontent.com/10534873/38950019-14f593be-42f9-11e8-9335-8d859f012867.png">

**Comment by sporkwitch** [comment]
It would help if you put your config.json in a gist; make sure the redact the actual values for token, guild, and channel id.

**Comment by Ragnarok345** [comment]
{ "token": "token",  "mailGuildId": "Guild",  "mainGuildId": "Guild",  "logChannelId": "Guild",  "status": "Verify with me!",  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible.", "prefix": ".",  "alwaysReply": "true",  "ignoreAccidentalThreads": "true",  "typingProxy": "true", "typingProxyReverse": "true", "relaySmallAttachmentsAsAttachments": "true" }

**Comment by sporkwitch** [comment]
That's not a gist; please use the code tags to preserve formatting if putting stuff like that in-line lol

**Comment by Ragnarok345** [comment]
`{ "token": "token", "mailGuildId": "Guild", "mainGuildId": "Guild", "logChannelId": "Log", "status": "Verify with me!", "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible.", "prefix": ".", "alwaysReply": "true", "ignoreAccidentalThreads": "true", "typingProxy": "true", "typingProxyReverse": "true", "relaySmallAttachmentsAsAttachments": "true" }`
I'm _extremely_ unexperienced with GitHub, so I hope that's what you mean.

**Comment by sporkwitch** [comment]
@Ragnarok345 Make sure to close the issue if it's resolved :)
