### ISSUE TITLE
Suggestion: Preset command sequence from the main server to automatically send snippets

### ISSUE THREAD

**Issue by randomhuman9** [Dragory/modmailbot#664]
Sometimes there is a need to send a member some information which is saved as a ModMail snippet. For example, a member with suicidal or self harm tendencies may be sent a suicide helpline snippet. It's not always appropriate to do that in the chat and end up highlighting the member or having a huge snippet in the chat. To do this a mod would have to -
1. Grab the user id
2. Switch to the ModMail server
3. Start a new thread 
4. Send the snippet
5. Close/Put a timed close

A shortcut feature for all the above could be a simple command that can be initiated from the main server. For example -
!modmail <userid> <snippet name> <close timer>
This would make the bot follow steps 3-5 in the ModMail server.

**Comment by DarkView** [comment]
Extends #110
