### ISSUE TITLE
Suggestions: see list

### ISSUE THREAD

**Issue by toril940** [Dragory/modmailbot#668]
Add command !info (used in thread gives info of the user who opened the thread) should give:
- Basic info like from zeppelin
- Username _and_ current nickname at the time of fetch from the command.
- Current avatar as well as server avatar from the main server for the user (can separate into !avatar) command.
- Custom statuses (as well as bios, unless we can't request those from the API yet).

Add integration with zep so you can bring up cases from the main server for the user with !cases through modmail.

**Comment by isaacKenyon** [comment]
this can be done by [using a bot token (doesnt matter, just has to be valid) to call /api/users/|D (HTTP GET)](https://github.com/nerrixDE/discordid-wiki/discussions/40#discussioncomment-1392919)
