### ISSUE TITLE
Greeting Crash

### ISSUE THREAD

**Issue by FlashSkyNews** [Dragory/modmailbot#67]
If the bot tries to send a DM to new users who don't have it active, the bot crashes.
`root@DiscordBots:/home/ModMails/Papaplatte# npm start

> modmailbot@2.8.0 start /home/ModMails/Papaplatte
> node src/index.js

Lade Module...
Versuche verbindung mit den DiscordAPP Servern aufzubauen...
Verbunden mit den DiscordAPP Server
Starte DM logging...
DM Loggins wurde gestartet!
Warte auf DMs!
Error: DiscordRESTError [50007]: Cannot send messages to this user
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@2.8.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@2.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-19T18_41_31_385Z-debug.log`

**Comment by Dragory** [comment]
Good catch! I'll update the bot to handle errors properly when sending greeting DMs. I'll update this issue once I've released the fix.
