### ISSUE TITLE
bot can't handle long period thread

### ISSUE THREAD

**Issue by Tali13** [Dragory/modmailbot#677]
i have a server set it up but it can't handle the mail for too long if i let it over 2 day bot can't interact with that thread channel anymore

**Comment by kyle-wordpress** [comment]
What host are you using? If you are using replit, heroku yet it is nonstandard as the database resets. You need to switch over or keep it up for 24/7.

**Comment by Tali13** [comment]
im using replit you khow to to keep it up 24/7 or just point a uptime ping it very second
