### ISSUE TITLE
Bot can't start a new thread (or even reply to an existing thread) if your DM are closed

### ISSUE THREAD

**Issue by jben7** [Dragory/modmailbot#679]
Recently, my Discord DM were closed and my support team couldn't start a new thread. I think that it's the same issue to reply to an existing thread.

**Comment by sethwv** [comment]
This isn't something that the bot has any control over but rather a limitation of the privacy & security settings - bots can't send friend requests to circumvent this like normal users can.

If your dms are closed, they're closed. It works the same with regular users.

**Comment by jben7** [comment]
oh okay thanks for your reply
