### ISSUE TITLE
Allow users to right click on a message to report

### ISSUE THREAD

**Issue by duendwang** [Dragory/modmailbot#683]
Using menus, allow users to right click on a message to report that message to moderators rather than needing to DM the bot. This allows users to close their DMs and still report messages. This would be in addition to and not replacing existing bot usage.

**Comment by Deauthorized** [comment]
I actually made a plugin which does exactly that, unfortunately it requires an updated version of eris, which due to some issues prevents the bot from receiving DMs from any user.

**Comment by Deauthorized** [comment]
Nvm, I managed to fix the issue by replacing line 145 in main.js with `if (msg.channel instanceof Eris.GuildChannel) return;`

**Comment by DarkView** [comment]
Menus, slash commands etc. will be "unlocked" once the bot's eris version is updated. 
With the next update (arriving before April 31st) the eris version will be updated and plugins can do stuff like this :)
Having this as a core feature is within the realms of possibility, but will take longer. So using a plugin at first and then later switching would make sense.
