### ISSUE TITLE
[REQUEST] Allow "customers" to use !close

### ISSUE THREAD

**Issue by sporkwitch** [Dragory/modmailbot#69]
Allow the "customers" DMing the bot to close their own ticket with !close

Would reduce admin overhead closing tickets that slip through the "ignoreAccidental" cracks

**Comment by JustxMeg** [comment]
I agree with this.

**Comment by iilukas** [comment]
Any update on this? @dragory

**Comment by Dragory** [comment]
Added in v2.17.0 as `allowUserClose` option. The command will provide no feedback to the user unless `closeMessage` is also set, but the thread will be closed regardless.

**Comment by sporkwitch** [comment]
Thanks! 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes
