### ISSUE TITLE
Add a config option which attaches a pre-configured message to all new threads.

### ISSUE THREAD

**Issue by Deauthorized** [Dragory/modmailbot#690]
Basically, whatever text that is in the `threadHeaderMoTD` variable would be attached to the bottom of the thread header in all new threads.

This would be useful in cases where there are plugins which add additional commands, or if there is information that is important enough where it should be attached to the top of each new thread.

**Comment by DarkView** [comment]
While I like this idea, I think allowing users to fully customize the headers in the first place would accomplish this *and more*, like changing the whole formatting, or translating it.
If anyone does want to work on this, they should look into making it fully customizable instead.

**Comment by DarkView** [comment]
Merged into #656
