### ISSUE TITLE
Suggestion: A config option that automatically makes all replies anonymous 

### ISSUE THREAD

**Issue by Ibotmealot** [Dragory/modmailbot#698]
A config option that makes all replies (using the reply command) anonymous would be useful, currently no such feature exists besides **alwaysReplyAnon** but that is for all messages sent. This would also include making all snippets anon even if you use the normal snippet prefix.

**Comment by Ibotmealot** [comment]
> I have a fork that does this, but a config would have saved me some time, haha
> 
> In my fork, both the Mod messages and the User messages are anonymous.

Yeah you'd have to edit the source to do this (which I've done in the past) but every update you'll have to keep in mind to make the change, so this is just a small qol thing.

**Comment by veerjd** [comment]
Sure, though it just makes it super unlikely that I update at all

**Comment by veerjd** [comment]
@DarkView Is that a thing now for real?

**Comment by mesub7** [comment]
> @DarkView Is that a thing now for real?

Yes, otherwise we wouldn't have closed the issue. 

See the configuration option [`forceAnon`](https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#forceanon) for more information.
