### ISSUE TITLE
Snippet issue

### ISSUE THREAD

**Issue by CodeBuddyUltra** [Dragory/modmailbot#700]
!s Hi, Our staff member has received your thread and your problem will be resolved shortly
Devil Modmail
BOT
 — Today at 10:56 AM
Snippet "Hi," created!

!r {{Hi}}
Devil Modmail
BOT
 — Today at 11:10 AM
The following snippets used in the reply do not exist:
Hi

**Comment by DarkView** [comment]
The snippet you created is called "Hi,"
"Snippet **"Hi,"** created!"

**Comment by CodeBuddyUltra** [comment]
Understood
