### ISSUE TITLE
Greeting is not being sent.

### ISSUE THREAD

**Issue by FlashSkyNews** [Dragory/modmailbot#71]
![2018-04-28_21-31-18](https://user-images.githubusercontent.com/24974529/39400177-9c42a4f8-4b2b-11e8-84c5-3224a479da66.gif)

Token Changed btw xd

**Comment by Dragory** [comment]
Hmm, that's a weird one. So it worked at some point and suddenly stopped working? Did anything change?

*Also, side note - even though it probably won't fix this, use `true` instead of `"true"` in the config*

**Comment by FlashSkyNews** [comment]
Yeah, it worked, and then suddenly it stopped working. And strangely enough, I haven't changed anything. I have reinstalled it several times...

**Comment by FlashSkyNews** [comment]
![discord_2018-04-29_12-14-42](https://user-images.githubusercontent.com/24974529/39405646-dc123030-4ba8-11e8-9abb-04639479213f.png)
![discordcanary_2018-04-29_12-14-11](https://user-images.githubusercontent.com/24974529/39405647-dc2a3888-4ba8-11e8-95fb-7135fc13752a.png)
![2018-04-29_12-13-56](https://user-images.githubusercontent.com/24974529/39405649-dc3fef2a-4ba8-11e8-80c0-268e8e44d14b.png)

**Comment by sporkwitch** [comment]
Is this the main or the mail guild? Greetings are not sent for the mail guild. I believe you would also need to have greetings enabled on the server itself, and the bot would need to be able to read that channel.

**Comment by Dragory** [comment]
It appears he has both set to the same guild at the moment @sporkwitch, which should work fine. The server doesn't need to have greetings enabled either - the bot gets the join event directly from the API, no need for scraping welcome messages.

That being said - @FlashSkyNews can you also check the server-specific privacy settings for your test user? Click on the server name, and then "Privacy Settings". It should look like this:
![image](https://user-images.githubusercontent.com/2606411/39405878-4f6e0768-4bb6-11e8-9b39-dd4eadd73dd4.png)

**Comment by FlashSkyNews** [comment]
For the test to make sure it's not a main server problem, I currently used the mail ID.

**Comment by FlashSkyNews** [comment]
![discord_2018-04-29_14-42-29](https://user-images.githubusercontent.com/24974529/39406717-91ed39b0-4bbb-11e8-868e-0199ee0fd2b6.png)

**Comment by Dragory** [comment]
Okay, try removing line 19 in `src/modules/greeting.js` and try again. If it gives an error in the console this time, we know it's something related to privacy settings/blocking/etc. (just gotta figure out what, then). If not, well, then we gotta try something else.

**Comment by FlashSkyNews** [comment]
[https://img.flashsky.de/2018-04-30_23-01-43.gif](url)

**Comment by Dragory** [comment]
What if you change line 15 in `greeting.js` from
`if (! channel) return;`
to
`if (! channel) return console.log('Could not get DM channel');`
And then try again?

If that doesn't give you "Could not get DM channel" in console when the greeting is supposed to be sent, can you try with a new, different bot user?

**Comment by FlashSkyNews** [comment]
Sure, i'll do it today. But now i go to sleep

**Comment by FlashSkyNews** [comment]
Oh sorry, i forgot to respond. 
No respond
https://i.imgur.com/jvAltOi.png

**Comment by Dragory** [comment]
What if you change the response message to something else, such as "Hello"?

**Comment by FlashSkyNews** [comment]
![discordptb_2018-05-03_20-43-16](https://user-images.githubusercontent.com/24974529/39596448-a922ec1a-4f12-11e8-8f94-e74d3022edf1.png)
nope...

**Comment by FlashSkyNews** [comment]
Permission are fixed.

**Comment by Dragory** [comment]
Could you put your `main.js` and `modules/greeting.js` on https://gist.github.com/ and link them here? I'm really not sure what it could be at this point.

**Comment by FlashSkyNews** [comment]
main.js: https://gist.github.com/81dbe5ddf3f1450b96c63207e2725c8f
greeting.js: https://gist.github.com/a3cae845261f7cb1098743a93d3840b0

**Comment by FlashSkyNews** [comment]
,

**Comment by FlashSkyNews** [comment]
> EDIT: Also, does the greeting work for anyone else?

Nope...

**Comment by Dragory** [comment]
I'm out of ideas. There are no errors, config looks fine, code looks fine, and it works elsewhere. At this point I'd like to remote in and have a look myself, if you'd be fine with that.

**Comment by FlashSkyNews** [comment]
kk

**Comment by Dragory** [comment]
Update: I may have figured out the bug here. It seems I broke greetings when adding multi-server support a few updates back. I should have a fix very soon.

**Comment by Dragory** [comment]
Okay, I've released v2.11.1 which should fix this issue. Can you give it a try?

**Comment by FlashSkyNews** [comment]
sure.....
