### ISSUE TITLE
How do you update again?

### ISSUE THREAD

**Issue by Ragnarok345** [Dragory/modmailbot#73]
It was telling me to update, including how, but the tab got closed before I could do it, and now the bot has crashed twice in the last couple hours. I think it's something like sudo npm i -g npm but I don't remember for sure, and that command isn't working.

**Comment by Dragory** [comment]
This is unrelated to modmail. The message you got was from `npm`, the package manager for Node, and running the command is not required for modmail to function.

If you're experiencing crashes, please make a separate issue for those with the error messages you're getting.
