### ISSUE TITLE
How to setup logs

### ISSUE THREAD

**Issue by L11K** [Dragory/modmailbot#75]
Is this correct?
![image](https://user-images.githubusercontent.com/18279534/39897337-39805142-5488-11e8-88d1-20b58c602fc8.png)
because if it is, I'm missing something. 
config.json
```
{
  "token": "token",
  "mailGuildId": "ID",
  "mainGuildId": ["ID","ID"],
  "logChannelId": "ID",
  "prefix":"!",
  "newThreadCategoryId":"ID",
  "typingProxy":"true",
  "ignoreAccidentalThreads":"true",
  "threadTimestamps":"true",
  "allowMove":"true",
  "relaySmallAttachmentsAsAttachments":"true",
  "port":"8890",

  "status": "Police",
  "responseMessage": "message."
}
```

I checked all the issues here and nothing. 

I am using glitch.com, so if I set the project URL (project URL = project IP) it gives me ```Cannot GET /logs/<logs>```

Sorry if I am missing something obvious and you just wasted your time, but regardless, thanks.

Also:

I'm very excited for the features in ```TODO```
-Add option for minimum time on server for contacting modmail
-Add option for minimum account age for contacting modmail

plus if you could add a minimum characters amount for the bot to create a new thread, it would be very useful.

**Comment by sporkwitch** [comment]
@L11K There's already a setting for ignoring accidental thread creation, have you tried that yet?

As to the issue, what do you mean about glitch.com?  They're hosting an instance of the bot for you?

The default behaviour of the bot is to generate a link with the IP of the listening interface (in this case 34.229.183.29 on port 8890) then the paths are /logs/logid and /attachments/attachmentid

If 34.229.183.29 isn't publicly accessible or doesn't have 8890 open or proxied you won't be able to access logs or attachments.
