### ISSUE TITLE
Error trying to startup

### ISSUE THREAD

**Issue by BasselTube** [Dragory/modmailbot#76]
#I get this error when i try to run "npm start"
C:\Users\ASUS\Desktop\modmailbot-master\src\data\Thread.js:299
      ...data
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\ASUS\Desktop\modmailbot-master\src\data\threads.js:11:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)

**Comment by BasselTube** [comment]
OK, i'll try and update you, thanks for the reply.

**Comment by BasselTube** [comment]
It's worse after upgrading, now when i try to run npm install i get this error: 

npm install
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ASUS\Desktop\modmailbot-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\ASUS\Desktop\modmailbot-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)

**Comment by BasselTube** [comment]
I updated now i keep getting this error while trying to run npm install:

npm install
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ASUS\Desktop\modmailbot-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\ASUS\Desktop\modmailbot-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)

**Comment by BasselTube** [comment]
Thanks, it worked! but i want to set alwaysReply to true and alwaysReplyAnon to true, how do i properly type it in config?

**Comment by Dragory** [comment]
You would add them after the line already in the config like so:

```json
{
  "token": "your bot token",
  "mailGuildId": "id of the modmail inbox server",
  "mainGuildId": "id of the main server where users will DM the bot",
  "logChannelId": "id of the channel on the inbox server where notifications of new logs etc. will be posted",

  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible.",

  "alwaysReply": true,
  "alwaysReplyAnon": true
}```

(Note the added comma at the end of the responseMessage line)

**Comment by BasselTube** [comment]
Thank you, i like your bot so much, cya!
