### ISSUE TITLE
Suggestion: Regex Replies

### ISSUE THREAD

**Issue by randomhuman9** [Dragory/modmailbot#770]
Being able to set multiple regex with corresponding reply texts so that if the message to the bot matches the regex it will send the corresponding text as auto reply.

- Regex matches should be limited to the first message to the bot and the reply upon match in this case should replace the standard auto reply so that it does not interfere when a modmail is being handled by a moderator
- Maybe the second message immediately after bot auto reply can be matched too since people sometimes send only 'hi' or '.' as their first message
- Regex corresponding replies could be set to snippet names so that you could simply make a snippet and use it manually or have it auto reply. Snippets are also easier to update any time.

**Comment by DarkView** [comment]
Extends #357
