### ISSUE TITLE
Automatically reconnect after connection is interrupted instead of crashing

### ISSUE THREAD

**Issue by JetCrooked** [Dragory/modmailbot#775]
Currently, if the bot's network connection is interrupted for any reason, it crashes and the terminal window shows the "press any key to continue..." which closes it, forcing you to restart the bot yourself. What the bot should instead do is periodically attempt to reconnect, like the Discord client for example does when losing connection, until it successfully reconnects and is therefore back up and running without any action required from the bot owner.

**Comment by mesub7** [comment]
Using a process manager to avoid this is encouraged. This is one reason why the repository [contains a configuration file](https://github.com/Dragory/modmailbot/blob/master/modmailbot-pm2.json) for your use.

You are always free to use alternative process managers if PM2 is not to your liking.

**Comment by JetCrooked** [comment]
Using a process manager is good advice for VPS use for sure, but my post was more so aimed at running the bot on a PC

**Comment by wrac4242** [comment]
Running the bot on a PC is not recommended due to often there being restarts and potential issues with downtime. there is a list of good free-tier VPSs on the support server that I will be happy to get for you if you want

**Comment by DarkView** [comment]
The bot already reconnects on connection issues [as you can see here](https://github.com/Dragory/modmailbot/blob/0e9bf7e93f97070e78e046ac6948d8f8c02a4627/src/bot.js#L32).
If you have a specific error message to add to the ignore list, please make a new issue with that specific information.
