### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DonaldDumq** [Dragory/modmailbot#79]
motivate

**Comment by sporkwitch** [comment]
No setup is needed, it'll link you the logs in the inbox server.  You might need to open 8890 on the firewall, that's it.

**Comment by DonaldDumq** [comment]
So I can't make my own logs?

**Comment by sporkwitch** [comment]
It's unclear what you're trying to do.  The bot logs the tickets and provides a link for you.

**Comment by DonaldDumq** [comment]
Hello, can I use heroku with this?

**Comment by sporkwitch** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by DonaldDumq** [comment]
I have checked and no help

**Comment by DonaldDumq** [comment]
Hello?

**Comment by Dragory** [comment]
Sorry, I can't offer support for specific hosting platforms. The installation instructions, apart from platform-specific differences, should be the same. That being said, check out issue #74 for some Heroku-specific troubleshooting.

**Comment by DonaldDumq** [comment]
But is there anyway I could do logs on my own server? 165.227.55.25 I'm not allowed to touch the router

**Comment by DonaldDumq** [comment]
Also what can I do instead of NPM Start bc i need to run it as a background process i use pm2

**Comment by DonaldDumq** [comment]
![image](https://user-images.githubusercontent.com/31372877/40434886-61f6f384-5e7d-11e8-9fb4-e7b6f8b92df6.png)

**Comment by sporkwitch** [comment]
Error message answers itself.

**Comment by DonaldDumq** [comment]
I tried that doesn't work. Category does exist.

**Comment by sporkwitch** [comment]
Screenshot the server channel list, paste your config file

**Comment by DonaldDumq** [comment]
![image](https://user-images.githubusercontent.com/31372877/40435662-2884ef46-5e7f-11e8-8c69-bdf7181ae777.png)

**Comment by DonaldDumq** [comment]
Still having problems for some reason.
