### ISSUE TITLE
CRITICAL: TOKEN must be set

### ISSUE THREAD

**Issue by KoreyMiracle** [Dragory/modmailbot#794]
I genuinely cannot figure out why I keep getting this CRITICAL error. Says TOKEN must be set? 

![CRITICAL](https://github.com/Dragory/modmailbot/assets/150237532/d10da794-18e7-4142-92cd-583d6f9e8670)

**Comment by nin0-dev** [comment]
you aren't on the right bot repo, you're likely looking for [that one](https://github.com/modmail-dev/Modmail)

**Comment by KoreyMiracle** [comment]
> nin0

Oof, my bad. Thank you!
