### ISSUE TITLE
!blocklist 

### ISSUE THREAD

**Issue by Pearl8520** [Dragory/modmailbot#798]
Would be nice to have a command to view all the users that are blocked from messaging the bot

**Comment by Akinator31** [comment]
I added it in my last pull request. You can get the code to use it because I don't think the pull request will be accepted quickly.

[Pull request](https://github.com/Dragory/modmailbot/pull/799)

**Comment by Pearl8520** [comment]
Epic ty

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Pearl8520** [comment]
!blocked doesnt work despite adding the code

**Comment by Pearl8520** [comment]
What's your discord username btw? That way I can contact you directly on discord rather than here on GitHub just so I can close this repo
