### ISSUE TITLE
For people that don't regularly use github, could the readme be slightly more detailed.

### ISSUE THREAD

**Issue by Sen10el** [Dragory/modmailbot#8]
I'm having trouble using the Github desktop application, so I resorted to just copying the file into my documents folder.. But I am stuck on what "Install dependencies: npm install" is asking to do... I've tried putting that into the CMD, but it gives me this list of errors:

```
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
```

So when I attempt to run the bot, it just doesn't work, giving me this error:

```
module.js:471

    throw err;
    ^

Error: Cannot find module 'C:\Windows\system32\src\index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

I know I'm doing something wrong, but I'm just lost. I thought it would be easier to grasp than what I can at the moment.

**Comment by Dragory** [comment]
Hey! You're right, the instructions in the README are currently aimed at people who are already experienced with git and the command line in general.

In this case the issue seems to be that your `cmd` is opened in the system32 folder (the default) instead of the bot's folder. You can easily open cmd in the bot's folder by opening the bot's folder in the file manager, shift+right clicking the background, and clicking "Open command window here" (or, in newer Windows 10 updates, "Open PowerShell window here"). Picture: http://i.imgur.com/5aMBQea.png

**Comment by Sen10el** [comment]
Thank you a ton for responding as quickly as you did. Unfortunately I've still been running into problems :(

The problems that I'm running into now seems to be as described below when I run `npm install` in the proper command line..
```
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\Nick\Documents\modmailbot-master\npm-debug.log
```

I've downloaded git, but I don't know how to verify that it is on the right path or if I have the right setting on. I would share the contents of the npm-debug.log, but I'm not positive what information could be taken from that so unless github has a private message feature that'll go untouched.

**Comment by Dragory** [comment]
Make sure you restart explorer + cmd after installing Git. Also, when installing Git, make sure the "add Git to PATH" option is checked during the install.

The installation process shouldn't require Git; it's something I've been meaning to fix. But for now, check the above stuff.

**Comment by Sen10el** [comment]
Everything started working once I redid the Git installation, adding it to the PATH correctly. One (probably last) speedbump is when i try to DM the bot to test it out, it'll blurt out this error message in the CMD:
```
[ERROR] Modmail channel for Nick#2659 could not be created:
Cannot read property 'createChannel' of undefined
(node:12264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'id' of undefined
```
I apologize for all of these questions, I just love the idea of the bot and think it's fantastic and I'm eager to get it up and running on a few of my servers!
Thank you again

**Comment by Dragory** [comment]
Make sure `mailGuildId` is set in config.json (set it to the ID of the inbox server; to get the id, enable "Developer Mode" in Discord appearance settings, right click the server in the sidebar, and click "Copy ID". Enclose it in double quotes in the config file).
