### ISSUE TITLE
Pre-made for Modmail

### ISSUE THREAD

**Issue by Sunburnnk** [Dragory/modmailbot#813]
Hello, I would like to propose an idea for Modmail, I don't know if it already exists but I propose it to you anyway: it would be the possibility of using "pre-made" messages like Zeppelin when using tags, let me explain: Sometimes we end up with tickets for certain servers for the same reason, and I'm tired of repeating myself for people who open a ticket for the same reason, the goal would be to have the possibility of being able to type a personalized command (like tags with Zeppelin) which would allow Modmail to directly send a message to the person already freshly prepared, for example instead of doing: !r (as a base prefix) I would put !rTest to directly send a message already made by me with Modmail (this should only work if the "alwaysReplyAnon or alwaysReply" plugins are disabled) unless there is an alternative to this

**Comment by DarkView** [comment]
This exact feature is listed in the main README.
It was pretty easy to find ;)
https://github.com/Dragory/modmailbot/blob/master/docs/snippets.md
