### ISSUE TITLE
Bot doesn't reply to user and times out on commands

### ISSUE THREAD

**Issue by titaniumdata** [Dragory/modmailbot#86]
I'm running the bot on my linux system, and i set up everything according to the setup guide, but the bot won't 1) reply to users when we respond in the server message chat and 2) the bot times out and crashes when we use commands like &logs (We set the prefix to &)

What  am I doing wrong here?

**Comment by Dragory** [comment]
What errors are you getting?

**Comment by titaniumdata** [comment]
This is what i get from the terminal output when i run the &logs command:

Loading modules...
Connecting to Discord...
Connected! Now listening to DMs.
Error: Query timed out
    at DNS._ontimeout (/home/titaniumdata/Documents/modmail/modmailbot/node_modules/dns-socket/index.js:99:18)
    at Timeout.ontimeout (/home/titaniumdata/Documents/modmail/modmailbot/node_modules/dns-socket/index.js:53:10)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

I get nothing when I'm trying to respond to a user. The user sees that we are typing, but the message never shows up in their DMs..

**Comment by titaniumdata** [comment]
I have figured out what happened.
1) I was not using the &reply command (stupid me) 
2) It only crashes on me. Any other user is fine - as far as I've seen.

**Comment by Dragory** [comment]
Sorry for not getting back to you on this. Considering you said it only crashes on you, I imagine it hasn't been too much of an issue anymore. That being said, the error seems to indicate a network timeout of some sort, so you might want to look into that.

Do you still want to keep this issue open?

**Comment by titaniumdata** [comment]
This issue can be closed. I'm not messaging myself in the bot anymore (it was just for testing). Thanks for your help!
