### ISSUE TITLE
It worked the first time, but it never worked after it

### ISSUE THREAD

**Issue by itzzsagnik** [Dragory/modmailbot#9]
![image](https://user-images.githubusercontent.com/25751606/27277653-8d36f52a-54fc-11e7-8970-68d979be4588.png)

**Comment by Dragory** [comment]
Did you delete any modmail channels manually? If so, that would likely cause this issue. Always close the channels with `!close` instead.

To fix this, delete the `db/threads.json` file in the bot's folder, then restart the bot (this resets all threads, so be sure to close any pending ones first).

**Comment by Dragory** [comment]
Closed due to inactivity
