### ISSUE TITLE
Bot crashing when closing threads

### ISSUE THREAD

**Issue by titaniumdata** [Dragory/modmailbot#91]
When i use the close command, the thread gets removed successfully, but the bot also crashes. This is the console output:

Loading modules...
Connecting to Discord...
Connected! Now listening to DMs.
[NOTE] Creating new thread channel [username censored]
Closing thread eaee8f54-36eb-40ee-bf29-b6dda653b5e5
Deleting channel 464176581733253121
Error: Couldn't find your IP
    at pify.then.res (/home/titaniumdata/Documents/Titanide Services/Titanide Discord Server/Bots/Titanide Support/modmail/modmailbot/node_modules/public-ip/index.js:48:10)
    at <anonymous>

**Comment by Dragory** [comment]
Seems like it can't find your public IP, which is used for log links, for whatever reason. You should be able to fix this by setting `url` manually in the config instead.

**Comment by Dragory** [comment]
Hey, are you still having this issue? Were you able to fix it with the config option?

**Comment by titaniumdata** [comment]
I managed to fix it by changing the ip in the config to my own, and then just doing localhost in the browser when the thread was closed. Thanks
