### ISSUE TITLE
About the future

### ISSUE THREAD

**Issue by L11K** [Dragory/modmailbot#95]
Is #45 and #55 possible already? Since you said it wasn't possible because the bot didn't have a database (45). The minimum account age would also very helpful. 

Or if we could store the logs/attachments inside the DB then upload to Discord as a file? I have it hosted somewhere where I can get the logs by URL because of limitations in the service.

Either way, I appreciate your work.

**Comment by JonasPardon** [comment]
I submitted a pull request yesterday (#94) for minimum account age, if Dragory merges that it'll be one less thing on your list!

**Comment by L11K** [comment]
Hopefully.

**Comment by JonasPardon** [comment]
Hey @L11K , minimum account ago is now in the latest update, #94 got merged.

**Comment by JustxMeg** [comment]
When will the oauth be live?
