### ISSUE TITLE
How can i make a .BAT

### ISSUE THREAD

**Issue by GeoZzNL** [Dragory/modmailbot#96]
Hello,

Thank you very much for this great bot!

We are planning to use it, but we are interested in starting it using a .bat file

Do you know how we can start node using bat?

Regards

**Comment by Dragory** [comment]
You should be able to make a bat file that simply runs...
```
npm start
```
...in the correct directory to start the bot.

**Comment by GeoZzNL** [comment]
Its working! Amazing. 

Thanks
