### ISSUE TITLE
hello i try to start the bot and get this 

### ISSUE THREAD

**Issue by csj90** [Dragory/modmailbot#99]
https://gyazo.com/3a892a3b7550c8c68abd089e49cab270

**Comment by JonasPardon** [comment]
You filled out your `config.js` wrong. Mind posting here so we can take a look? Make sure there are no tokens in there.

**Comment by csj90** [comment]
i fixed it and is it a thing for the the to create a private text chat for only staff to see on the same discord

**Comment by Dragory** [comment]
It is possible to do that, but a largely untested way to run the bot, so you may encounter some issues. However, if you want to do it that way, here's what you gotta do:

1. Set `mainGuildId` and `mailGuildId` to the same server
2. Set `newThreadCategoryId` to a private category
3. Set `inboxServerPermission` to e.g. `kickMembers` to make sure non-mods can't run bot commands

After this, new threads should be created in the private category set in **2.**, and only members with the specific permission can run bot commands.

**Comment by SamFeniks** [comment]
could it be that this breaks "pingOnBotMention": "true", ? because it doesn't ping when it's on the same server.

**Comment by JonasPardon** [comment]
@SamFeniks you should open a new issue for this, instead of commenting on old threads

**Comment by SamFeniks** [comment]
will do! am new to github.
